/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7dbce1fca443
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { NotraError } from "./notra-error.js";

/**
 * Content generation is unavailable
 */
export type ServiceUnavailableErrorData = {
  error: string;
  jobId?: string | undefined;
};

/**
 * Content generation is unavailable
 */
export class ServiceUnavailableError extends NotraError {
  error: string;
  jobId?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ServiceUnavailableErrorData;

  constructor(
    err: ServiceUnavailableErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.jobId != null) this.jobId = err.jobId;

    this.name = "ServiceUnavailableError";
  }
}

/** @internal */
export const ServiceUnavailableError$inboundSchema: z.ZodMiniType<
  ServiceUnavailableError,
  unknown
> = z.pipe(
  z.object({
    error: types.string(),
    jobId: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ServiceUnavailableError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
