/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bfb1b7baf100
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { NotraError } from "./notra-error.js";

export type RateLimitErrorResponseData = {
  error: string;
  limit: number;
  remaining: number;
  reset: number;
};

export class RateLimitErrorResponse extends NotraError {
  error: string;
  limit: number;
  remaining: number;
  reset: number;

  /** The original data that was passed to this error instance. */
  data$: RateLimitErrorResponseData;

  constructor(
    err: RateLimitErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    this.limit = err.limit;
    this.remaining = err.remaining;
    this.reset = err.reset;

    this.name = "RateLimitErrorResponse";
  }
}

/** @internal */
export const RateLimitErrorResponse$inboundSchema: z.ZodMiniType<
  RateLimitErrorResponse,
  unknown
> = z.pipe(
  z.object({
    error: types.string(),
    limit: types.number(),
    remaining: types.number(),
    reset: types.number(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new RateLimitErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
