/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a86741df1ce3
 */

import { agentCreateAgentSession } from "../funcs/agent-create-agent-session.js";
import { agentListAgentChats } from "../funcs/agent-list-agent-chats.js";
import { agentSendAgentSessionMessage } from "../funcs/agent-send-agent-session-message.js";
import { agentStreamAgentSessionEvents } from "../funcs/agent-stream-agent-session-events.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Agent extends ClientSDK {
  /**
   * Start a durable agent session
   *
   * @remarks
   * The exact eve session protocol the Notra dashboard uses, proxied through API auth. Point any eve client (eve/client, useEveAgent) at /v2 as its host with your API key as a bearer token. Returns the session id and continuation token; stream events from GET /v2/eve/v1/session/{sessionId}/stream.
   */
  async createAgentSession(
    request: models.CreateAgentSessionRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateAgentSessionResponse> {
    return unwrapAsync(agentCreateAgentSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Send a follow-up message or answer a pending input request
   *
   * @remarks
   * Sends the next turn of an agent session. The server binds the session's stored continuation token, so the client-provided one is ignored. Answer input.requested events (tool approvals, questions) from the event stream via inputResponses.
   */
  async sendAgentSessionMessage(
    request: operations.SendAgentSessionMessageRequest,
    options?: RequestOptions,
  ): Promise<operations.SendAgentSessionMessageResponse> {
    return unwrapAsync(agentSendAgentSessionMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * Stream an agent session's events
   *
   * @remarks
   * Durable, replayable eve session event stream (newline-delimited JSON). Pass startIndex to resume from a known position. Includes input.requested events for tool approvals.
   */
  async streamAgentSessionEvents(
    request: operations.StreamAgentSessionEventsRequest,
    options?: RequestOptions,
  ): Promise<operations.StreamAgentSessionEventsResponse> {
    return unwrapAsync(agentStreamAgentSessionEvents(
      this,
      request,
      options,
    ));
  }

  /**
   * List agent sessions
   */
  async listAgentChats(
    request?: operations.ListAgentChatsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListAgentChatsResponse> {
    return unwrapAsync(agentListAgentChats(
      this,
      request,
      options,
    ));
  }
}
