/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 910eab44b075
 */

import { chatsCreateChat } from "../funcs/chats-create-chat.js";
import { chatsGetChat } from "../funcs/chats-get-chat.js";
import { chatsListChats } from "../funcs/chats-list-chats.js";
import { chatsPostChatMessage } from "../funcs/chats-post-chat-message.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chats extends ClientSDK {
  /**
   * List chats
   */
  async listChats(
    options?: RequestOptions,
  ): Promise<models.GetChatsResponse> {
    return unwrapAsync(chatsListChats(
      this,
      options,
    ));
  }

  /**
   * Start a new chat and stream the reply
   */
  async createChat(
    request: models.SendChatMessageRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateChatResponse> {
    return unwrapAsync(chatsCreateChat(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single chat with messages
   */
  async getChat(
    request: operations.GetChatRequest,
    options?: RequestOptions,
  ): Promise<models.GetChatResponse> {
    return unwrapAsync(chatsGetChat(
      this,
      request,
      options,
    ));
  }

  /**
   * Post a message to an existing chat and stream the reply
   */
  async postChatMessage(
    request: operations.PostChatMessageRequest,
    options?: RequestOptions,
  ): Promise<operations.PostChatMessageResponse> {
    return unwrapAsync(chatsPostChatMessage(
      this,
      request,
      options,
    ));
  }
}
