/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 910eab44b075
 */

import { chatsCreateChat } from "../funcs/chats-create-chat.js";
import { chatsGetChatByExternalChannel } from "../funcs/chats-get-chat-by-external-channel.js";
import { chatsGetChat } from "../funcs/chats-get-chat.js";
import { chatsListChats } from "../funcs/chats-list-chats.js";
import { chatsPostChatMessage } from "../funcs/chats-post-chat-message.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chats extends ClientSDK {
  /**
   * List chats
   *
   * @remarks
   * Returns the organization's chat sessions without their messages. Use GET /v1/chats/{chatId} to load a conversation.
   */
  async listChats(
    options?: RequestOptions,
  ): Promise<models.GetChatsResponse> {
    return unwrapAsync(chatsListChats(
      this,
      options,
    ));
  }

  /**
   * Start a new chat and stream the reply
   *
   * @remarks
   * Creates a chat session, sends the first message, and streams the assistant reply. Read the X-Chat-Id response header to continue the conversation with POST /v1/chats/{chatId}.
   */
  async createChat(
    request: models.SendChatMessageRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateChatResponse> {
    return unwrapAsync(chatsCreateChat(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a chat by external channel id
   *
   * @remarks
   * Looks up the chat session linked to a Discord or Slack channel. Link a chat by passing externalChannelId when you create it.
   */
  async getChatByExternalChannel(
    request: operations.GetChatByExternalChannelRequest,
    options?: RequestOptions,
  ): Promise<models.ChatSessionSummary> {
    return unwrapAsync(chatsGetChatByExternalChannel(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single chat with messages
   *
   * @remarks
   * Returns the chat session and its full message history in UI message format.
   */
  async getChat(
    request: operations.GetChatRequest,
    options?: RequestOptions,
  ): Promise<models.GetChatResponse> {
    return unwrapAsync(chatsGetChat(
      this,
      request,
      options,
    ));
  }

  /**
   * Post a message to an existing chat and stream the reply
   *
   * @remarks
   * Appends a user message to the chat and streams the assistant reply. Earlier messages in the chat are included as context automatically.
   */
  async postChatMessage(
    request: operations.PostChatMessageRequest,
    options?: RequestOptions,
  ): Promise<operations.PostChatMessageResponse> {
    return unwrapAsync(chatsPostChatMessage(
      this,
      request,
      options,
    ));
  }
}
