/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 152cac8c63c4
 */

import { contentDeletePost } from "../funcs/content-delete-post.js";
import { contentGetPost } from "../funcs/content-get-post.js";
import { contentListPosts } from "../funcs/content-list-posts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Content extends ClientSDK {
  /**
   * List posts
   */
  async listPosts(
    request?: operations.ListPostsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPostsResponse> {
    return unwrapAsync(contentListPosts(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single post
   */
  async getPost(
    request: operations.GetPostRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPostResponse> {
    return unwrapAsync(contentGetPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a single post
   */
  async deletePost(
    request: operations.DeletePostRequest,
    options?: RequestOptions,
  ): Promise<operations.DeletePostResponse> {
    return unwrapAsync(contentDeletePost(
      this,
      request,
      options,
    ));
  }
}
