/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 152cac8c63c4
 */

import { contentCreateBrandIdentity } from "../funcs/content-create-brand-identity.js";
import { contentCreateGitHubIntegration } from "../funcs/content-create-git-hub-integration.js";
import { contentCreatePostGeneration } from "../funcs/content-create-post-generation.js";
import { contentDeleteBrandIdentity } from "../funcs/content-delete-brand-identity.js";
import { contentDeleteIntegration } from "../funcs/content-delete-integration.js";
import { contentDeletePost } from "../funcs/content-delete-post.js";
import { contentGetBrandIdentityGeneration } from "../funcs/content-get-brand-identity-generation.js";
import { contentGetBrandIdentity } from "../funcs/content-get-brand-identity.js";
import { contentGetPostGeneration } from "../funcs/content-get-post-generation.js";
import { contentGetPost } from "../funcs/content-get-post.js";
import { contentListBrandIdentities } from "../funcs/content-list-brand-identities.js";
import { contentListIntegrations } from "../funcs/content-list-integrations.js";
import { contentListPosts } from "../funcs/content-list-posts.js";
import { contentUpdateBrandIdentity } from "../funcs/content-update-brand-identity.js";
import { contentUpdatePost } from "../funcs/content-update-post.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Content extends ClientSDK {
  /**
   * List posts
   *
   * @remarks
   * Returns posts for the organization the API key belongs to, newest first by default. Only published posts are included unless you pass status=draft,published.
   */
  async listPosts(
    request?: operations.ListPostsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPostsResponse> {
    return unwrapAsync(contentListPosts(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single post
   *
   * @remarks
   * Returns the post. When no post with this ID exists in your organization, the response is still 200 with post set to null.
   */
  async getPost(
    request: operations.GetPostRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPostResponse> {
    return unwrapAsync(contentGetPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a single post
   */
  async deletePost(
    request: operations.DeletePostRequest,
    options?: RequestOptions,
  ): Promise<operations.DeletePostResponse> {
    return unwrapAsync(contentDeletePost(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a single post
   *
   * @remarks
   * Updates any combination of title, slug, markdown, and status. Sending markdown re-renders the stored HTML, and when title is omitted it is taken from the first heading in the markdown, keeping the existing title when the markdown has no heading. Slugs are only accepted for blog posts and changelogs.
   */
  async updatePost(
    request: operations.UpdatePostRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdatePostResponse> {
    return unwrapAsync(contentUpdatePost(
      this,
      request,
      options,
    ));
  }

  /**
   * Queue async post generation
   *
   * @remarks
   * Queues a generation job for one content type and returns 202 with the job. Select sources with integrations.github, integrations.linear, or github.repositories; when no selector is given at all, every connected GitHub integration is used. Poll GET /v1/posts/generate/{jobId} until job.status is completed, failed, or skipped. Notra does not send webhooks when the job finishes.
   */
  async createPostGeneration(
    request: operations.CreatePostGenerationRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePostGenerationResponse> {
    return unwrapAsync(contentCreatePostGeneration(
      this,
      request,
      options,
    ));
  }

  /**
   * Get async post generation status
   *
   * @remarks
   * Returns the job and its event log. job.status moves from queued to running and ends as completed, failed, or skipped. job.postId is set once the post has been created; fetch it with GET /v1/posts/{postId}.
   */
  async getPostGeneration(
    request: operations.GetPostGenerationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPostGenerationResponse> {
    return unwrapAsync(contentGetPostGeneration(
      this,
      request,
      options,
    ));
  }

  /**
   * List available brand identities
   *
   * @remarks
   * Returns every brand identity in the organization, default identity first.
   */
  async listBrandIdentities(
    options?: RequestOptions,
  ): Promise<operations.ListBrandIdentitiesResponse> {
    return unwrapAsync(contentListBrandIdentities(
      this,
      options,
    ));
  }

  /**
   * Queue async brand identity generation
   *
   * @remarks
   * Creates the brand identity immediately, then queues a website analysis that fills in company details, tone, and audience. The first brand identity in an organization becomes the default. Poll GET /v1/brand-identities/generate/{jobId} until job.status is completed or failed.
   */
  async createBrandIdentity(
    request: operations.CreateBrandIdentityRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateBrandIdentityResponse> {
    return unwrapAsync(contentCreateBrandIdentity(
      this,
      request,
      options,
    ));
  }

  /**
   * Get async brand identity generation status
   *
   * @remarks
   * Returns the analysis job. job.status moves from queued to running and ends as completed or failed; job.step shows the current stage while running. Fetch the finished identity with GET /v1/brand-identities/{brandIdentityId}.
   */
  async getBrandIdentityGeneration(
    request: operations.GetBrandIdentityGenerationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetBrandIdentityGenerationResponse> {
    return unwrapAsync(contentGetBrandIdentityGeneration(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single brand identity
   *
   * @remarks
   * Returns the brand identity. When no brand identity with this ID exists in your organization, the response is still 200 with brandIdentity set to null.
   */
  async getBrandIdentity(
    request: operations.GetBrandIdentityRequest,
    options?: RequestOptions,
  ): Promise<operations.GetBrandIdentityResponse> {
    return unwrapAsync(contentGetBrandIdentity(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a single brand identity
   *
   * @remarks
   * Deletes a non-default brand identity and disables any automation triggers that reference it.
   */
  async deleteBrandIdentity(
    request: operations.DeleteBrandIdentityRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteBrandIdentityResponse> {
    return unwrapAsync(contentDeleteBrandIdentity(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a single brand identity
   *
   * @remarks
   * Updates brand identity fields. Pass isDefault: true to make the target brand identity the organization's default.
   */
  async updateBrandIdentity(
    request: operations.UpdateBrandIdentityRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateBrandIdentityResponse> {
    return unwrapAsync(contentUpdateBrandIdentity(
      this,
      request,
      options,
    ));
  }

  /**
   * List available integrations
   *
   * @remarks
   * Returns the enabled GitHub and Linear integrations for the organization. The slack array is always empty.
   */
  async listIntegrations(
    options?: RequestOptions,
  ): Promise<operations.ListIntegrationsResponse> {
    return unwrapAsync(contentListIntegrations(
      this,
      options,
    ));
  }

  /**
   * Create a GitHub integration
   *
   * @remarks
   * Checks that the repository can be read (a personal access token is required for private repositories), connects it, and enables changelog generation for it; blog post and X post outputs start disabled. A webhook secret is generated on creation. Copy the payload URL and secret from the dashboard to receive push and release events.
   */
  async createGitHubIntegration(
    request: operations.CreateGitHubIntegrationRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateGitHubIntegrationResponse> {
    return unwrapAsync(contentCreateGitHubIntegration(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a single integration
   *
   * @remarks
   * Deletes a GitHub or Linear integration. Schedules and event triggers that target the integration are disabled and listed in the response.
   */
  async deleteIntegration(
    request: operations.DeleteIntegrationRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteIntegrationResponse> {
    return unwrapAsync(contentDeleteIntegration(
      this,
      request,
      options,
    ));
  }
}
