/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 43cd9bb36140
 */

import { feedbackGetFeedback } from "../funcs/feedback-get-feedback.js";
import { feedbackListFeedback } from "../funcs/feedback-list-feedback.js";
import { feedbackSubmitFeedback } from "../funcs/feedback-submit-feedback.js";
import { feedbackSubmitOrganizationFeedback } from "../funcs/feedback-submit-organization-feedback.js";
import { feedbackUpdateFeedback } from "../funcs/feedback-update-feedback.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Feedback extends ClientSDK {
  /**
   * Submit feedback to an organization's feedback URL
   *
   * @remarks
   * Record feedback from an AI agent or integration by posting to the organization's feedback URL, as shown on the Feedback page in the dashboard. No credentials are required. Limited per source IP and per organization.
   */
  async submitOrganizationFeedback(
    request: operations.SubmitOrganizationFeedbackRequest,
    options?: RequestOptions,
  ): Promise<operations.SubmitOrganizationFeedbackResponse> {
    return unwrapAsync(feedbackSubmitOrganizationFeedback(
      this,
      request,
      options,
    ));
  }

  /**
   * List feedback
   */
  async listFeedback(
    request?: operations.ListFeedbackRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListFeedbackResponse> {
    return unwrapAsync(feedbackListFeedback(
      this,
      request,
      options,
    ));
  }

  /**
   * Submit feedback with an API key
   *
   * @remarks
   * Record feedback for the organization that owns the credential. Requires an API key with the feedback.write scope. Agents and MCP servers should post to the organization's feedback URL instead.
   */
  async submitFeedback(
    request: models.SubmitFeedbackRequest,
    options?: RequestOptions,
  ): Promise<operations.SubmitFeedbackResponse> {
    return unwrapAsync(feedbackSubmitFeedback(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single feedback entry
   */
  async getFeedback(
    request: operations.GetFeedbackRequest,
    options?: RequestOptions,
  ): Promise<models.FeedbackResponse> {
    return unwrapAsync(feedbackGetFeedback(
      this,
      request,
      options,
    ));
  }

  /**
   * Update feedback status
   */
  async updateFeedback(
    request: operations.UpdateFeedbackRequest,
    options?: RequestOptions,
  ): Promise<models.FeedbackResponse> {
    return unwrapAsync(feedbackUpdateFeedback(
      this,
      request,
      options,
    ));
  }
}
