/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ffd650bcc566
 */

import { schedulesCreateSchedule } from "../funcs/schedules-create-schedule.js";
import { schedulesDeleteSchedule } from "../funcs/schedules-delete-schedule.js";
import { schedulesListSchedules } from "../funcs/schedules-list-schedules.js";
import { schedulesUpdateSchedule } from "../funcs/schedules-update-schedule.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Schedules extends ClientSDK {
  /**
   * List schedules
   */
  async listSchedules(
    request?: operations.ListSchedulesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListSchedulesResponse> {
    return unwrapAsync(schedulesListSchedules(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a schedule
   */
  async createSchedule(
    request: operations.CreateScheduleRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateScheduleResponse> {
    return unwrapAsync(schedulesCreateSchedule(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a schedule
   */
  async deleteSchedule(
    request: operations.DeleteScheduleRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteScheduleResponse> {
    return unwrapAsync(schedulesDeleteSchedule(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a schedule
   */
  async updateSchedule(
    request: operations.UpdateScheduleRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateScheduleResponse> {
    return unwrapAsync(schedulesUpdateSchedule(
      this,
      request,
      options,
    ));
  }
}
