/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Content } from "./content.js";

export class Notra extends ClientSDK {
  private _content?: Content;
  get content(): Content {
    return (this._content ??= new Content(this._options));
  }
}
