/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 847667a72f83
 */

import { skillsCreateSkill } from "../funcs/skills-create-skill.js";
import { skillsDeleteSkill } from "../funcs/skills-delete-skill.js";
import { skillsGetSkill } from "../funcs/skills-get-skill.js";
import { skillsListSkills } from "../funcs/skills-list-skills.js";
import { skillsPatchSkill } from "../funcs/skills-patch-skill.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Skills extends ClientSDK {
  /**
   * List skills
   */
  async listSkills(
    options?: RequestOptions,
  ): Promise<models.ListSkillsResponse> {
    return unwrapAsync(skillsListSkills(
      this,
      options,
    ));
  }

  /**
   * Create a skill
   */
  async createSkill(
    request: models.CreateSkillRequest,
    options?: RequestOptions,
  ): Promise<models.CreateSkillResponse> {
    return unwrapAsync(skillsCreateSkill(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single skill
   */
  async getSkill(
    request: operations.GetSkillRequest,
    options?: RequestOptions,
  ): Promise<models.SkillResponse> {
    return unwrapAsync(skillsGetSkill(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a skill
   */
  async deleteSkill(
    request: operations.DeleteSkillRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteSkillResponse> {
    return unwrapAsync(skillsDeleteSkill(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a skill
   */
  async patchSkill(
    request: operations.PatchSkillRequest,
    options?: RequestOptions,
  ): Promise<models.PatchSkillResponse> {
    return unwrapAsync(skillsPatchSkill(
      this,
      request,
      options,
    ));
  }
}
