/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e879e17d0532
 */

import { webhooksCreateWebhookEndpoint } from "../funcs/webhooks-create-webhook-endpoint.js";
import { webhooksDeleteWebhookEndpoint } from "../funcs/webhooks-delete-webhook-endpoint.js";
import { webhooksGetWebhookDelivery } from "../funcs/webhooks-get-webhook-delivery.js";
import { webhooksListWebhookDeliveries } from "../funcs/webhooks-list-webhook-deliveries.js";
import { webhooksListWebhookEndpoints } from "../funcs/webhooks-list-webhook-endpoints.js";
import { webhooksRetryWebhookDelivery } from "../funcs/webhooks-retry-webhook-delivery.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * List outbound webhook subscriptions
   */
  async listWebhookEndpoints(
    options?: RequestOptions,
  ): Promise<operations.ListWebhookEndpointsResponse> {
    return unwrapAsync(webhooksListWebhookEndpoints(
      this,
      options,
    ));
  }

  /**
   * Subscribe an HTTPS endpoint to Notra events
   */
  async createWebhookEndpoint(
    request: operations.CreateWebhookEndpointRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateWebhookEndpointResponse> {
    return unwrapAsync(webhooksCreateWebhookEndpoint(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a webhook subscription and cancel unsent deliveries
   */
  async deleteWebhookEndpoint(
    request: operations.DeleteWebhookEndpointRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteWebhookEndpointResponse> {
    return unwrapAsync(webhooksDeleteWebhookEndpoint(
      this,
      request,
      options,
    ));
  }

  /**
   * List webhook deliveries
   */
  async listWebhookDeliveries(
    request?: operations.ListWebhookDeliveriesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListWebhookDeliveriesResponse> {
    return unwrapAsync(webhooksListWebhookDeliveries(
      this,
      request,
      options,
    ));
  }

  /**
   * Get payload and attempt history for a delivery
   */
  async getWebhookDelivery(
    request: operations.GetWebhookDeliveryRequest,
    options?: RequestOptions,
  ): Promise<operations.GetWebhookDeliveryResponse> {
    return unwrapAsync(webhooksGetWebhookDelivery(
      this,
      request,
      options,
    ));
  }

  /**
   * Retry a failed delivery, retaining its history
   */
  async retryWebhookDelivery(
    request: operations.RetryWebhookDeliveryRequest,
    options?: RequestOptions,
  ): Promise<operations.RetryWebhookDeliveryResponse> {
    return unwrapAsync(webhooksRetryWebhookDelivery(
      this,
      request,
      options,
    ));
  }
}
