/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 725ebf2530f7
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @usenotra/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx discoveryGetPublicApiStatus.example.ts
 */

import { Notra } from "@usenotra/sdk";

const notra = new Notra();

async function main() {
  const result = await notra.discovery.getPublicApiStatus();

  console.log(result);
}

main().catch(console.error);
