/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3b783051787b
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CancelPostScheduleRequest = {
  postId: string;
};

export type CancelPostScheduleResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CancelPostScheduleResponse;
};

/** @internal */
export type CancelPostScheduleRequest$Outbound = {
  postId: string;
};

/** @internal */
export const CancelPostScheduleRequest$outboundSchema: z.ZodMiniType<
  CancelPostScheduleRequest$Outbound,
  CancelPostScheduleRequest
> = z.object({
  postId: z.string(),
});

export function cancelPostScheduleRequestToJSON(
  cancelPostScheduleRequest: CancelPostScheduleRequest,
): string {
  return JSON.stringify(
    CancelPostScheduleRequest$outboundSchema.parse(cancelPostScheduleRequest),
  );
}

/** @internal */
export const CancelPostScheduleResponse$inboundSchema: z.ZodMiniType<
  CancelPostScheduleResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.CancelPostScheduleResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function cancelPostScheduleResponseFromJSON(
  jsonString: string,
): SafeParseResult<CancelPostScheduleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CancelPostScheduleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CancelPostScheduleResponse' from JSON`,
  );
}
