/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3ce0f3511b73
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type CreateGeoPromptRequest = {
  projectId: string;
  body: models.CreateGeoPromptRequest;
};

/** @internal */
export type CreateGeoPromptRequest$Outbound = {
  projectId: string;
  body: models.CreateGeoPromptRequest$Outbound;
};

/** @internal */
export const CreateGeoPromptRequest$outboundSchema: z.ZodMiniType<
  CreateGeoPromptRequest$Outbound,
  CreateGeoPromptRequest
> = z.object({
  projectId: z.string(),
  body: models.CreateGeoPromptRequest$outboundSchema,
});

export function createGeoPromptRequestToJSON(
  createGeoPromptRequest: CreateGeoPromptRequest,
): string {
  return JSON.stringify(
    CreateGeoPromptRequest$outboundSchema.parse(createGeoPromptRequest),
  );
}
