/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3a70fdfe59ab
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const CreatePostContentTypeRequest = {
  BlogPost: "blog_post",
  Changelog: "changelog",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
} as const;
export type CreatePostContentTypeRequest = ClosedEnum<
  typeof CreatePostContentTypeRequest
>;

export const CreatePostStatusRequest = {
  Draft: "draft",
  Published: "published",
} as const;
export type CreatePostStatusRequest = ClosedEnum<
  typeof CreatePostStatusRequest
>;

/**
 * Slugs are normalized to lowercase letters, numbers, and hyphens and only accepted for blog posts and changelogs. Omit markdown to create an empty post you fill in later.
 */
export type CreatePostRequest = {
  title: string;
  contentType: CreatePostContentTypeRequest;
  slug?: string | null | undefined;
  markdown?: string | undefined;
  status?: CreatePostStatusRequest | undefined;
};

export type CreatePostOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export const CreatePostPostContentType = {
  Changelog: "changelog",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
  BlogPost: "blog_post",
  InvestorUpdate: "investor_update",
  Image: "image",
} as const;
export type CreatePostPostContentType = OpenEnum<
  typeof CreatePostPostContentType
>;

export const CreatePostPostStatus = {
  Draft: "draft",
  Published: "published",
} as const;
export type CreatePostPostStatus = OpenEnum<typeof CreatePostPostStatus>;

export type CreatePostPost = {
  id: string;
  title: string;
  slug: string | null;
  /**
   * Rendered HTML for text posts. For image posts, this is the public CDN URL of the rendered image.
   */
  content: string;
  /**
   * Public CDN URL of the generated HTML artifact for image posts. Null for non-image posts.
   */
  htmlUrl: string | null;
  /**
   * Markdown source for text posts. Null for image posts.
   */
  markdown: string | null;
  /**
   * Legacy inline generated HTML for image posts. New generated image HTML is stored as htmlUrl. Null for non-image posts.
   */
  rawHtml: string | null;
  recommendations: string | null;
  contentType: CreatePostPostContentType;
  sourceMetadata?: any | undefined;
  status: CreatePostPostStatus;
  createdAt: string;
  updatedAt: string;
};

/**
 * Post created successfully
 */
export type CreatePostResponseBody = {
  organization: CreatePostOrganization;
  post: CreatePostPost;
};

export type CreatePostResponse = {
  headers: { [k: string]: Array<string> };
  result: CreatePostResponseBody;
};

/** @internal */
export const CreatePostContentTypeRequest$outboundSchema: z.ZodMiniEnum<
  typeof CreatePostContentTypeRequest
> = z.enum(CreatePostContentTypeRequest);

/** @internal */
export const CreatePostStatusRequest$outboundSchema: z.ZodMiniEnum<
  typeof CreatePostStatusRequest
> = z.enum(CreatePostStatusRequest);

/** @internal */
export type CreatePostRequest$Outbound = {
  title: string;
  contentType: string;
  slug?: string | null | undefined;
  markdown?: string | undefined;
  status: string;
};

/** @internal */
export const CreatePostRequest$outboundSchema: z.ZodMiniType<
  CreatePostRequest$Outbound,
  CreatePostRequest
> = z.object({
  title: z.string(),
  contentType: CreatePostContentTypeRequest$outboundSchema,
  slug: z.optional(z.nullable(z.string())),
  markdown: z.optional(z.string()),
  status: z._default(CreatePostStatusRequest$outboundSchema, "draft"),
});

export function createPostRequestToJSON(
  createPostRequest: CreatePostRequest,
): string {
  return JSON.stringify(
    CreatePostRequest$outboundSchema.parse(createPostRequest),
  );
}

/** @internal */
export const CreatePostOrganization$inboundSchema: z.ZodMiniType<
  CreatePostOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function createPostOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<CreatePostOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePostOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePostOrganization' from JSON`,
  );
}

/** @internal */
export const CreatePostPostContentType$inboundSchema: z.ZodMiniType<
  CreatePostPostContentType,
  unknown
> = openEnums.inboundSchema(CreatePostPostContentType);

/** @internal */
export const CreatePostPostStatus$inboundSchema: z.ZodMiniType<
  CreatePostPostStatus,
  unknown
> = openEnums.inboundSchema(CreatePostPostStatus);

/** @internal */
export const CreatePostPost$inboundSchema: z.ZodMiniType<
  CreatePostPost,
  unknown
> = z.object({
  id: types.string(),
  title: types.string(),
  slug: types.nullable(types.string()),
  content: types.string(),
  htmlUrl: types.nullable(types.string()),
  markdown: types.nullable(types.string()),
  rawHtml: types.nullable(types.string()),
  recommendations: types.nullable(types.string()),
  contentType: CreatePostPostContentType$inboundSchema,
  sourceMetadata: types.optional(z.any()),
  status: CreatePostPostStatus$inboundSchema,
  createdAt: types.string(),
  updatedAt: types.string(),
});

export function createPostPostFromJSON(
  jsonString: string,
): SafeParseResult<CreatePostPost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePostPost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePostPost' from JSON`,
  );
}

/** @internal */
export const CreatePostResponseBody$inboundSchema: z.ZodMiniType<
  CreatePostResponseBody,
  unknown
> = z.object({
  organization: z.lazy(() => CreatePostOrganization$inboundSchema),
  post: z.lazy(() => CreatePostPost$inboundSchema),
});

export function createPostResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreatePostResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePostResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePostResponseBody' from JSON`,
  );
}

/** @internal */
export const CreatePostResponse$inboundSchema: z.ZodMiniType<
  CreatePostResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => CreatePostResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePostResponse' from JSON`,
  );
}
