/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 26fb581cbfda
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CreateGitHubIntegrationRequest = {
  owner: string;
  repo: string;
  branch?: string | null | undefined;
  token?: string | null | undefined;
};

export type CreateGitHubIntegrationGithub = {
  id: string;
  displayName: string;
  owner: string | null;
  repo: string | null;
  defaultBranch: string | null;
};

export type CreateGitHubIntegrationOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

/**
 * GitHub integration created successfully
 */
export type CreateGitHubIntegrationResponse = {
  github: CreateGitHubIntegrationGithub;
  organization: CreateGitHubIntegrationOrganization;
};

/** @internal */
export type CreateGitHubIntegrationRequest$Outbound = {
  owner: string;
  repo: string;
  branch?: string | null | undefined;
  token?: string | null | undefined;
};

/** @internal */
export const CreateGitHubIntegrationRequest$outboundSchema: z.ZodMiniType<
  CreateGitHubIntegrationRequest$Outbound,
  CreateGitHubIntegrationRequest
> = z.object({
  owner: z.string(),
  repo: z.string(),
  branch: z.optional(z.nullable(z.string())),
  token: z.optional(z.nullable(z.string())),
});

export function createGitHubIntegrationRequestToJSON(
  createGitHubIntegrationRequest: CreateGitHubIntegrationRequest,
): string {
  return JSON.stringify(
    CreateGitHubIntegrationRequest$outboundSchema.parse(
      createGitHubIntegrationRequest,
    ),
  );
}

/** @internal */
export const CreateGitHubIntegrationGithub$inboundSchema: z.ZodMiniType<
  CreateGitHubIntegrationGithub,
  unknown
> = z.object({
  id: types.string(),
  displayName: types.string(),
  owner: types.nullable(types.string()),
  repo: types.nullable(types.string()),
  defaultBranch: types.nullable(types.string()),
});

export function createGitHubIntegrationGithubFromJSON(
  jsonString: string,
): SafeParseResult<CreateGitHubIntegrationGithub, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGitHubIntegrationGithub$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGitHubIntegrationGithub' from JSON`,
  );
}

/** @internal */
export const CreateGitHubIntegrationOrganization$inboundSchema: z.ZodMiniType<
  CreateGitHubIntegrationOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function createGitHubIntegrationOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<CreateGitHubIntegrationOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateGitHubIntegrationOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGitHubIntegrationOrganization' from JSON`,
  );
}

/** @internal */
export const CreateGitHubIntegrationResponse$inboundSchema: z.ZodMiniType<
  CreateGitHubIntegrationResponse,
  unknown
> = z.object({
  github: z.lazy(() => CreateGitHubIntegrationGithub$inboundSchema),
  organization: z.lazy(() => CreateGitHubIntegrationOrganization$inboundSchema),
});

export function createGitHubIntegrationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateGitHubIntegrationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGitHubIntegrationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGitHubIntegrationResponse' from JSON`,
  );
}
