/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ce3fc630292a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateGeoScanRequest = {
  projectId: string;
};

export type CreateGeoScanResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CreateGeoScanResponse;
};

/** @internal */
export type CreateGeoScanRequest$Outbound = {
  projectId: string;
};

/** @internal */
export const CreateGeoScanRequest$outboundSchema: z.ZodMiniType<
  CreateGeoScanRequest$Outbound,
  CreateGeoScanRequest
> = z.object({
  projectId: z.string(),
});

export function createGeoScanRequestToJSON(
  createGeoScanRequest: CreateGeoScanRequest,
): string {
  return JSON.stringify(
    CreateGeoScanRequest$outboundSchema.parse(createGeoScanRequest),
  );
}

/** @internal */
export const CreateGeoScanResponse$inboundSchema: z.ZodMiniType<
  CreateGeoScanResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.CreateGeoScanResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createGeoScanResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateGeoScanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGeoScanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGeoScanResponse' from JSON`,
  );
}
