/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b523c9a831d3
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CreateChatResponse = {
  headers: { [k: string]: Array<string> };
  result: string;
};

/** @internal */
export const CreateChatResponse$inboundSchema: z.ZodMiniType<
  CreateChatResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createChatResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateChatResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateChatResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateChatResponse' from JSON`,
  );
}
