/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c7660793646d
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const EventRequest = {
  PostGenerationCompleted: "post.generation.completed",
  PostGenerationFailed: "post.generation.failed",
  PostGenerationSkipped: "post.generation.skipped",
  BrandIdentityGenerationCompleted: "brand_identity.generation.completed",
  BrandIdentityGenerationFailed: "brand_identity.generation.failed",
  PostPublished: "post.published",
  PostCreated: "post.created",
  PostUpdated: "post.updated",
  PostDeleted: "post.deleted",
  PostUnpublished: "post.unpublished",
  GeoScanCompleted: "geo.scan.completed",
  GeoScanFailed: "geo.scan.failed",
} as const;
export type EventRequest = ClosedEnum<typeof EventRequest>;

export type CreateWebhookEndpointRequest = {
  url: string;
  events: Array<EventRequest>;
};

export const CreateWebhookEndpointEndpointEvent = {
  PostGenerationCompleted: "post.generation.completed",
  PostGenerationFailed: "post.generation.failed",
  PostGenerationSkipped: "post.generation.skipped",
  BrandIdentityGenerationCompleted: "brand_identity.generation.completed",
  BrandIdentityGenerationFailed: "brand_identity.generation.failed",
  PostPublished: "post.published",
  PostCreated: "post.created",
  PostUpdated: "post.updated",
  PostDeleted: "post.deleted",
  PostUnpublished: "post.unpublished",
  GeoScanCompleted: "geo.scan.completed",
  GeoScanFailed: "geo.scan.failed",
} as const;
export type CreateWebhookEndpointEndpointEvent = OpenEnum<
  typeof CreateWebhookEndpointEndpointEvent
>;

export type CreateWebhookEndpointEndpoint = {
  id: string;
  organizationId: string;
  url: string;
  events: Array<CreateWebhookEndpointEndpointEvent>;
  enabled: boolean;
  createdAt: string;
};

/**
 * Endpoint and one-time signing secret
 */
export type CreateWebhookEndpointResponse = {
  endpoint: CreateWebhookEndpointEndpoint;
  secret: string;
};

/** @internal */
export const EventRequest$outboundSchema: z.ZodMiniEnum<typeof EventRequest> = z
  .enum(EventRequest);

/** @internal */
export type CreateWebhookEndpointRequest$Outbound = {
  url: string;
  events: Array<string>;
};

/** @internal */
export const CreateWebhookEndpointRequest$outboundSchema: z.ZodMiniType<
  CreateWebhookEndpointRequest$Outbound,
  CreateWebhookEndpointRequest
> = z.object({
  url: z.string(),
  events: z.array(EventRequest$outboundSchema),
});

export function createWebhookEndpointRequestToJSON(
  createWebhookEndpointRequest: CreateWebhookEndpointRequest,
): string {
  return JSON.stringify(
    CreateWebhookEndpointRequest$outboundSchema.parse(
      createWebhookEndpointRequest,
    ),
  );
}

/** @internal */
export const CreateWebhookEndpointEndpointEvent$inboundSchema: z.ZodMiniType<
  CreateWebhookEndpointEndpointEvent,
  unknown
> = openEnums.inboundSchema(CreateWebhookEndpointEndpointEvent);

/** @internal */
export const CreateWebhookEndpointEndpoint$inboundSchema: z.ZodMiniType<
  CreateWebhookEndpointEndpoint,
  unknown
> = z.object({
  id: types.string(),
  organizationId: types.string(),
  url: types.string(),
  events: z.array(CreateWebhookEndpointEndpointEvent$inboundSchema),
  enabled: types.boolean(),
  createdAt: types.string(),
});

export function createWebhookEndpointEndpointFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookEndpointEndpoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookEndpointEndpoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookEndpointEndpoint' from JSON`,
  );
}

/** @internal */
export const CreateWebhookEndpointResponse$inboundSchema: z.ZodMiniType<
  CreateWebhookEndpointResponse,
  unknown
> = z.object({
  endpoint: z.lazy(() => CreateWebhookEndpointEndpoint$inboundSchema),
  secret: types.string(),
});

export function createWebhookEndpointResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookEndpointResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookEndpointResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookEndpointResponse' from JSON`,
  );
}
