/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3a526dc77340
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CreateBrandIdentityRequest = {
  name?: string | undefined;
  websiteUrl: string;
};

export type CreateBrandIdentityOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export const CreateBrandIdentityStatus = {
  Queued: "queued",
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
export type CreateBrandIdentityStatus = OpenEnum<
  typeof CreateBrandIdentityStatus
>;

export const CreateBrandIdentityStep = {
  Scraping: "scraping",
  Extracting: "extracting",
  Saving: "saving",
} as const;
export type CreateBrandIdentityStep = OpenEnum<typeof CreateBrandIdentityStep>;

export type CreateBrandIdentityJob = {
  id: string;
  organizationId: string;
  brandIdentityId: string;
  status: CreateBrandIdentityStatus;
  step: CreateBrandIdentityStep | null;
  currentStep: number;
  totalSteps: number;
  workflowRunId: string | null;
  error: string | null;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};

/**
 * Brand identity generation queued successfully
 */
export type CreateBrandIdentityResponseBody = {
  organization: CreateBrandIdentityOrganization;
  job: CreateBrandIdentityJob;
};

export type CreateBrandIdentityResponse = {
  headers: { [k: string]: Array<string> };
  result: CreateBrandIdentityResponseBody;
};

/** @internal */
export type CreateBrandIdentityRequest$Outbound = {
  name?: string | undefined;
  websiteUrl: string;
};

/** @internal */
export const CreateBrandIdentityRequest$outboundSchema: z.ZodMiniType<
  CreateBrandIdentityRequest$Outbound,
  CreateBrandIdentityRequest
> = z.object({
  name: z.optional(z.string()),
  websiteUrl: z.string(),
});

export function createBrandIdentityRequestToJSON(
  createBrandIdentityRequest: CreateBrandIdentityRequest,
): string {
  return JSON.stringify(
    CreateBrandIdentityRequest$outboundSchema.parse(createBrandIdentityRequest),
  );
}

/** @internal */
export const CreateBrandIdentityOrganization$inboundSchema: z.ZodMiniType<
  CreateBrandIdentityOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function createBrandIdentityOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<CreateBrandIdentityOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBrandIdentityOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBrandIdentityOrganization' from JSON`,
  );
}

/** @internal */
export const CreateBrandIdentityStatus$inboundSchema: z.ZodMiniType<
  CreateBrandIdentityStatus,
  unknown
> = openEnums.inboundSchema(CreateBrandIdentityStatus);

/** @internal */
export const CreateBrandIdentityStep$inboundSchema: z.ZodMiniType<
  CreateBrandIdentityStep,
  unknown
> = openEnums.inboundSchema(CreateBrandIdentityStep);

/** @internal */
export const CreateBrandIdentityJob$inboundSchema: z.ZodMiniType<
  CreateBrandIdentityJob,
  unknown
> = z.object({
  id: types.string(),
  organizationId: types.string(),
  brandIdentityId: types.string(),
  status: CreateBrandIdentityStatus$inboundSchema,
  step: types.nullable(CreateBrandIdentityStep$inboundSchema),
  currentStep: types.number(),
  totalSteps: types.number(),
  workflowRunId: types.nullable(types.string()),
  error: types.nullable(types.string()),
  createdAt: types.string(),
  updatedAt: types.string(),
  completedAt: types.nullable(types.string()),
});

export function createBrandIdentityJobFromJSON(
  jsonString: string,
): SafeParseResult<CreateBrandIdentityJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBrandIdentityJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBrandIdentityJob' from JSON`,
  );
}

/** @internal */
export const CreateBrandIdentityResponseBody$inboundSchema: z.ZodMiniType<
  CreateBrandIdentityResponseBody,
  unknown
> = z.object({
  organization: z.lazy(() => CreateBrandIdentityOrganization$inboundSchema),
  job: z.lazy(() => CreateBrandIdentityJob$inboundSchema),
});

export function createBrandIdentityResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateBrandIdentityResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBrandIdentityResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBrandIdentityResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateBrandIdentityResponse$inboundSchema: z.ZodMiniType<
  CreateBrandIdentityResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => CreateBrandIdentityResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createBrandIdentityResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBrandIdentityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBrandIdentityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBrandIdentityResponse' from JSON`,
  );
}
