/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e21467a02666
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type CreateGeoSequenceRequest = {
  projectId: string;
  body: models.CreateGeoSequenceRequest;
};

/** @internal */
export type CreateGeoSequenceRequest$Outbound = {
  projectId: string;
  body: models.CreateGeoSequenceRequest$Outbound;
};

/** @internal */
export const CreateGeoSequenceRequest$outboundSchema: z.ZodMiniType<
  CreateGeoSequenceRequest$Outbound,
  CreateGeoSequenceRequest
> = z.object({
  projectId: z.string(),
  body: models.CreateGeoSequenceRequest$outboundSchema,
});

export function createGeoSequenceRequestToJSON(
  createGeoSequenceRequest: CreateGeoSequenceRequest,
): string {
  return JSON.stringify(
    CreateGeoSequenceRequest$outboundSchema.parse(createGeoSequenceRequest),
  );
}
