/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b523c9a831d3
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateChatResponse = models.SendChatMessageQueuedResponse | string;

/** @internal */
export const CreateChatResponse$inboundSchema: z.ZodMiniType<
  CreateChatResponse,
  unknown
> = smartUnion([
  models.SendChatMessageQueuedResponse$inboundSchema,
  types.string(),
]);

export function createChatResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateChatResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateChatResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateChatResponse' from JSON`,
  );
}
