/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 34978b6e683a
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Always cron for schedules.
 */
export const CreateScheduleSourceTypeRequest = {
  Cron: "cron",
} as const;
/**
 * Always cron for schedules.
 */
export type CreateScheduleSourceTypeRequest = ClosedEnum<
  typeof CreateScheduleSourceTypeRequest
>;

/**
 * How often the schedule runs.
 */
export const FrequencyRequest = {
  Daily: "daily",
  Weekly: "weekly",
  Monthly: "monthly",
} as const;
/**
 * How often the schedule runs.
 */
export type FrequencyRequest = ClosedEnum<typeof FrequencyRequest>;

export type CronRequest = {
  /**
   * How often the schedule runs.
   */
  frequency: FrequencyRequest;
  /**
   * Hour of the day to run, in UTC (0-23).
   */
  hour: number;
  /**
   * Minute of the hour to run (0-59).
   */
  minute: number;
  /**
   * Day of the week for weekly schedules, 0 (Sunday) to 6 (Saturday). Required when frequency is weekly.
   */
  dayOfWeek?: number | undefined;
  /**
   * Day of the month for monthly schedules (1-31). Required when frequency is monthly.
   */
  dayOfMonth?: number | undefined;
};

export type CreateScheduleSourceConfigRequest = {
  cron: CronRequest;
};

export type CreateScheduleTargetsRequest = {
  /**
   * GitHub integration IDs to generate from, as returned by GET /v1/integrations.
   */
  repositoryIds: Array<string>;
};

/**
 * Type of content each run generates.
 */
export const CreateScheduleOutputTypeRequest = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
  Image: "image",
} as const;
/**
 * Type of content each run generates.
 */
export type CreateScheduleOutputTypeRequest = ClosedEnum<
  typeof CreateScheduleOutputTypeRequest
>;

/**
 * Where auto-published posts are sent.
 */
export const CreateSchedulePublishDestinationRequest = {
  Webflow: "webflow",
  Framer: "framer",
  Custom: "custom",
} as const;
/**
 * Where auto-published posts are sent.
 */
export type CreateSchedulePublishDestinationRequest = ClosedEnum<
  typeof CreateSchedulePublishDestinationRequest
>;

export type CreateScheduleOutputConfigRequest = {
  /**
   * Where auto-published posts are sent.
   */
  publishDestination?: CreateSchedulePublishDestinationRequest | undefined;
  /**
   * Brand identity ID to write in. Defaults to the organization's default brand identity.
   */
  brandVoiceId?: string | undefined;
};

/**
 * How far back each run collects source activity.
 */
export const CreateScheduleLookbackWindowRequest = {
  CurrentDay: "current_day",
  Yesterday: "yesterday",
  Last7Days: "last_7_days",
  Last14Days: "last_14_days",
  Last30Days: "last_30_days",
} as const;
/**
 * How far back each run collects source activity.
 */
export type CreateScheduleLookbackWindowRequest = ClosedEnum<
  typeof CreateScheduleLookbackWindowRequest
>;

export type CreateScheduleRequest = {
  /**
   * Display name shown in the dashboard.
   */
  name: string;
  /**
   * Always cron for schedules.
   */
  sourceType: CreateScheduleSourceTypeRequest;
  sourceConfig: CreateScheduleSourceConfigRequest;
  targets: CreateScheduleTargetsRequest;
  /**
   * Type of content each run generates.
   */
  outputType: CreateScheduleOutputTypeRequest;
  outputConfig?: CreateScheduleOutputConfigRequest | undefined;
  /**
   * Whether the schedule runs. Disabled schedules are stored but never fire.
   */
  enabled: boolean;
  /**
   * Publish generated posts automatically instead of saving them as drafts.
   */
  autoPublish?: boolean | undefined;
  /**
   * How far back each run collects source activity.
   */
  lookbackWindow?: CreateScheduleLookbackWindowRequest | undefined;
};

export const CreateScheduleSourceTypeResponse = {
  Cron: "cron",
} as const;
export type CreateScheduleSourceTypeResponse = ClosedEnum<
  typeof CreateScheduleSourceTypeResponse
>;

/**
 * How often the schedule runs.
 */
export const CreateScheduleFrequencyResponse = {
  Daily: "daily",
  Weekly: "weekly",
  Monthly: "monthly",
} as const;
/**
 * How often the schedule runs.
 */
export type CreateScheduleFrequencyResponse = OpenEnum<
  typeof CreateScheduleFrequencyResponse
>;

export type CreateScheduleCronResponse = {
  /**
   * How often the schedule runs.
   */
  frequency: CreateScheduleFrequencyResponse;
  /**
   * Hour of the day to run, in UTC (0-23).
   */
  hour: number;
  /**
   * Minute of the hour to run (0-59).
   */
  minute: number;
  /**
   * Day of the week for weekly schedules, 0 (Sunday) to 6 (Saturday). Required when frequency is weekly.
   */
  dayOfWeek?: number | undefined;
  /**
   * Day of the month for monthly schedules (1-31). Required when frequency is monthly.
   */
  dayOfMonth?: number | undefined;
};

export type CreateScheduleSourceConfigResponse = {
  cron: CreateScheduleCronResponse;
};

export type CreateScheduleTargetsResponse = {
  /**
   * GitHub integration IDs to generate from, as returned by GET /v1/integrations.
   */
  repositoryIds: Array<string>;
};

export const CreateScheduleOutputTypeResponse = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
  Image: "image",
} as const;
export type CreateScheduleOutputTypeResponse = OpenEnum<
  typeof CreateScheduleOutputTypeResponse
>;

/**
 * Where auto-published posts are sent.
 */
export const CreateSchedulePublishDestinationResponse = {
  Webflow: "webflow",
  Framer: "framer",
  Custom: "custom",
} as const;
/**
 * Where auto-published posts are sent.
 */
export type CreateSchedulePublishDestinationResponse = OpenEnum<
  typeof CreateSchedulePublishDestinationResponse
>;

export type CreateScheduleOutputConfigResponse = {
  /**
   * Where auto-published posts are sent.
   */
  publishDestination?: CreateSchedulePublishDestinationResponse | undefined;
  /**
   * Brand identity ID to write in. Defaults to the organization's default brand identity.
   */
  brandVoiceId?: string | undefined;
};

export const CreateScheduleLookbackWindowResponse = {
  CurrentDay: "current_day",
  Yesterday: "yesterday",
  Last7Days: "last_7_days",
  Last14Days: "last_14_days",
  Last30Days: "last_30_days",
} as const;
export type CreateScheduleLookbackWindowResponse = OpenEnum<
  typeof CreateScheduleLookbackWindowResponse
>;

export type CreateScheduleSchedule = {
  id: string;
  organizationId: string;
  name: string;
  sourceType: CreateScheduleSourceTypeResponse;
  sourceConfig: CreateScheduleSourceConfigResponse;
  targets: CreateScheduleTargetsResponse;
  outputType: CreateScheduleOutputTypeResponse;
  outputConfig?: CreateScheduleOutputConfigResponse | null | undefined;
  enabled: boolean;
  autoPublish: boolean;
  createdAt: string;
  updatedAt: string;
  lookbackWindow: CreateScheduleLookbackWindowResponse;
};

export type CreateScheduleOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

/**
 * Schedule created successfully
 */
export type CreateScheduleResponse = {
  schedule: CreateScheduleSchedule;
  organization: CreateScheduleOrganization;
};

/** @internal */
export const CreateScheduleSourceTypeRequest$outboundSchema: z.ZodMiniEnum<
  typeof CreateScheduleSourceTypeRequest
> = z.enum(CreateScheduleSourceTypeRequest);

/** @internal */
export const FrequencyRequest$outboundSchema: z.ZodMiniEnum<
  typeof FrequencyRequest
> = z.enum(FrequencyRequest);

/** @internal */
export type CronRequest$Outbound = {
  frequency: string;
  hour: number;
  minute: number;
  dayOfWeek?: number | undefined;
  dayOfMonth?: number | undefined;
};

/** @internal */
export const CronRequest$outboundSchema: z.ZodMiniType<
  CronRequest$Outbound,
  CronRequest
> = z.object({
  frequency: FrequencyRequest$outboundSchema,
  hour: z.int(),
  minute: z.int(),
  dayOfWeek: z.optional(z.int()),
  dayOfMonth: z.optional(z.int()),
});

export function cronRequestToJSON(cronRequest: CronRequest): string {
  return JSON.stringify(CronRequest$outboundSchema.parse(cronRequest));
}

/** @internal */
export type CreateScheduleSourceConfigRequest$Outbound = {
  cron: CronRequest$Outbound;
};

/** @internal */
export const CreateScheduleSourceConfigRequest$outboundSchema: z.ZodMiniType<
  CreateScheduleSourceConfigRequest$Outbound,
  CreateScheduleSourceConfigRequest
> = z.object({
  cron: z.lazy(() => CronRequest$outboundSchema),
});

export function createScheduleSourceConfigRequestToJSON(
  createScheduleSourceConfigRequest: CreateScheduleSourceConfigRequest,
): string {
  return JSON.stringify(
    CreateScheduleSourceConfigRequest$outboundSchema.parse(
      createScheduleSourceConfigRequest,
    ),
  );
}

/** @internal */
export type CreateScheduleTargetsRequest$Outbound = {
  repositoryIds: Array<string>;
};

/** @internal */
export const CreateScheduleTargetsRequest$outboundSchema: z.ZodMiniType<
  CreateScheduleTargetsRequest$Outbound,
  CreateScheduleTargetsRequest
> = z.object({
  repositoryIds: z.array(z.string()),
});

export function createScheduleTargetsRequestToJSON(
  createScheduleTargetsRequest: CreateScheduleTargetsRequest,
): string {
  return JSON.stringify(
    CreateScheduleTargetsRequest$outboundSchema.parse(
      createScheduleTargetsRequest,
    ),
  );
}

/** @internal */
export const CreateScheduleOutputTypeRequest$outboundSchema: z.ZodMiniEnum<
  typeof CreateScheduleOutputTypeRequest
> = z.enum(CreateScheduleOutputTypeRequest);

/** @internal */
export const CreateSchedulePublishDestinationRequest$outboundSchema:
  z.ZodMiniEnum<typeof CreateSchedulePublishDestinationRequest> = z.enum(
    CreateSchedulePublishDestinationRequest,
  );

/** @internal */
export type CreateScheduleOutputConfigRequest$Outbound = {
  publishDestination?: string | undefined;
  brandVoiceId?: string | undefined;
};

/** @internal */
export const CreateScheduleOutputConfigRequest$outboundSchema: z.ZodMiniType<
  CreateScheduleOutputConfigRequest$Outbound,
  CreateScheduleOutputConfigRequest
> = z.object({
  publishDestination: z.optional(
    CreateSchedulePublishDestinationRequest$outboundSchema,
  ),
  brandVoiceId: z.optional(z.string()),
});

export function createScheduleOutputConfigRequestToJSON(
  createScheduleOutputConfigRequest: CreateScheduleOutputConfigRequest,
): string {
  return JSON.stringify(
    CreateScheduleOutputConfigRequest$outboundSchema.parse(
      createScheduleOutputConfigRequest,
    ),
  );
}

/** @internal */
export const CreateScheduleLookbackWindowRequest$outboundSchema: z.ZodMiniEnum<
  typeof CreateScheduleLookbackWindowRequest
> = z.enum(CreateScheduleLookbackWindowRequest);

/** @internal */
export type CreateScheduleRequest$Outbound = {
  name: string;
  sourceType: string;
  sourceConfig: CreateScheduleSourceConfigRequest$Outbound;
  targets: CreateScheduleTargetsRequest$Outbound;
  outputType: string;
  outputConfig?: CreateScheduleOutputConfigRequest$Outbound | undefined;
  enabled: boolean;
  autoPublish: boolean;
  lookbackWindow: string;
};

/** @internal */
export const CreateScheduleRequest$outboundSchema: z.ZodMiniType<
  CreateScheduleRequest$Outbound,
  CreateScheduleRequest
> = z.object({
  name: z.string(),
  sourceType: CreateScheduleSourceTypeRequest$outboundSchema,
  sourceConfig: z.lazy(() => CreateScheduleSourceConfigRequest$outboundSchema),
  targets: z.lazy(() => CreateScheduleTargetsRequest$outboundSchema),
  outputType: CreateScheduleOutputTypeRequest$outboundSchema,
  outputConfig: z.optional(
    z.lazy(() => CreateScheduleOutputConfigRequest$outboundSchema),
  ),
  enabled: z.boolean(),
  autoPublish: z._default(z.boolean(), false),
  lookbackWindow: z._default(
    CreateScheduleLookbackWindowRequest$outboundSchema,
    "last_7_days",
  ),
});

export function createScheduleRequestToJSON(
  createScheduleRequest: CreateScheduleRequest,
): string {
  return JSON.stringify(
    CreateScheduleRequest$outboundSchema.parse(createScheduleRequest),
  );
}

/** @internal */
export const CreateScheduleSourceTypeResponse$inboundSchema: z.ZodMiniEnum<
  typeof CreateScheduleSourceTypeResponse
> = z.enum(CreateScheduleSourceTypeResponse);

/** @internal */
export const CreateScheduleFrequencyResponse$inboundSchema: z.ZodMiniType<
  CreateScheduleFrequencyResponse,
  unknown
> = openEnums.inboundSchema(CreateScheduleFrequencyResponse);

/** @internal */
export const CreateScheduleCronResponse$inboundSchema: z.ZodMiniType<
  CreateScheduleCronResponse,
  unknown
> = z.object({
  frequency: CreateScheduleFrequencyResponse$inboundSchema,
  hour: types.number(),
  minute: types.number(),
  dayOfWeek: types.optional(types.number()),
  dayOfMonth: types.optional(types.number()),
});

export function createScheduleCronResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateScheduleCronResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateScheduleCronResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateScheduleCronResponse' from JSON`,
  );
}

/** @internal */
export const CreateScheduleSourceConfigResponse$inboundSchema: z.ZodMiniType<
  CreateScheduleSourceConfigResponse,
  unknown
> = z.object({
  cron: z.lazy(() => CreateScheduleCronResponse$inboundSchema),
});

export function createScheduleSourceConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateScheduleSourceConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateScheduleSourceConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateScheduleSourceConfigResponse' from JSON`,
  );
}

/** @internal */
export const CreateScheduleTargetsResponse$inboundSchema: z.ZodMiniType<
  CreateScheduleTargetsResponse,
  unknown
> = z.object({
  repositoryIds: z.array(types.string()),
});

export function createScheduleTargetsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateScheduleTargetsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateScheduleTargetsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateScheduleTargetsResponse' from JSON`,
  );
}

/** @internal */
export const CreateScheduleOutputTypeResponse$inboundSchema: z.ZodMiniType<
  CreateScheduleOutputTypeResponse,
  unknown
> = openEnums.inboundSchema(CreateScheduleOutputTypeResponse);

/** @internal */
export const CreateSchedulePublishDestinationResponse$inboundSchema:
  z.ZodMiniType<CreateSchedulePublishDestinationResponse, unknown> = openEnums
    .inboundSchema(CreateSchedulePublishDestinationResponse);

/** @internal */
export const CreateScheduleOutputConfigResponse$inboundSchema: z.ZodMiniType<
  CreateScheduleOutputConfigResponse,
  unknown
> = z.object({
  publishDestination: types.optional(
    CreateSchedulePublishDestinationResponse$inboundSchema,
  ),
  brandVoiceId: types.optional(types.string()),
});

export function createScheduleOutputConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateScheduleOutputConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateScheduleOutputConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateScheduleOutputConfigResponse' from JSON`,
  );
}

/** @internal */
export const CreateScheduleLookbackWindowResponse$inboundSchema: z.ZodMiniType<
  CreateScheduleLookbackWindowResponse,
  unknown
> = openEnums.inboundSchema(CreateScheduleLookbackWindowResponse);

/** @internal */
export const CreateScheduleSchedule$inboundSchema: z.ZodMiniType<
  CreateScheduleSchedule,
  unknown
> = z.object({
  id: types.string(),
  organizationId: types.string(),
  name: types.string(),
  sourceType: CreateScheduleSourceTypeResponse$inboundSchema,
  sourceConfig: z.lazy(() => CreateScheduleSourceConfigResponse$inboundSchema),
  targets: z.lazy(() => CreateScheduleTargetsResponse$inboundSchema),
  outputType: CreateScheduleOutputTypeResponse$inboundSchema,
  outputConfig: z.optional(
    z.nullable(z.lazy(() => CreateScheduleOutputConfigResponse$inboundSchema)),
  ),
  enabled: types.boolean(),
  autoPublish: types.boolean(),
  createdAt: types.string(),
  updatedAt: types.string(),
  lookbackWindow: CreateScheduleLookbackWindowResponse$inboundSchema,
});

export function createScheduleScheduleFromJSON(
  jsonString: string,
): SafeParseResult<CreateScheduleSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateScheduleSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateScheduleSchedule' from JSON`,
  );
}

/** @internal */
export const CreateScheduleOrganization$inboundSchema: z.ZodMiniType<
  CreateScheduleOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function createScheduleOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<CreateScheduleOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateScheduleOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateScheduleOrganization' from JSON`,
  );
}

/** @internal */
export const CreateScheduleResponse$inboundSchema: z.ZodMiniType<
  CreateScheduleResponse,
  unknown
> = z.object({
  schedule: z.lazy(() => CreateScheduleSchedule$inboundSchema),
  organization: z.lazy(() => CreateScheduleOrganization$inboundSchema),
});

export function createScheduleResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateScheduleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateScheduleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateScheduleResponse' from JSON`,
  );
}
