/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f06805df0189
 */

import * as z from "zod/v4-mini";

export type DeleteGeoSequenceRequest = {
  projectId: string;
  sequenceId: string;
};

/** @internal */
export type DeleteGeoSequenceRequest$Outbound = {
  projectId: string;
  sequenceId: string;
};

/** @internal */
export const DeleteGeoSequenceRequest$outboundSchema: z.ZodMiniType<
  DeleteGeoSequenceRequest$Outbound,
  DeleteGeoSequenceRequest
> = z.object({
  projectId: z.string(),
  sequenceId: z.string(),
});

export function deleteGeoSequenceRequestToJSON(
  deleteGeoSequenceRequest: DeleteGeoSequenceRequest,
): string {
  return JSON.stringify(
    DeleteGeoSequenceRequest$outboundSchema.parse(deleteGeoSequenceRequest),
  );
}
