/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 18cd1dd91c86
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteWebhookEndpointRequest = {
  endpointId: string;
};

/**
 * Deleted endpoint ID
 */
export type DeleteWebhookEndpointResponse = {
  id: string;
};

/** @internal */
export type DeleteWebhookEndpointRequest$Outbound = {
  endpointId: string;
};

/** @internal */
export const DeleteWebhookEndpointRequest$outboundSchema: z.ZodMiniType<
  DeleteWebhookEndpointRequest$Outbound,
  DeleteWebhookEndpointRequest
> = z.object({
  endpointId: z.string(),
});

export function deleteWebhookEndpointRequestToJSON(
  deleteWebhookEndpointRequest: DeleteWebhookEndpointRequest,
): string {
  return JSON.stringify(
    DeleteWebhookEndpointRequest$outboundSchema.parse(
      deleteWebhookEndpointRequest,
    ),
  );
}

/** @internal */
export const DeleteWebhookEndpointResponse$inboundSchema: z.ZodMiniType<
  DeleteWebhookEndpointResponse,
  unknown
> = z.object({
  id: types.string(),
});

export function deleteWebhookEndpointResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWebhookEndpointResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteWebhookEndpointResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWebhookEndpointResponse' from JSON`,
  );
}
