/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 11091e3f50b4
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteEventTriggerRequest = {
  triggerId: string;
};

export type DeleteEventTriggerOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

/**
 * Event trigger deleted successfully
 */
export type DeleteEventTriggerResponse = {
  id: string;
  organization: DeleteEventTriggerOrganization;
};

/** @internal */
export type DeleteEventTriggerRequest$Outbound = {
  triggerId: string;
};

/** @internal */
export const DeleteEventTriggerRequest$outboundSchema: z.ZodMiniType<
  DeleteEventTriggerRequest$Outbound,
  DeleteEventTriggerRequest
> = z.object({
  triggerId: z.string(),
});

export function deleteEventTriggerRequestToJSON(
  deleteEventTriggerRequest: DeleteEventTriggerRequest,
): string {
  return JSON.stringify(
    DeleteEventTriggerRequest$outboundSchema.parse(deleteEventTriggerRequest),
  );
}

/** @internal */
export const DeleteEventTriggerOrganization$inboundSchema: z.ZodMiniType<
  DeleteEventTriggerOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function deleteEventTriggerOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<DeleteEventTriggerOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteEventTriggerOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteEventTriggerOrganization' from JSON`,
  );
}

/** @internal */
export const DeleteEventTriggerResponse$inboundSchema: z.ZodMiniType<
  DeleteEventTriggerResponse,
  unknown
> = z.object({
  id: types.string(),
  organization: z.lazy(() => DeleteEventTriggerOrganization$inboundSchema),
});

export function deleteEventTriggerResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteEventTriggerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteEventTriggerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteEventTriggerResponse' from JSON`,
  );
}
