/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e45cb5e77cda
 */

import * as z from "zod/v4-mini";

export type DeleteProjectRequest = {
  projectId: string;
};

/** @internal */
export type DeleteProjectRequest$Outbound = {
  projectId: string;
};

/** @internal */
export const DeleteProjectRequest$outboundSchema: z.ZodMiniType<
  DeleteProjectRequest$Outbound,
  DeleteProjectRequest
> = z.object({
  projectId: z.string(),
});

export function deleteProjectRequestToJSON(
  deleteProjectRequest: DeleteProjectRequest,
): string {
  return JSON.stringify(
    DeleteProjectRequest$outboundSchema.parse(deleteProjectRequest),
  );
}
