/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2d3c4c4d46f8
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeletePostRequest = {
  postId: string;
};

/**
 * Post deleted successfully
 */
export type DeletePostResponse = {
  id: string;
};

/** @internal */
export type DeletePostRequest$Outbound = {
  postId: string;
};

/** @internal */
export const DeletePostRequest$outboundSchema: z.ZodMiniType<
  DeletePostRequest$Outbound,
  DeletePostRequest
> = z.object({
  postId: z.string(),
});

export function deletePostRequestToJSON(
  deletePostRequest: DeletePostRequest,
): string {
  return JSON.stringify(
    DeletePostRequest$outboundSchema.parse(deletePostRequest),
  );
}

/** @internal */
export const DeletePostResponse$inboundSchema: z.ZodMiniType<
  DeletePostResponse,
  unknown
> = z.object({
  id: types.string(),
});

export function deletePostResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeletePostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletePostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletePostResponse' from JSON`,
  );
}
