/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5b681d37ee17
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteIntegrationRequest = {
  integrationId: string;
};

export type DeleteIntegrationOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type DeleteIntegrationDisabledSchedule = {
  id: string;
  name: string;
};

export type DeleteIntegrationDisabledEvent = {
  id: string;
  name: string;
};

/**
 * Integration deleted successfully
 */
export type DeleteIntegrationResponse = {
  id: string;
  organization: DeleteIntegrationOrganization;
  disabledSchedules: Array<DeleteIntegrationDisabledSchedule>;
  disabledEvents: Array<DeleteIntegrationDisabledEvent>;
};

/** @internal */
export type DeleteIntegrationRequest$Outbound = {
  integrationId: string;
};

/** @internal */
export const DeleteIntegrationRequest$outboundSchema: z.ZodMiniType<
  DeleteIntegrationRequest$Outbound,
  DeleteIntegrationRequest
> = z.object({
  integrationId: z.string(),
});

export function deleteIntegrationRequestToJSON(
  deleteIntegrationRequest: DeleteIntegrationRequest,
): string {
  return JSON.stringify(
    DeleteIntegrationRequest$outboundSchema.parse(deleteIntegrationRequest),
  );
}

/** @internal */
export const DeleteIntegrationOrganization$inboundSchema: z.ZodMiniType<
  DeleteIntegrationOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function deleteIntegrationOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<DeleteIntegrationOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteIntegrationOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteIntegrationOrganization' from JSON`,
  );
}

/** @internal */
export const DeleteIntegrationDisabledSchedule$inboundSchema: z.ZodMiniType<
  DeleteIntegrationDisabledSchedule,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function deleteIntegrationDisabledScheduleFromJSON(
  jsonString: string,
): SafeParseResult<DeleteIntegrationDisabledSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteIntegrationDisabledSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteIntegrationDisabledSchedule' from JSON`,
  );
}

/** @internal */
export const DeleteIntegrationDisabledEvent$inboundSchema: z.ZodMiniType<
  DeleteIntegrationDisabledEvent,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function deleteIntegrationDisabledEventFromJSON(
  jsonString: string,
): SafeParseResult<DeleteIntegrationDisabledEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteIntegrationDisabledEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteIntegrationDisabledEvent' from JSON`,
  );
}

/** @internal */
export const DeleteIntegrationResponse$inboundSchema: z.ZodMiniType<
  DeleteIntegrationResponse,
  unknown
> = z.object({
  id: types.string(),
  organization: z.lazy(() => DeleteIntegrationOrganization$inboundSchema),
  disabledSchedules: z.array(
    z.lazy(() => DeleteIntegrationDisabledSchedule$inboundSchema),
  ),
  disabledEvents: z.array(
    z.lazy(() => DeleteIntegrationDisabledEvent$inboundSchema),
  ),
});

export function deleteIntegrationResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteIntegrationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteIntegrationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteIntegrationResponse' from JSON`,
  );
}
