/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6f01b66689ea
 */

import * as z from "zod/v4-mini";

export type DeleteSkillRequest = {
  /**
   * Skill name. Lowercase letters, digits, and hyphens only.
   */
  name: string;
};

/** @internal */
export type DeleteSkillRequest$Outbound = {
  name: string;
};

/** @internal */
export const DeleteSkillRequest$outboundSchema: z.ZodMiniType<
  DeleteSkillRequest$Outbound,
  DeleteSkillRequest
> = z.object({
  name: z.string(),
});

export function deleteSkillRequestToJSON(
  deleteSkillRequest: DeleteSkillRequest,
): string {
  return JSON.stringify(
    DeleteSkillRequest$outboundSchema.parse(deleteSkillRequest),
  );
}
