/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 51a49c0e750b
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteBrandIdentityRequest = {
  brandIdentityId: string;
};

export type DeleteBrandIdentityOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type DisabledSchedule = {
  id: string;
  name: string;
};

export type DisabledEvent = {
  id: string;
  name: string;
};

/**
 * Brand identity deleted successfully
 */
export type DeleteBrandIdentityResponse = {
  id: string;
  organization: DeleteBrandIdentityOrganization;
  disabledSchedules: Array<DisabledSchedule>;
  disabledEvents: Array<DisabledEvent>;
};

/** @internal */
export type DeleteBrandIdentityRequest$Outbound = {
  brandIdentityId: string;
};

/** @internal */
export const DeleteBrandIdentityRequest$outboundSchema: z.ZodMiniType<
  DeleteBrandIdentityRequest$Outbound,
  DeleteBrandIdentityRequest
> = z.object({
  brandIdentityId: z.string(),
});

export function deleteBrandIdentityRequestToJSON(
  deleteBrandIdentityRequest: DeleteBrandIdentityRequest,
): string {
  return JSON.stringify(
    DeleteBrandIdentityRequest$outboundSchema.parse(deleteBrandIdentityRequest),
  );
}

/** @internal */
export const DeleteBrandIdentityOrganization$inboundSchema: z.ZodMiniType<
  DeleteBrandIdentityOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function deleteBrandIdentityOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<DeleteBrandIdentityOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteBrandIdentityOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteBrandIdentityOrganization' from JSON`,
  );
}

/** @internal */
export const DisabledSchedule$inboundSchema: z.ZodMiniType<
  DisabledSchedule,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function disabledScheduleFromJSON(
  jsonString: string,
): SafeParseResult<DisabledSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisabledSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisabledSchedule' from JSON`,
  );
}

/** @internal */
export const DisabledEvent$inboundSchema: z.ZodMiniType<
  DisabledEvent,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function disabledEventFromJSON(
  jsonString: string,
): SafeParseResult<DisabledEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisabledEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisabledEvent' from JSON`,
  );
}

/** @internal */
export const DeleteBrandIdentityResponse$inboundSchema: z.ZodMiniType<
  DeleteBrandIdentityResponse,
  unknown
> = z.object({
  id: types.string(),
  organization: z.lazy(() => DeleteBrandIdentityOrganization$inboundSchema),
  disabledSchedules: z.array(z.lazy(() => DisabledSchedule$inboundSchema)),
  disabledEvents: z.array(z.lazy(() => DisabledEvent$inboundSchema)),
});

export function deleteBrandIdentityResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteBrandIdentityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteBrandIdentityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteBrandIdentityResponse' from JSON`,
  );
}
