/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c67f7bc03e42
 */

import * as z from "zod/v4-mini";

export type GetGeoPromptHistoryRequest = {
  projectId: string;
  promptId: string;
  scanId?: string | undefined;
};

/** @internal */
export type GetGeoPromptHistoryRequest$Outbound = {
  projectId: string;
  promptId: string;
  scanId?: string | undefined;
};

/** @internal */
export const GetGeoPromptHistoryRequest$outboundSchema: z.ZodMiniType<
  GetGeoPromptHistoryRequest$Outbound,
  GetGeoPromptHistoryRequest
> = z.object({
  projectId: z.string(),
  promptId: z.string(),
  scanId: z.optional(z.string()),
});

export function getGeoPromptHistoryRequestToJSON(
  getGeoPromptHistoryRequest: GetGeoPromptHistoryRequest,
): string {
  return JSON.stringify(
    GetGeoPromptHistoryRequest$outboundSchema.parse(getGeoPromptHistoryRequest),
  );
}
