/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ebdbe2f6d005
 */

import * as z from "zod/v4-mini";

export type GetFeedbackRequest = {
  feedbackId: string;
};

/** @internal */
export type GetFeedbackRequest$Outbound = {
  feedbackId: string;
};

/** @internal */
export const GetFeedbackRequest$outboundSchema: z.ZodMiniType<
  GetFeedbackRequest$Outbound,
  GetFeedbackRequest
> = z.object({
  feedbackId: z.string(),
});

export function getFeedbackRequestToJSON(
  getFeedbackRequest: GetFeedbackRequest,
): string {
  return JSON.stringify(
    GetFeedbackRequest$outboundSchema.parse(getFeedbackRequest),
  );
}
