/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f1aa086e191f
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetPostGenerationRequest = {
  jobId: string;
};

export const GetPostGenerationStatus = {
  Queued: "queued",
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
export type GetPostGenerationStatus = OpenEnum<typeof GetPostGenerationStatus>;

export const GetPostGenerationContentType = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
} as const;
export type GetPostGenerationContentType = OpenEnum<
  typeof GetPostGenerationContentType
>;

export const GetPostGenerationLookbackWindow = {
  CurrentDay: "current_day",
  Yesterday: "yesterday",
  Last7Days: "last_7_days",
  Last14Days: "last_14_days",
  Last30Days: "last_30_days",
} as const;
export type GetPostGenerationLookbackWindow = OpenEnum<
  typeof GetPostGenerationLookbackWindow
>;

export const GetPostGenerationSource = {
  Api: "api",
  Dashboard: "dashboard",
} as const;
export type GetPostGenerationSource = OpenEnum<typeof GetPostGenerationSource>;

export type GetPostGenerationJob = {
  id: string;
  organizationId: string;
  status: GetPostGenerationStatus;
  contentType: GetPostGenerationContentType;
  lookbackWindow: GetPostGenerationLookbackWindow;
  repositoryIds: Array<string>;
  brandVoiceId: string | null;
  workflowRunId: string | null;
  postId: string | null;
  error: string | null;
  source: GetPostGenerationSource;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};

export const Type = {
  Queued: "queued",
  WorkflowTriggered: "workflow_triggered",
  Running: "running",
  FetchingRepositories: "fetching_repositories",
  GeneratingContent: "generating_content",
  PostCreated: "post_created",
  Completed: "completed",
  Failed: "failed",
} as const;
export type Type = OpenEnum<typeof Type>;

export type Event = {
  id: string;
  jobId: string;
  type: Type;
  message: string;
  createdAt: string;
  metadata: { [k: string]: any } | null;
};

/**
 * Post generation status fetched successfully
 */
export type GetPostGenerationResponse = {
  job: GetPostGenerationJob;
  events: Array<Event>;
};

/** @internal */
export type GetPostGenerationRequest$Outbound = {
  jobId: string;
};

/** @internal */
export const GetPostGenerationRequest$outboundSchema: z.ZodMiniType<
  GetPostGenerationRequest$Outbound,
  GetPostGenerationRequest
> = z.object({
  jobId: z.string(),
});

export function getPostGenerationRequestToJSON(
  getPostGenerationRequest: GetPostGenerationRequest,
): string {
  return JSON.stringify(
    GetPostGenerationRequest$outboundSchema.parse(getPostGenerationRequest),
  );
}

/** @internal */
export const GetPostGenerationStatus$inboundSchema: z.ZodMiniType<
  GetPostGenerationStatus,
  unknown
> = openEnums.inboundSchema(GetPostGenerationStatus);

/** @internal */
export const GetPostGenerationContentType$inboundSchema: z.ZodMiniType<
  GetPostGenerationContentType,
  unknown
> = openEnums.inboundSchema(GetPostGenerationContentType);

/** @internal */
export const GetPostGenerationLookbackWindow$inboundSchema: z.ZodMiniType<
  GetPostGenerationLookbackWindow,
  unknown
> = openEnums.inboundSchema(GetPostGenerationLookbackWindow);

/** @internal */
export const GetPostGenerationSource$inboundSchema: z.ZodMiniType<
  GetPostGenerationSource,
  unknown
> = openEnums.inboundSchema(GetPostGenerationSource);

/** @internal */
export const GetPostGenerationJob$inboundSchema: z.ZodMiniType<
  GetPostGenerationJob,
  unknown
> = z.object({
  id: types.string(),
  organizationId: types.string(),
  status: GetPostGenerationStatus$inboundSchema,
  contentType: GetPostGenerationContentType$inboundSchema,
  lookbackWindow: GetPostGenerationLookbackWindow$inboundSchema,
  repositoryIds: z.array(types.string()),
  brandVoiceId: types.nullable(types.string()),
  workflowRunId: types.nullable(types.string()),
  postId: types.nullable(types.string()),
  error: types.nullable(types.string()),
  source: GetPostGenerationSource$inboundSchema,
  createdAt: types.string(),
  updatedAt: types.string(),
  completedAt: types.nullable(types.string()),
});

export function getPostGenerationJobFromJSON(
  jsonString: string,
): SafeParseResult<GetPostGenerationJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPostGenerationJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPostGenerationJob' from JSON`,
  );
}

/** @internal */
export const Type$inboundSchema: z.ZodMiniType<Type, unknown> = openEnums
  .inboundSchema(Type);

/** @internal */
export const Event$inboundSchema: z.ZodMiniType<Event, unknown> = z.object({
  id: types.string(),
  jobId: types.string(),
  type: Type$inboundSchema,
  message: types.string(),
  createdAt: types.string(),
  metadata: types.nullable(z.record(z.string(), z.any())),
});

export function eventFromJSON(
  jsonString: string,
): SafeParseResult<Event, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Event$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Event' from JSON`,
  );
}

/** @internal */
export const GetPostGenerationResponse$inboundSchema: z.ZodMiniType<
  GetPostGenerationResponse,
  unknown
> = z.object({
  job: z.lazy(() => GetPostGenerationJob$inboundSchema),
  events: z.array(z.lazy(() => Event$inboundSchema)),
});

export function getPostGenerationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPostGenerationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPostGenerationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPostGenerationResponse' from JSON`,
  );
}
