/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 570daa51fc02
 */

import * as z from "zod/v4-mini";

export type GetGeoTrafficOverviewRequest = {
  projectId: string;
  /**
   * Rolling window size in days. Ignored when from/to are set.
   */
  days?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export type GetGeoTrafficOverviewRequest$Outbound = {
  projectId: string;
  days?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export const GetGeoTrafficOverviewRequest$outboundSchema: z.ZodMiniType<
  GetGeoTrafficOverviewRequest$Outbound,
  GetGeoTrafficOverviewRequest
> = z.object({
  projectId: z.string(),
  days: z.optional(z.int()),
  from: z.optional(z.string()),
  to: z.optional(z.string()),
});

export function getGeoTrafficOverviewRequestToJSON(
  getGeoTrafficOverviewRequest: GetGeoTrafficOverviewRequest,
): string {
  return JSON.stringify(
    GetGeoTrafficOverviewRequest$outboundSchema.parse(
      getGeoTrafficOverviewRequest,
    ),
  );
}
