/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a7f2432c7bbc
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetWebhookDeliveryRequest = {
  deliveryId: string;
};

export const GetWebhookDeliveryEventType = {
  PostGenerationCompleted: "post.generation.completed",
  PostGenerationFailed: "post.generation.failed",
  PostGenerationSkipped: "post.generation.skipped",
  BrandIdentityGenerationCompleted: "brand_identity.generation.completed",
  BrandIdentityGenerationFailed: "brand_identity.generation.failed",
  PostPublished: "post.published",
  PostCreated: "post.created",
  PostUpdated: "post.updated",
  PostDeleted: "post.deleted",
  PostUnpublished: "post.unpublished",
  GeoScanCompleted: "geo.scan.completed",
  GeoScanFailed: "geo.scan.failed",
} as const;
export type GetWebhookDeliveryEventType = OpenEnum<
  typeof GetWebhookDeliveryEventType
>;

export const GetWebhookDeliveryStatus = {
  Pending: "pending",
  Sending: "sending",
  Retrying: "retrying",
  Succeeded: "succeeded",
  Failed: "failed",
  Cancelled: "cancelled",
} as const;
export type GetWebhookDeliveryStatus = OpenEnum<
  typeof GetWebhookDeliveryStatus
>;

export type GetWebhookDeliveryDelivery = {
  id: string;
  eventId: string;
  endpointId: string;
  url: string;
  eventType: GetWebhookDeliveryEventType;
  status: GetWebhookDeliveryStatus;
  attemptCount: number;
  nextAttemptAt: string;
  createdAt: string;
  statusCode: number | null;
  error: string | null;
  payload: string;
};

export type Attempt = {
  id: string;
  deliveryId: string;
  attemptNumber: number;
  startedAt: string;
  finishedAt: string | null;
  statusCode: number | null;
  error: string | null;
  durationMs: number | null;
};

/**
 * Delivery detail
 */
export type GetWebhookDeliveryResponse = {
  delivery: GetWebhookDeliveryDelivery;
  attempts: Array<Attempt>;
};

/** @internal */
export type GetWebhookDeliveryRequest$Outbound = {
  deliveryId: string;
};

/** @internal */
export const GetWebhookDeliveryRequest$outboundSchema: z.ZodMiniType<
  GetWebhookDeliveryRequest$Outbound,
  GetWebhookDeliveryRequest
> = z.object({
  deliveryId: z.string(),
});

export function getWebhookDeliveryRequestToJSON(
  getWebhookDeliveryRequest: GetWebhookDeliveryRequest,
): string {
  return JSON.stringify(
    GetWebhookDeliveryRequest$outboundSchema.parse(getWebhookDeliveryRequest),
  );
}

/** @internal */
export const GetWebhookDeliveryEventType$inboundSchema: z.ZodMiniType<
  GetWebhookDeliveryEventType,
  unknown
> = openEnums.inboundSchema(GetWebhookDeliveryEventType);

/** @internal */
export const GetWebhookDeliveryStatus$inboundSchema: z.ZodMiniType<
  GetWebhookDeliveryStatus,
  unknown
> = openEnums.inboundSchema(GetWebhookDeliveryStatus);

/** @internal */
export const GetWebhookDeliveryDelivery$inboundSchema: z.ZodMiniType<
  GetWebhookDeliveryDelivery,
  unknown
> = z.object({
  id: types.string(),
  eventId: types.string(),
  endpointId: types.string(),
  url: types.string(),
  eventType: GetWebhookDeliveryEventType$inboundSchema,
  status: GetWebhookDeliveryStatus$inboundSchema,
  attemptCount: types.number(),
  nextAttemptAt: types.string(),
  createdAt: types.string(),
  statusCode: types.nullable(types.number()),
  error: types.nullable(types.string()),
  payload: types.string(),
});

export function getWebhookDeliveryDeliveryFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookDeliveryDelivery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookDeliveryDelivery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookDeliveryDelivery' from JSON`,
  );
}

/** @internal */
export const Attempt$inboundSchema: z.ZodMiniType<Attempt, unknown> = z.object({
  id: types.string(),
  deliveryId: types.string(),
  attemptNumber: types.number(),
  startedAt: types.string(),
  finishedAt: types.nullable(types.string()),
  statusCode: types.nullable(types.number()),
  error: types.nullable(types.string()),
  durationMs: types.nullable(types.number()),
});

export function attemptFromJSON(
  jsonString: string,
): SafeParseResult<Attempt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Attempt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Attempt' from JSON`,
  );
}

/** @internal */
export const GetWebhookDeliveryResponse$inboundSchema: z.ZodMiniType<
  GetWebhookDeliveryResponse,
  unknown
> = z.object({
  delivery: z.lazy(() => GetWebhookDeliveryDelivery$inboundSchema),
  attempts: z.array(z.lazy(() => Attempt$inboundSchema)),
});

export function getWebhookDeliveryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookDeliveryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookDeliveryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookDeliveryResponse' from JSON`,
  );
}
