/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 24d708b2aa0e
 */

import * as z from "zod/v4-mini";

export type GetGeoVisibilityTimeseriesRequest = {
  projectId: string;
  /**
   * Rolling window size in days. Ignored when from/to are set.
   */
  days?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export type GetGeoVisibilityTimeseriesRequest$Outbound = {
  projectId: string;
  days?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export const GetGeoVisibilityTimeseriesRequest$outboundSchema: z.ZodMiniType<
  GetGeoVisibilityTimeseriesRequest$Outbound,
  GetGeoVisibilityTimeseriesRequest
> = z.object({
  projectId: z.string(),
  days: z.optional(z.int()),
  from: z.optional(z.string()),
  to: z.optional(z.string()),
});

export function getGeoVisibilityTimeseriesRequestToJSON(
  getGeoVisibilityTimeseriesRequest: GetGeoVisibilityTimeseriesRequest,
): string {
  return JSON.stringify(
    GetGeoVisibilityTimeseriesRequest$outboundSchema.parse(
      getGeoVisibilityTimeseriesRequest,
    ),
  );
}
