/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 93f74a5f9fc3
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetBrandIdentityGenerationRequest = {
  jobId: string;
};

export type GetBrandIdentityGenerationOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export const GetBrandIdentityGenerationStatus = {
  Queued: "queued",
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
export type GetBrandIdentityGenerationStatus = OpenEnum<
  typeof GetBrandIdentityGenerationStatus
>;

export const GetBrandIdentityGenerationStep = {
  Scraping: "scraping",
  Extracting: "extracting",
  Saving: "saving",
} as const;
export type GetBrandIdentityGenerationStep = OpenEnum<
  typeof GetBrandIdentityGenerationStep
>;

export type GetBrandIdentityGenerationJob = {
  id: string;
  organizationId: string;
  brandIdentityId: string;
  status: GetBrandIdentityGenerationStatus;
  step: GetBrandIdentityGenerationStep | null;
  currentStep: number;
  totalSteps: number;
  workflowRunId: string | null;
  error: string | null;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};

/**
 * Brand identity generation status fetched successfully
 */
export type GetBrandIdentityGenerationResponse = {
  organization: GetBrandIdentityGenerationOrganization;
  job: GetBrandIdentityGenerationJob;
};

/** @internal */
export type GetBrandIdentityGenerationRequest$Outbound = {
  jobId: string;
};

/** @internal */
export const GetBrandIdentityGenerationRequest$outboundSchema: z.ZodMiniType<
  GetBrandIdentityGenerationRequest$Outbound,
  GetBrandIdentityGenerationRequest
> = z.object({
  jobId: z.string(),
});

export function getBrandIdentityGenerationRequestToJSON(
  getBrandIdentityGenerationRequest: GetBrandIdentityGenerationRequest,
): string {
  return JSON.stringify(
    GetBrandIdentityGenerationRequest$outboundSchema.parse(
      getBrandIdentityGenerationRequest,
    ),
  );
}

/** @internal */
export const GetBrandIdentityGenerationOrganization$inboundSchema:
  z.ZodMiniType<GetBrandIdentityGenerationOrganization, unknown> = z.object({
    id: types.string(),
    slug: types.string(),
    name: types.string(),
    logo: types.nullable(types.string()),
  });

export function getBrandIdentityGenerationOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GetBrandIdentityGenerationOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetBrandIdentityGenerationOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBrandIdentityGenerationOrganization' from JSON`,
  );
}

/** @internal */
export const GetBrandIdentityGenerationStatus$inboundSchema: z.ZodMiniType<
  GetBrandIdentityGenerationStatus,
  unknown
> = openEnums.inboundSchema(GetBrandIdentityGenerationStatus);

/** @internal */
export const GetBrandIdentityGenerationStep$inboundSchema: z.ZodMiniType<
  GetBrandIdentityGenerationStep,
  unknown
> = openEnums.inboundSchema(GetBrandIdentityGenerationStep);

/** @internal */
export const GetBrandIdentityGenerationJob$inboundSchema: z.ZodMiniType<
  GetBrandIdentityGenerationJob,
  unknown
> = z.object({
  id: types.string(),
  organizationId: types.string(),
  brandIdentityId: types.string(),
  status: GetBrandIdentityGenerationStatus$inboundSchema,
  step: types.nullable(GetBrandIdentityGenerationStep$inboundSchema),
  currentStep: types.number(),
  totalSteps: types.number(),
  workflowRunId: types.nullable(types.string()),
  error: types.nullable(types.string()),
  createdAt: types.string(),
  updatedAt: types.string(),
  completedAt: types.nullable(types.string()),
});

export function getBrandIdentityGenerationJobFromJSON(
  jsonString: string,
): SafeParseResult<GetBrandIdentityGenerationJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBrandIdentityGenerationJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBrandIdentityGenerationJob' from JSON`,
  );
}

/** @internal */
export const GetBrandIdentityGenerationResponse$inboundSchema: z.ZodMiniType<
  GetBrandIdentityGenerationResponse,
  unknown
> = z.object({
  organization: z.lazy(() =>
    GetBrandIdentityGenerationOrganization$inboundSchema
  ),
  job: z.lazy(() => GetBrandIdentityGenerationJob$inboundSchema),
});

export function getBrandIdentityGenerationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBrandIdentityGenerationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetBrandIdentityGenerationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBrandIdentityGenerationResponse' from JSON`,
  );
}
