/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e9168f4e2a0d
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetPostRequest = {
  postId: string;
};

export const GetPostStatus = {
  Draft: "draft",
  Published: "published",
} as const;
export type GetPostStatus = OpenEnum<typeof GetPostStatus>;

export type GetPostPost = {
  id: string;
  title: string;
  content: string;
  markdown: string;
  recommendations: string | null;
  contentType: string;
  sourceMetadata?: any | undefined;
  status: GetPostStatus;
  createdAt: string;
  updatedAt: string;
};

/**
 * Post fetched successfully
 */
export type GetPostResponse = {
  post: GetPostPost | null;
};

/** @internal */
export type GetPostRequest$Outbound = {
  postId: string;
};

/** @internal */
export const GetPostRequest$outboundSchema: z.ZodMiniType<
  GetPostRequest$Outbound,
  GetPostRequest
> = z.object({
  postId: z.string(),
});

export function getPostRequestToJSON(getPostRequest: GetPostRequest): string {
  return JSON.stringify(GetPostRequest$outboundSchema.parse(getPostRequest));
}

/** @internal */
export const GetPostStatus$inboundSchema: z.ZodMiniType<
  GetPostStatus,
  unknown
> = openEnums.inboundSchema(GetPostStatus);

/** @internal */
export const GetPostPost$inboundSchema: z.ZodMiniType<GetPostPost, unknown> = z
  .object({
    id: types.string(),
    title: types.string(),
    content: types.string(),
    markdown: types.string(),
    recommendations: types.nullable(types.string()),
    contentType: types.string(),
    sourceMetadata: types.optional(z.any()),
    status: GetPostStatus$inboundSchema,
    createdAt: types.string(),
    updatedAt: types.string(),
  });

export function getPostPostFromJSON(
  jsonString: string,
): SafeParseResult<GetPostPost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPostPost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPostPost' from JSON`,
  );
}

/** @internal */
export const GetPostResponse$inboundSchema: z.ZodMiniType<
  GetPostResponse,
  unknown
> = z.object({
  post: types.nullable(z.lazy(() => GetPostPost$inboundSchema)),
});

export function getPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPostResponse' from JSON`,
  );
}
