/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1755262cc552
 */

import * as z from "zod/v4-mini";

export type GetPostScheduleRequest = {
  postId: string;
};

/** @internal */
export type GetPostScheduleRequest$Outbound = {
  postId: string;
};

/** @internal */
export const GetPostScheduleRequest$outboundSchema: z.ZodMiniType<
  GetPostScheduleRequest$Outbound,
  GetPostScheduleRequest
> = z.object({
  postId: z.string(),
});

export function getPostScheduleRequestToJSON(
  getPostScheduleRequest: GetPostScheduleRequest,
): string {
  return JSON.stringify(
    GetPostScheduleRequest$outboundSchema.parse(getPostScheduleRequest),
  );
}
