/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 002bf2ad680e
 */

import * as z from "zod/v4-mini";

export type GetGeoVisibilityCompetitorDetailRequest = {
  projectId: string;
  /**
   * Competitor brand name as reported by competitor-share.
   */
  brand: string;
  /**
   * Rolling window size in days. Ignored when from/to are set.
   */
  days?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export type GetGeoVisibilityCompetitorDetailRequest$Outbound = {
  projectId: string;
  brand: string;
  days?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export const GetGeoVisibilityCompetitorDetailRequest$outboundSchema:
  z.ZodMiniType<
    GetGeoVisibilityCompetitorDetailRequest$Outbound,
    GetGeoVisibilityCompetitorDetailRequest
  > = z.object({
    projectId: z.string(),
    brand: z.string(),
    days: z.optional(z.int()),
    from: z.optional(z.string()),
    to: z.optional(z.string()),
  });

export function getGeoVisibilityCompetitorDetailRequestToJSON(
  getGeoVisibilityCompetitorDetailRequest:
    GetGeoVisibilityCompetitorDetailRequest,
): string {
  return JSON.stringify(
    GetGeoVisibilityCompetitorDetailRequest$outboundSchema.parse(
      getGeoVisibilityCompetitorDetailRequest,
    ),
  );
}
