/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const GetPostStatusQueryParamEnum2 = {
  Draft: "draft",
  Published: "published",
} as const;
export type GetPostStatusQueryParamEnum2 = ClosedEnum<
  typeof GetPostStatusQueryParamEnum2
>;

export const GetPostStatusQueryParamEnum1 = {
  Draft: "draft",
  Published: "published",
} as const;
export type GetPostStatusQueryParamEnum1 = ClosedEnum<
  typeof GetPostStatusQueryParamEnum1
>;

/**
 * Filter by status. Repeat the query param to pass multiple values.
 */
export type GetPostStatusUnion =
  | GetPostStatusQueryParamEnum1
  | Array<GetPostStatusQueryParamEnum2>;

export type GetPostRequest = {
  organizationId: string;
  postId: string;
  /**
   * Filter by status. Repeat the query param to pass multiple values.
   */
  status?:
    | GetPostStatusQueryParamEnum1
    | Array<GetPostStatusQueryParamEnum2>
    | undefined;
};

export const GetPostPostStatus = {
  Draft: "draft",
  Published: "published",
} as const;
export type GetPostPostStatus = OpenEnum<typeof GetPostPostStatus>;

export type GetPostPost = {
  id: string;
  title: string;
  content: string;
  markdown: string;
  contentType: string;
  sourceMetadata?: any | undefined;
  status: GetPostPostStatus;
  createdAt: string;
  updatedAt: string;
};

export const GetPostMetadataStatus = {
  Draft: "draft",
  Published: "published",
} as const;
export type GetPostMetadataStatus = OpenEnum<typeof GetPostMetadataStatus>;

export type GetPostMetadata = {
  status: Array<GetPostMetadataStatus>;
};

/**
 * Post fetched successfully
 */
export type GetPostResponse = {
  post: GetPostPost | null;
  metadata: GetPostMetadata;
};

/** @internal */
export const GetPostStatusQueryParamEnum2$outboundSchema: z.ZodMiniEnum<
  typeof GetPostStatusQueryParamEnum2
> = z.enum(GetPostStatusQueryParamEnum2);

/** @internal */
export const GetPostStatusQueryParamEnum1$outboundSchema: z.ZodMiniEnum<
  typeof GetPostStatusQueryParamEnum1
> = z.enum(GetPostStatusQueryParamEnum1);

/** @internal */
export type GetPostStatusUnion$Outbound = string | Array<string>;

/** @internal */
export const GetPostStatusUnion$outboundSchema: z.ZodMiniType<
  GetPostStatusUnion$Outbound,
  GetPostStatusUnion
> = smartUnion([
  GetPostStatusQueryParamEnum1$outboundSchema,
  z.array(GetPostStatusQueryParamEnum2$outboundSchema),
]);

export function getPostStatusUnionToJSON(
  getPostStatusUnion: GetPostStatusUnion,
): string {
  return JSON.stringify(
    GetPostStatusUnion$outboundSchema.parse(getPostStatusUnion),
  );
}

/** @internal */
export type GetPostRequest$Outbound = {
  organizationId: string;
  postId: string;
  status?: string | Array<string> | undefined;
};

/** @internal */
export const GetPostRequest$outboundSchema: z.ZodMiniType<
  GetPostRequest$Outbound,
  GetPostRequest
> = z.object({
  organizationId: z.string(),
  postId: z.string(),
  status: z.optional(
    smartUnion([
      GetPostStatusQueryParamEnum1$outboundSchema,
      z.array(GetPostStatusQueryParamEnum2$outboundSchema),
    ]),
  ),
});

export function getPostRequestToJSON(getPostRequest: GetPostRequest): string {
  return JSON.stringify(GetPostRequest$outboundSchema.parse(getPostRequest));
}

/** @internal */
export const GetPostPostStatus$inboundSchema: z.ZodMiniType<
  GetPostPostStatus,
  unknown
> = openEnums.inboundSchema(GetPostPostStatus);

/** @internal */
export const GetPostPost$inboundSchema: z.ZodMiniType<GetPostPost, unknown> = z
  .object({
    id: types.string(),
    title: types.string(),
    content: types.string(),
    markdown: types.string(),
    contentType: types.string(),
    sourceMetadata: types.optional(z.any()),
    status: GetPostPostStatus$inboundSchema,
    createdAt: types.string(),
    updatedAt: types.string(),
  });

export function getPostPostFromJSON(
  jsonString: string,
): SafeParseResult<GetPostPost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPostPost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPostPost' from JSON`,
  );
}

/** @internal */
export const GetPostMetadataStatus$inboundSchema: z.ZodMiniType<
  GetPostMetadataStatus,
  unknown
> = openEnums.inboundSchema(GetPostMetadataStatus);

/** @internal */
export const GetPostMetadata$inboundSchema: z.ZodMiniType<
  GetPostMetadata,
  unknown
> = z.object({
  status: z.array(GetPostMetadataStatus$inboundSchema),
});

export function getPostMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GetPostMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPostMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPostMetadata' from JSON`,
  );
}

/** @internal */
export const GetPostResponse$inboundSchema: z.ZodMiniType<
  GetPostResponse,
  unknown
> = z.object({
  post: types.nullable(z.lazy(() => GetPostPost$inboundSchema)),
  metadata: z.lazy(() => GetPostMetadata$inboundSchema),
});

export function getPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPostResponse' from JSON`,
  );
}
