/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c339740cc9ba
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetEventTriggerRequest = {
  triggerId: string;
};

export const GetEventTriggerSourceType = {
  GithubWebhook: "github_webhook",
} as const;
export type GetEventTriggerSourceType = ClosedEnum<
  typeof GetEventTriggerSourceType
>;

export const GetEventTriggerEventType = {
  Release: "release",
  Push: "push",
} as const;
export type GetEventTriggerEventType = OpenEnum<
  typeof GetEventTriggerEventType
>;

export type GetEventTriggerSourceConfig = {
  eventTypes: Array<GetEventTriggerEventType>;
  includePreReleases: boolean;
};

export type GetEventTriggerTargets = {
  repositoryIds: Array<string>;
};

export const GetEventTriggerOutputType = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
  Image: "image",
} as const;
export type GetEventTriggerOutputType = OpenEnum<
  typeof GetEventTriggerOutputType
>;

export const GetEventTriggerPublishDestination = {
  Webflow: "webflow",
  Framer: "framer",
  Custom: "custom",
} as const;
export type GetEventTriggerPublishDestination = OpenEnum<
  typeof GetEventTriggerPublishDestination
>;

export type GetEventTriggerOutputConfig = {
  publishDestination?: GetEventTriggerPublishDestination | undefined;
  brandVoiceId?: string | undefined;
};

export type GetEventTriggerEventTrigger = {
  id: string;
  organizationId: string;
  name: string;
  sourceType: GetEventTriggerSourceType;
  sourceConfig: GetEventTriggerSourceConfig;
  targets: GetEventTriggerTargets;
  outputType: GetEventTriggerOutputType;
  outputConfig?: GetEventTriggerOutputConfig | null | undefined;
  enabled: boolean;
  autoPublish: boolean;
  createdAt: string;
  updatedAt: string;
};

export type GetEventTriggerOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

/**
 * Event trigger fetched successfully
 */
export type GetEventTriggerResponse = {
  eventTrigger: GetEventTriggerEventTrigger;
  organization: GetEventTriggerOrganization;
};

/** @internal */
export type GetEventTriggerRequest$Outbound = {
  triggerId: string;
};

/** @internal */
export const GetEventTriggerRequest$outboundSchema: z.ZodMiniType<
  GetEventTriggerRequest$Outbound,
  GetEventTriggerRequest
> = z.object({
  triggerId: z.string(),
});

export function getEventTriggerRequestToJSON(
  getEventTriggerRequest: GetEventTriggerRequest,
): string {
  return JSON.stringify(
    GetEventTriggerRequest$outboundSchema.parse(getEventTriggerRequest),
  );
}

/** @internal */
export const GetEventTriggerSourceType$inboundSchema: z.ZodMiniEnum<
  typeof GetEventTriggerSourceType
> = z.enum(GetEventTriggerSourceType);

/** @internal */
export const GetEventTriggerEventType$inboundSchema: z.ZodMiniType<
  GetEventTriggerEventType,
  unknown
> = openEnums.inboundSchema(GetEventTriggerEventType);

/** @internal */
export const GetEventTriggerSourceConfig$inboundSchema: z.ZodMiniType<
  GetEventTriggerSourceConfig,
  unknown
> = z.object({
  eventTypes: z.array(GetEventTriggerEventType$inboundSchema),
  includePreReleases: z._default(types.boolean(), true),
});

export function getEventTriggerSourceConfigFromJSON(
  jsonString: string,
): SafeParseResult<GetEventTriggerSourceConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEventTriggerSourceConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEventTriggerSourceConfig' from JSON`,
  );
}

/** @internal */
export const GetEventTriggerTargets$inboundSchema: z.ZodMiniType<
  GetEventTriggerTargets,
  unknown
> = z.object({
  repositoryIds: z.array(types.string()),
});

export function getEventTriggerTargetsFromJSON(
  jsonString: string,
): SafeParseResult<GetEventTriggerTargets, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEventTriggerTargets$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEventTriggerTargets' from JSON`,
  );
}

/** @internal */
export const GetEventTriggerOutputType$inboundSchema: z.ZodMiniType<
  GetEventTriggerOutputType,
  unknown
> = openEnums.inboundSchema(GetEventTriggerOutputType);

/** @internal */
export const GetEventTriggerPublishDestination$inboundSchema: z.ZodMiniType<
  GetEventTriggerPublishDestination,
  unknown
> = openEnums.inboundSchema(GetEventTriggerPublishDestination);

/** @internal */
export const GetEventTriggerOutputConfig$inboundSchema: z.ZodMiniType<
  GetEventTriggerOutputConfig,
  unknown
> = z.object({
  publishDestination: types.optional(
    GetEventTriggerPublishDestination$inboundSchema,
  ),
  brandVoiceId: types.optional(types.string()),
});

export function getEventTriggerOutputConfigFromJSON(
  jsonString: string,
): SafeParseResult<GetEventTriggerOutputConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEventTriggerOutputConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEventTriggerOutputConfig' from JSON`,
  );
}

/** @internal */
export const GetEventTriggerEventTrigger$inboundSchema: z.ZodMiniType<
  GetEventTriggerEventTrigger,
  unknown
> = z.object({
  id: types.string(),
  organizationId: types.string(),
  name: types.string(),
  sourceType: GetEventTriggerSourceType$inboundSchema,
  sourceConfig: z.lazy(() => GetEventTriggerSourceConfig$inboundSchema),
  targets: z.lazy(() => GetEventTriggerTargets$inboundSchema),
  outputType: GetEventTriggerOutputType$inboundSchema,
  outputConfig: z.optional(
    z.nullable(z.lazy(() => GetEventTriggerOutputConfig$inboundSchema)),
  ),
  enabled: types.boolean(),
  autoPublish: types.boolean(),
  createdAt: types.string(),
  updatedAt: types.string(),
});

export function getEventTriggerEventTriggerFromJSON(
  jsonString: string,
): SafeParseResult<GetEventTriggerEventTrigger, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEventTriggerEventTrigger$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEventTriggerEventTrigger' from JSON`,
  );
}

/** @internal */
export const GetEventTriggerOrganization$inboundSchema: z.ZodMiniType<
  GetEventTriggerOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function getEventTriggerOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GetEventTriggerOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEventTriggerOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEventTriggerOrganization' from JSON`,
  );
}

/** @internal */
export const GetEventTriggerResponse$inboundSchema: z.ZodMiniType<
  GetEventTriggerResponse,
  unknown
> = z.object({
  eventTrigger: z.lazy(() => GetEventTriggerEventTrigger$inboundSchema),
  organization: z.lazy(() => GetEventTriggerOrganization$inboundSchema),
});

export function getEventTriggerResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetEventTriggerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEventTriggerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEventTriggerResponse' from JSON`,
  );
}
