/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e9168f4e2a0d
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const GetPostStatusQueryParamEnum2 = {
  Draft: "draft",
  Published: "published",
} as const;
export type GetPostStatusQueryParamEnum2 = ClosedEnum<
  typeof GetPostStatusQueryParamEnum2
>;

export const GetPostStatusQueryParamEnum1 = {
  Draft: "draft",
  Published: "published",
} as const;
export type GetPostStatusQueryParamEnum1 = ClosedEnum<
  typeof GetPostStatusQueryParamEnum1
>;

/**
 * Filter by status. Repeat the query param to pass multiple values.
 */
export type GetPostStatusUnion =
  | GetPostStatusQueryParamEnum1
  | Array<GetPostStatusQueryParamEnum2>;

export const GetPostContentTypeEnum2 = {
  Changelog: "changelog",
  LinkedinPost: "linkedin_post",
} as const;
export type GetPostContentTypeEnum2 = ClosedEnum<
  typeof GetPostContentTypeEnum2
>;

export const GetPostContentTypeEnum1 = {
  Changelog: "changelog",
  LinkedinPost: "linkedin_post",
} as const;
export type GetPostContentTypeEnum1 = ClosedEnum<
  typeof GetPostContentTypeEnum1
>;

/**
 * Filter by content type. Repeat the query param to pass multiple values.
 */
export type GetPostContentTypeUnion =
  | GetPostContentTypeEnum1
  | Array<GetPostContentTypeEnum2>;

export type GetPostRequest = {
  organizationId: string;
  postId: string;
  /**
   * Filter by status. Repeat the query param to pass multiple values.
   */
  status?:
    | GetPostStatusQueryParamEnum1
    | Array<GetPostStatusQueryParamEnum2>
    | undefined;
  /**
   * Filter by content type. Repeat the query param to pass multiple values.
   */
  contentType?:
    | GetPostContentTypeEnum1
    | Array<GetPostContentTypeEnum2>
    | undefined;
};

export const GetPostStatusResponse = {
  Draft: "draft",
  Published: "published",
} as const;
export type GetPostStatusResponse = OpenEnum<typeof GetPostStatusResponse>;

export type GetPostPost = {
  id: string;
  title: string;
  content: string;
  markdown: string;
  contentType: string;
  sourceMetadata?: any | undefined;
  status: GetPostStatusResponse;
  createdAt: string;
  updatedAt: string;
};

/**
 * Post fetched successfully
 */
export type GetPostResponse = {
  post: GetPostPost | null;
};

/** @internal */
export const GetPostStatusQueryParamEnum2$outboundSchema: z.ZodMiniEnum<
  typeof GetPostStatusQueryParamEnum2
> = z.enum(GetPostStatusQueryParamEnum2);

/** @internal */
export const GetPostStatusQueryParamEnum1$outboundSchema: z.ZodMiniEnum<
  typeof GetPostStatusQueryParamEnum1
> = z.enum(GetPostStatusQueryParamEnum1);

/** @internal */
export type GetPostStatusUnion$Outbound = string | Array<string>;

/** @internal */
export const GetPostStatusUnion$outboundSchema: z.ZodMiniType<
  GetPostStatusUnion$Outbound,
  GetPostStatusUnion
> = smartUnion([
  GetPostStatusQueryParamEnum1$outboundSchema,
  z.array(GetPostStatusQueryParamEnum2$outboundSchema),
]);

export function getPostStatusUnionToJSON(
  getPostStatusUnion: GetPostStatusUnion,
): string {
  return JSON.stringify(
    GetPostStatusUnion$outboundSchema.parse(getPostStatusUnion),
  );
}

/** @internal */
export const GetPostContentTypeEnum2$outboundSchema: z.ZodMiniEnum<
  typeof GetPostContentTypeEnum2
> = z.enum(GetPostContentTypeEnum2);

/** @internal */
export const GetPostContentTypeEnum1$outboundSchema: z.ZodMiniEnum<
  typeof GetPostContentTypeEnum1
> = z.enum(GetPostContentTypeEnum1);

/** @internal */
export type GetPostContentTypeUnion$Outbound = string | Array<string>;

/** @internal */
export const GetPostContentTypeUnion$outboundSchema: z.ZodMiniType<
  GetPostContentTypeUnion$Outbound,
  GetPostContentTypeUnion
> = smartUnion([
  GetPostContentTypeEnum1$outboundSchema,
  z.array(GetPostContentTypeEnum2$outboundSchema),
]);

export function getPostContentTypeUnionToJSON(
  getPostContentTypeUnion: GetPostContentTypeUnion,
): string {
  return JSON.stringify(
    GetPostContentTypeUnion$outboundSchema.parse(getPostContentTypeUnion),
  );
}

/** @internal */
export type GetPostRequest$Outbound = {
  organizationId: string;
  postId: string;
  status?: string | Array<string> | undefined;
  contentType?: string | Array<string> | undefined;
};

/** @internal */
export const GetPostRequest$outboundSchema: z.ZodMiniType<
  GetPostRequest$Outbound,
  GetPostRequest
> = z.object({
  organizationId: z.string(),
  postId: z.string(),
  status: z.optional(
    smartUnion([
      GetPostStatusQueryParamEnum1$outboundSchema,
      z.array(GetPostStatusQueryParamEnum2$outboundSchema),
    ]),
  ),
  contentType: z.optional(
    smartUnion([
      GetPostContentTypeEnum1$outboundSchema,
      z.array(GetPostContentTypeEnum2$outboundSchema),
    ]),
  ),
});

export function getPostRequestToJSON(getPostRequest: GetPostRequest): string {
  return JSON.stringify(GetPostRequest$outboundSchema.parse(getPostRequest));
}

/** @internal */
export const GetPostStatusResponse$inboundSchema: z.ZodMiniType<
  GetPostStatusResponse,
  unknown
> = openEnums.inboundSchema(GetPostStatusResponse);

/** @internal */
export const GetPostPost$inboundSchema: z.ZodMiniType<GetPostPost, unknown> = z
  .object({
    id: types.string(),
    title: types.string(),
    content: types.string(),
    markdown: types.string(),
    contentType: types.string(),
    sourceMetadata: types.optional(z.any()),
    status: GetPostStatusResponse$inboundSchema,
    createdAt: types.string(),
    updatedAt: types.string(),
  });

export function getPostPostFromJSON(
  jsonString: string,
): SafeParseResult<GetPostPost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPostPost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPostPost' from JSON`,
  );
}

/** @internal */
export const GetPostResponse$inboundSchema: z.ZodMiniType<
  GetPostResponse,
  unknown
> = z.object({
  post: types.nullable(z.lazy(() => GetPostPost$inboundSchema)),
});

export function getPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPostResponse' from JSON`,
  );
}
