/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0cc4f7bf3418
 */

import * as z from "zod/v4-mini";

export type GetSkillRequest = {
  /**
   * Skill name. Lowercase letters, digits, and hyphens only.
   */
  name: string;
};

/** @internal */
export type GetSkillRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetSkillRequest$outboundSchema: z.ZodMiniType<
  GetSkillRequest$Outbound,
  GetSkillRequest
> = z.object({
  name: z.string(),
});

export function getSkillRequestToJSON(
  getSkillRequest: GetSkillRequest,
): string {
  return JSON.stringify(GetSkillRequest$outboundSchema.parse(getSkillRequest));
}
