/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a6043135f0db
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Messaging platform the channel belongs to.
 */
export const GetChatByExternalChannelSource = {
  Discord: "discord",
  Slack: "slack",
} as const;
/**
 * Messaging platform the channel belongs to.
 */
export type GetChatByExternalChannelSource = ClosedEnum<
  typeof GetChatByExternalChannelSource
>;

export type GetChatByExternalChannelRequest = {
  /**
   * Messaging platform the channel belongs to.
   */
  source: GetChatByExternalChannelSource;
  /**
   * Channel ID on that platform.
   */
  id: string;
};

/** @internal */
export const GetChatByExternalChannelSource$outboundSchema: z.ZodMiniEnum<
  typeof GetChatByExternalChannelSource
> = z.enum(GetChatByExternalChannelSource);

/** @internal */
export type GetChatByExternalChannelRequest$Outbound = {
  source: string;
  id: string;
};

/** @internal */
export const GetChatByExternalChannelRequest$outboundSchema: z.ZodMiniType<
  GetChatByExternalChannelRequest$Outbound,
  GetChatByExternalChannelRequest
> = z.object({
  source: GetChatByExternalChannelSource$outboundSchema,
  id: z.string(),
});

export function getChatByExternalChannelRequestToJSON(
  getChatByExternalChannelRequest: GetChatByExternalChannelRequest,
): string {
  return JSON.stringify(
    GetChatByExternalChannelRequest$outboundSchema.parse(
      getChatByExternalChannelRequest,
    ),
  );
}
