/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7bc93e43ca08
 */

import * as z from "zod/v4-mini";

export type GetGeoVisibilityCompetitorShareRequest = {
  projectId: string;
  /**
   * Rolling window size in days. Ignored when from/to are set.
   */
  days?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export type GetGeoVisibilityCompetitorShareRequest$Outbound = {
  projectId: string;
  days?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export const GetGeoVisibilityCompetitorShareRequest$outboundSchema:
  z.ZodMiniType<
    GetGeoVisibilityCompetitorShareRequest$Outbound,
    GetGeoVisibilityCompetitorShareRequest
  > = z.object({
    projectId: z.string(),
    days: z.optional(z.int()),
    from: z.optional(z.string()),
    to: z.optional(z.string()),
  });

export function getGeoVisibilityCompetitorShareRequestToJSON(
  getGeoVisibilityCompetitorShareRequest:
    GetGeoVisibilityCompetitorShareRequest,
): string {
  return JSON.stringify(
    GetGeoVisibilityCompetitorShareRequest$outboundSchema.parse(
      getGeoVisibilityCompetitorShareRequest,
    ),
  );
}
