/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ba3590c99d4a
 */

import * as z from "zod/v4-mini";

export type GetGeoVisibilityLanguageShareRequest = {
  projectId: string;
  /**
   * Rolling window size in days. Ignored when from/to are set.
   */
  days?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export type GetGeoVisibilityLanguageShareRequest$Outbound = {
  projectId: string;
  days?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export const GetGeoVisibilityLanguageShareRequest$outboundSchema: z.ZodMiniType<
  GetGeoVisibilityLanguageShareRequest$Outbound,
  GetGeoVisibilityLanguageShareRequest
> = z.object({
  projectId: z.string(),
  days: z.optional(z.int()),
  from: z.optional(z.string()),
  to: z.optional(z.string()),
});

export function getGeoVisibilityLanguageShareRequestToJSON(
  getGeoVisibilityLanguageShareRequest: GetGeoVisibilityLanguageShareRequest,
): string {
  return JSON.stringify(
    GetGeoVisibilityLanguageShareRequest$outboundSchema.parse(
      getGeoVisibilityLanguageShareRequest,
    ),
  );
}
