/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9cc51a7330a1
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ImportGeoPromptsRequest = {
  projectId: string;
  body: models.ImportGeoPromptsRequest;
};

export type ImportGeoPromptsResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ImportGeoPromptsResponse;
};

/** @internal */
export type ImportGeoPromptsRequest$Outbound = {
  projectId: string;
  body: models.ImportGeoPromptsRequest$Outbound;
};

/** @internal */
export const ImportGeoPromptsRequest$outboundSchema: z.ZodMiniType<
  ImportGeoPromptsRequest$Outbound,
  ImportGeoPromptsRequest
> = z.object({
  projectId: z.string(),
  body: models.ImportGeoPromptsRequest$outboundSchema,
});

export function importGeoPromptsRequestToJSON(
  importGeoPromptsRequest: ImportGeoPromptsRequest,
): string {
  return JSON.stringify(
    ImportGeoPromptsRequest$outboundSchema.parse(importGeoPromptsRequest),
  );
}

/** @internal */
export const ImportGeoPromptsResponse$inboundSchema: z.ZodMiniType<
  ImportGeoPromptsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ImportGeoPromptsResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function importGeoPromptsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ImportGeoPromptsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImportGeoPromptsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImportGeoPromptsResponse' from JSON`,
  );
}
