/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5e40564d2317
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ImportGeoCompetitorsRequest = {
  projectId: string;
  body: models.ImportGeoCompetitorsRequest;
};

export type ImportGeoCompetitorsResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ImportGeoCompetitorsResponse;
};

/** @internal */
export type ImportGeoCompetitorsRequest$Outbound = {
  projectId: string;
  body: models.ImportGeoCompetitorsRequest$Outbound;
};

/** @internal */
export const ImportGeoCompetitorsRequest$outboundSchema: z.ZodMiniType<
  ImportGeoCompetitorsRequest$Outbound,
  ImportGeoCompetitorsRequest
> = z.object({
  projectId: z.string(),
  body: models.ImportGeoCompetitorsRequest$outboundSchema,
});

export function importGeoCompetitorsRequestToJSON(
  importGeoCompetitorsRequest: ImportGeoCompetitorsRequest,
): string {
  return JSON.stringify(
    ImportGeoCompetitorsRequest$outboundSchema.parse(
      importGeoCompetitorsRequest,
    ),
  );
}

/** @internal */
export const ImportGeoCompetitorsResponse$inboundSchema: z.ZodMiniType<
  ImportGeoCompetitorsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ImportGeoCompetitorsResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function importGeoCompetitorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ImportGeoCompetitorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImportGeoCompetitorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImportGeoCompetitorsResponse' from JSON`,
  );
}
