/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8a7bc85f36f5
 */

import * as z from "zod/v4-mini";

export type IssueGeoIngestTokenRequest = {
  /**
   * Bind the token to one project. Omit to track the whole organization.
   */
  projectId?: string | undefined;
};

/** @internal */
export type IssueGeoIngestTokenRequest$Outbound = {
  projectId?: string | undefined;
};

/** @internal */
export const IssueGeoIngestTokenRequest$outboundSchema: z.ZodMiniType<
  IssueGeoIngestTokenRequest$Outbound,
  IssueGeoIngestTokenRequest
> = z.object({
  projectId: z.optional(z.string()),
});

export function issueGeoIngestTokenRequestToJSON(
  issueGeoIngestTokenRequest: IssueGeoIngestTokenRequest,
): string {
  return JSON.stringify(
    IssueGeoIngestTokenRequest$outboundSchema.parse(issueGeoIngestTokenRequest),
  );
}
