/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 89c667286cb8
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListEventTriggersRequest = {
  /**
   * Filter by repository IDs using a comma-separated list
   */
  repositoryIds?: string | undefined;
};

export const ListEventTriggersSourceType = {
  GithubWebhook: "github_webhook",
} as const;
export type ListEventTriggersSourceType = ClosedEnum<
  typeof ListEventTriggersSourceType
>;

export const ListEventTriggersEventType = {
  Release: "release",
  Push: "push",
} as const;
export type ListEventTriggersEventType = OpenEnum<
  typeof ListEventTriggersEventType
>;

export type ListEventTriggersSourceConfig = {
  eventTypes: Array<ListEventTriggersEventType>;
  includePreReleases: boolean;
};

export type ListEventTriggersTargets = {
  repositoryIds: Array<string>;
};

export const ListEventTriggersOutputType = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
  Image: "image",
} as const;
export type ListEventTriggersOutputType = OpenEnum<
  typeof ListEventTriggersOutputType
>;

export const ListEventTriggersPublishDestination = {
  Webflow: "webflow",
  Framer: "framer",
  Custom: "custom",
} as const;
export type ListEventTriggersPublishDestination = OpenEnum<
  typeof ListEventTriggersPublishDestination
>;

export type ListEventTriggersOutputConfig = {
  publishDestination?: ListEventTriggersPublishDestination | undefined;
  brandVoiceId?: string | undefined;
};

export type ListEventTriggersEventTrigger = {
  id: string;
  organizationId: string;
  name: string;
  sourceType: ListEventTriggersSourceType;
  sourceConfig: ListEventTriggersSourceConfig;
  targets: ListEventTriggersTargets;
  outputType: ListEventTriggersOutputType;
  outputConfig?: ListEventTriggersOutputConfig | null | undefined;
  enabled: boolean;
  autoPublish: boolean;
  createdAt: string;
  updatedAt: string;
};

export type ListEventTriggersOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

/**
 * Event triggers fetched successfully
 */
export type ListEventTriggersResponse = {
  eventTriggers: Array<ListEventTriggersEventTrigger>;
  repositoryMap: { [k: string]: string };
  organization: ListEventTriggersOrganization;
};

/** @internal */
export type ListEventTriggersRequest$Outbound = {
  repositoryIds?: string | undefined;
};

/** @internal */
export const ListEventTriggersRequest$outboundSchema: z.ZodMiniType<
  ListEventTriggersRequest$Outbound,
  ListEventTriggersRequest
> = z.object({
  repositoryIds: z.optional(z.string()),
});

export function listEventTriggersRequestToJSON(
  listEventTriggersRequest: ListEventTriggersRequest,
): string {
  return JSON.stringify(
    ListEventTriggersRequest$outboundSchema.parse(listEventTriggersRequest),
  );
}

/** @internal */
export const ListEventTriggersSourceType$inboundSchema: z.ZodMiniEnum<
  typeof ListEventTriggersSourceType
> = z.enum(ListEventTriggersSourceType);

/** @internal */
export const ListEventTriggersEventType$inboundSchema: z.ZodMiniType<
  ListEventTriggersEventType,
  unknown
> = openEnums.inboundSchema(ListEventTriggersEventType);

/** @internal */
export const ListEventTriggersSourceConfig$inboundSchema: z.ZodMiniType<
  ListEventTriggersSourceConfig,
  unknown
> = z.object({
  eventTypes: z.array(ListEventTriggersEventType$inboundSchema),
  includePreReleases: z._default(types.boolean(), true),
});

export function listEventTriggersSourceConfigFromJSON(
  jsonString: string,
): SafeParseResult<ListEventTriggersSourceConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEventTriggersSourceConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEventTriggersSourceConfig' from JSON`,
  );
}

/** @internal */
export const ListEventTriggersTargets$inboundSchema: z.ZodMiniType<
  ListEventTriggersTargets,
  unknown
> = z.object({
  repositoryIds: z.array(types.string()),
});

export function listEventTriggersTargetsFromJSON(
  jsonString: string,
): SafeParseResult<ListEventTriggersTargets, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEventTriggersTargets$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEventTriggersTargets' from JSON`,
  );
}

/** @internal */
export const ListEventTriggersOutputType$inboundSchema: z.ZodMiniType<
  ListEventTriggersOutputType,
  unknown
> = openEnums.inboundSchema(ListEventTriggersOutputType);

/** @internal */
export const ListEventTriggersPublishDestination$inboundSchema: z.ZodMiniType<
  ListEventTriggersPublishDestination,
  unknown
> = openEnums.inboundSchema(ListEventTriggersPublishDestination);

/** @internal */
export const ListEventTriggersOutputConfig$inboundSchema: z.ZodMiniType<
  ListEventTriggersOutputConfig,
  unknown
> = z.object({
  publishDestination: types.optional(
    ListEventTriggersPublishDestination$inboundSchema,
  ),
  brandVoiceId: types.optional(types.string()),
});

export function listEventTriggersOutputConfigFromJSON(
  jsonString: string,
): SafeParseResult<ListEventTriggersOutputConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEventTriggersOutputConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEventTriggersOutputConfig' from JSON`,
  );
}

/** @internal */
export const ListEventTriggersEventTrigger$inboundSchema: z.ZodMiniType<
  ListEventTriggersEventTrigger,
  unknown
> = z.object({
  id: types.string(),
  organizationId: types.string(),
  name: types.string(),
  sourceType: ListEventTriggersSourceType$inboundSchema,
  sourceConfig: z.lazy(() => ListEventTriggersSourceConfig$inboundSchema),
  targets: z.lazy(() => ListEventTriggersTargets$inboundSchema),
  outputType: ListEventTriggersOutputType$inboundSchema,
  outputConfig: z.optional(
    z.nullable(z.lazy(() => ListEventTriggersOutputConfig$inboundSchema)),
  ),
  enabled: types.boolean(),
  autoPublish: types.boolean(),
  createdAt: types.string(),
  updatedAt: types.string(),
});

export function listEventTriggersEventTriggerFromJSON(
  jsonString: string,
): SafeParseResult<ListEventTriggersEventTrigger, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEventTriggersEventTrigger$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEventTriggersEventTrigger' from JSON`,
  );
}

/** @internal */
export const ListEventTriggersOrganization$inboundSchema: z.ZodMiniType<
  ListEventTriggersOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function listEventTriggersOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<ListEventTriggersOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEventTriggersOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEventTriggersOrganization' from JSON`,
  );
}

/** @internal */
export const ListEventTriggersResponse$inboundSchema: z.ZodMiniType<
  ListEventTriggersResponse,
  unknown
> = z.object({
  eventTriggers: z.array(
    z.lazy(() => ListEventTriggersEventTrigger$inboundSchema),
  ),
  repositoryMap: z.record(z.string(), types.string()),
  organization: z.lazy(() => ListEventTriggersOrganization$inboundSchema),
});

export function listEventTriggersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListEventTriggersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEventTriggersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEventTriggersResponse' from JSON`,
  );
}
