/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6c2e7f734daf
 */

import * as z from "zod/v4-mini";

export type ListGeoContentGapsRequest = {
  projectId: string;
};

/** @internal */
export type ListGeoContentGapsRequest$Outbound = {
  projectId: string;
};

/** @internal */
export const ListGeoContentGapsRequest$outboundSchema: z.ZodMiniType<
  ListGeoContentGapsRequest$Outbound,
  ListGeoContentGapsRequest
> = z.object({
  projectId: z.string(),
});

export function listGeoContentGapsRequestToJSON(
  listGeoContentGapsRequest: ListGeoContentGapsRequest,
): string {
  return JSON.stringify(
    ListGeoContentGapsRequest$outboundSchema.parse(listGeoContentGapsRequest),
  );
}
