/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: edbc77e5a0b7
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListAgentChatsRequest = {
  limit?: number | undefined;
};

export type ListAgentChatsResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ListAgentChatsResponse;
};

/** @internal */
export type ListAgentChatsRequest$Outbound = {
  limit: number;
};

/** @internal */
export const ListAgentChatsRequest$outboundSchema: z.ZodMiniType<
  ListAgentChatsRequest$Outbound,
  ListAgentChatsRequest
> = z.object({
  limit: z._default(z.int(), 20),
});

export function listAgentChatsRequestToJSON(
  listAgentChatsRequest: ListAgentChatsRequest,
): string {
  return JSON.stringify(
    ListAgentChatsRequest$outboundSchema.parse(listAgentChatsRequest),
  );
}

/** @internal */
export const ListAgentChatsResponse$inboundSchema: z.ZodMiniType<
  ListAgentChatsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ListAgentChatsResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listAgentChatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAgentChatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAgentChatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAgentChatsResponse' from JSON`,
  );
}
