/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a141077999e5
 */

import * as z from "zod/v4-mini";

export type ListGeoShelfSourcesRequest = {
  projectId: string;
  offset?: number | null | undefined;
  limit?: number | undefined;
};

/** @internal */
export type ListGeoShelfSourcesRequest$Outbound = {
  projectId: string;
  offset: number | null;
  limit: number;
};

/** @internal */
export const ListGeoShelfSourcesRequest$outboundSchema: z.ZodMiniType<
  ListGeoShelfSourcesRequest$Outbound,
  ListGeoShelfSourcesRequest
> = z.object({
  projectId: z.string(),
  offset: z.nullable(z._default(z.int(), 0)),
  limit: z._default(z.int(), 20),
});

export function listGeoShelfSourcesRequestToJSON(
  listGeoShelfSourcesRequest: ListGeoShelfSourcesRequest,
): string {
  return JSON.stringify(
    ListGeoShelfSourcesRequest$outboundSchema.parse(listGeoShelfSourcesRequest),
  );
}
