/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 207f5e1de7e4
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const ListWebhookDeliveriesQueryParamStatus = {
  All: "all",
  Pending: "pending",
  Sending: "sending",
  Retrying: "retrying",
  Succeeded: "succeeded",
  Failed: "failed",
  Cancelled: "cancelled",
} as const;
export type ListWebhookDeliveriesQueryParamStatus = ClosedEnum<
  typeof ListWebhookDeliveriesQueryParamStatus
>;

export type ListWebhookDeliveriesRequest = {
  offset?: number | null | undefined;
  status?: ListWebhookDeliveriesQueryParamStatus | undefined;
};

export const ListWebhookDeliveriesEventType = {
  PostGenerationCompleted: "post.generation.completed",
  PostGenerationFailed: "post.generation.failed",
  PostGenerationSkipped: "post.generation.skipped",
  BrandIdentityGenerationCompleted: "brand_identity.generation.completed",
  BrandIdentityGenerationFailed: "brand_identity.generation.failed",
  PostPublished: "post.published",
  PostCreated: "post.created",
  PostUpdated: "post.updated",
  PostDeleted: "post.deleted",
  PostUnpublished: "post.unpublished",
  GeoScanCompleted: "geo.scan.completed",
  GeoScanFailed: "geo.scan.failed",
} as const;
export type ListWebhookDeliveriesEventType = OpenEnum<
  typeof ListWebhookDeliveriesEventType
>;

export const ListWebhookDeliveriesDeliveryStatus = {
  Pending: "pending",
  Sending: "sending",
  Retrying: "retrying",
  Succeeded: "succeeded",
  Failed: "failed",
  Cancelled: "cancelled",
} as const;
export type ListWebhookDeliveriesDeliveryStatus = OpenEnum<
  typeof ListWebhookDeliveriesDeliveryStatus
>;

export type ListWebhookDeliveriesDelivery = {
  id: string;
  eventId: string;
  endpointId: string;
  url: string;
  eventType: ListWebhookDeliveriesEventType;
  status: ListWebhookDeliveriesDeliveryStatus;
  attemptCount: number;
  nextAttemptAt: string;
  createdAt: string;
  statusCode: number | null;
  error: string | null;
};

/**
 * Delivery history
 */
export type ListWebhookDeliveriesResponse = {
  deliveries: Array<ListWebhookDeliveriesDelivery>;
  hasMore: boolean;
};

/** @internal */
export const ListWebhookDeliveriesQueryParamStatus$outboundSchema:
  z.ZodMiniEnum<typeof ListWebhookDeliveriesQueryParamStatus> = z.enum(
    ListWebhookDeliveriesQueryParamStatus,
  );

/** @internal */
export type ListWebhookDeliveriesRequest$Outbound = {
  offset: number | null;
  status: string;
};

/** @internal */
export const ListWebhookDeliveriesRequest$outboundSchema: z.ZodMiniType<
  ListWebhookDeliveriesRequest$Outbound,
  ListWebhookDeliveriesRequest
> = z.object({
  offset: z.nullable(z._default(z.int(), 0)),
  status: z._default(
    ListWebhookDeliveriesQueryParamStatus$outboundSchema,
    "all",
  ),
});

export function listWebhookDeliveriesRequestToJSON(
  listWebhookDeliveriesRequest: ListWebhookDeliveriesRequest,
): string {
  return JSON.stringify(
    ListWebhookDeliveriesRequest$outboundSchema.parse(
      listWebhookDeliveriesRequest,
    ),
  );
}

/** @internal */
export const ListWebhookDeliveriesEventType$inboundSchema: z.ZodMiniType<
  ListWebhookDeliveriesEventType,
  unknown
> = openEnums.inboundSchema(ListWebhookDeliveriesEventType);

/** @internal */
export const ListWebhookDeliveriesDeliveryStatus$inboundSchema: z.ZodMiniType<
  ListWebhookDeliveriesDeliveryStatus,
  unknown
> = openEnums.inboundSchema(ListWebhookDeliveriesDeliveryStatus);

/** @internal */
export const ListWebhookDeliveriesDelivery$inboundSchema: z.ZodMiniType<
  ListWebhookDeliveriesDelivery,
  unknown
> = z.object({
  id: types.string(),
  eventId: types.string(),
  endpointId: types.string(),
  url: types.string(),
  eventType: ListWebhookDeliveriesEventType$inboundSchema,
  status: ListWebhookDeliveriesDeliveryStatus$inboundSchema,
  attemptCount: types.number(),
  nextAttemptAt: types.string(),
  createdAt: types.string(),
  statusCode: types.nullable(types.number()),
  error: types.nullable(types.string()),
});

export function listWebhookDeliveriesDeliveryFromJSON(
  jsonString: string,
): SafeParseResult<ListWebhookDeliveriesDelivery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWebhookDeliveriesDelivery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWebhookDeliveriesDelivery' from JSON`,
  );
}

/** @internal */
export const ListWebhookDeliveriesResponse$inboundSchema: z.ZodMiniType<
  ListWebhookDeliveriesResponse,
  unknown
> = z.object({
  deliveries: z.array(
    z.lazy(() => ListWebhookDeliveriesDelivery$inboundSchema),
  ),
  hasMore: types.boolean(),
});

export function listWebhookDeliveriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListWebhookDeliveriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWebhookDeliveriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWebhookDeliveriesResponse' from JSON`,
  );
}
