/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 73f5ab6050e3
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Triage status.
 */
export const ListFeedbackStatus = {
  New: "new",
  Triaged: "triaged",
  Resolved: "resolved",
  Archived: "archived",
} as const;
/**
 * Triage status.
 */
export type ListFeedbackStatus = ClosedEnum<typeof ListFeedbackStatus>;

/**
 * What kind of feedback this is.
 */
export const Kind = {
  Bug: "bug",
  Feature: "feature",
  Praise: "praise",
  Question: "question",
  Other: "other",
} as const;
/**
 * What kind of feedback this is.
 */
export type Kind = ClosedEnum<typeof Kind>;

export type ListFeedbackRequest = {
  /**
   * Triage status.
   */
  status?: ListFeedbackStatus | undefined;
  /**
   * What kind of feedback this is.
   */
  kind?: Kind | undefined;
  projectId?: string | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
};

/** @internal */
export const ListFeedbackStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListFeedbackStatus
> = z.enum(ListFeedbackStatus);

/** @internal */
export const Kind$outboundSchema: z.ZodMiniEnum<typeof Kind> = z.enum(Kind);

/** @internal */
export type ListFeedbackRequest$Outbound = {
  status?: string | undefined;
  kind?: string | undefined;
  projectId?: string | undefined;
  limit: number;
  page: number;
};

/** @internal */
export const ListFeedbackRequest$outboundSchema: z.ZodMiniType<
  ListFeedbackRequest$Outbound,
  ListFeedbackRequest
> = z.object({
  status: z.optional(ListFeedbackStatus$outboundSchema),
  kind: z.optional(Kind$outboundSchema),
  projectId: z.optional(z.string()),
  limit: z._default(z.int(), 25),
  page: z._default(z.int(), 1),
});

export function listFeedbackRequestToJSON(
  listFeedbackRequest: ListFeedbackRequest,
): string {
  return JSON.stringify(
    ListFeedbackRequest$outboundSchema.parse(listFeedbackRequest),
  );
}
