/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 67b26fff55fe
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListSchedulesRequest = {
  /**
   * Filter by repository IDs using a comma-separated list
   */
  repositoryIds?: string | undefined;
};

export const ListSchedulesSourceType = {
  Cron: "cron",
} as const;
export type ListSchedulesSourceType = ClosedEnum<
  typeof ListSchedulesSourceType
>;

export const ListSchedulesFrequency = {
  Daily: "daily",
  Weekly: "weekly",
  Monthly: "monthly",
} as const;
export type ListSchedulesFrequency = OpenEnum<typeof ListSchedulesFrequency>;

export type ListSchedulesCron = {
  frequency: ListSchedulesFrequency;
  hour: number;
  minute: number;
  dayOfWeek?: number | undefined;
  dayOfMonth?: number | undefined;
};

export type ListSchedulesSourceConfig = {
  cron: ListSchedulesCron;
};

export type ListSchedulesTargets = {
  repositoryIds: Array<string>;
};

export const ListSchedulesOutputType = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
} as const;
export type ListSchedulesOutputType = OpenEnum<typeof ListSchedulesOutputType>;

export const ListSchedulesPublishDestination = {
  Webflow: "webflow",
  Framer: "framer",
  Custom: "custom",
} as const;
export type ListSchedulesPublishDestination = OpenEnum<
  typeof ListSchedulesPublishDestination
>;

export type ListSchedulesOutputConfig = {
  publishDestination?: ListSchedulesPublishDestination | undefined;
  brandVoiceId?: string | undefined;
};

export const ListSchedulesLookbackWindow = {
  CurrentDay: "current_day",
  Yesterday: "yesterday",
  Last7Days: "last_7_days",
  Last14Days: "last_14_days",
  Last30Days: "last_30_days",
} as const;
export type ListSchedulesLookbackWindow = OpenEnum<
  typeof ListSchedulesLookbackWindow
>;

export type ListSchedulesSchedule = {
  id: string;
  organizationId: string;
  name: string;
  sourceType: ListSchedulesSourceType;
  sourceConfig: ListSchedulesSourceConfig;
  targets: ListSchedulesTargets;
  outputType: ListSchedulesOutputType;
  outputConfig?: ListSchedulesOutputConfig | null | undefined;
  enabled: boolean;
  autoPublish: boolean;
  createdAt: string;
  updatedAt: string;
  lookbackWindow: ListSchedulesLookbackWindow;
};

export type ListSchedulesOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

/**
 * Schedules fetched successfully
 */
export type ListSchedulesResponse = {
  schedules: Array<ListSchedulesSchedule>;
  repositoryMap: { [k: string]: string };
  organization: ListSchedulesOrganization;
};

/** @internal */
export type ListSchedulesRequest$Outbound = {
  repositoryIds?: string | undefined;
};

/** @internal */
export const ListSchedulesRequest$outboundSchema: z.ZodMiniType<
  ListSchedulesRequest$Outbound,
  ListSchedulesRequest
> = z.object({
  repositoryIds: z.optional(z.string()),
});

export function listSchedulesRequestToJSON(
  listSchedulesRequest: ListSchedulesRequest,
): string {
  return JSON.stringify(
    ListSchedulesRequest$outboundSchema.parse(listSchedulesRequest),
  );
}

/** @internal */
export const ListSchedulesSourceType$inboundSchema: z.ZodMiniEnum<
  typeof ListSchedulesSourceType
> = z.enum(ListSchedulesSourceType);

/** @internal */
export const ListSchedulesFrequency$inboundSchema: z.ZodMiniType<
  ListSchedulesFrequency,
  unknown
> = openEnums.inboundSchema(ListSchedulesFrequency);

/** @internal */
export const ListSchedulesCron$inboundSchema: z.ZodMiniType<
  ListSchedulesCron,
  unknown
> = z.object({
  frequency: ListSchedulesFrequency$inboundSchema,
  hour: types.number(),
  minute: types.number(),
  dayOfWeek: types.optional(types.number()),
  dayOfMonth: types.optional(types.number()),
});

export function listSchedulesCronFromJSON(
  jsonString: string,
): SafeParseResult<ListSchedulesCron, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSchedulesCron$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSchedulesCron' from JSON`,
  );
}

/** @internal */
export const ListSchedulesSourceConfig$inboundSchema: z.ZodMiniType<
  ListSchedulesSourceConfig,
  unknown
> = z.object({
  cron: z.lazy(() => ListSchedulesCron$inboundSchema),
});

export function listSchedulesSourceConfigFromJSON(
  jsonString: string,
): SafeParseResult<ListSchedulesSourceConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSchedulesSourceConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSchedulesSourceConfig' from JSON`,
  );
}

/** @internal */
export const ListSchedulesTargets$inboundSchema: z.ZodMiniType<
  ListSchedulesTargets,
  unknown
> = z.object({
  repositoryIds: z.array(types.string()),
});

export function listSchedulesTargetsFromJSON(
  jsonString: string,
): SafeParseResult<ListSchedulesTargets, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSchedulesTargets$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSchedulesTargets' from JSON`,
  );
}

/** @internal */
export const ListSchedulesOutputType$inboundSchema: z.ZodMiniType<
  ListSchedulesOutputType,
  unknown
> = openEnums.inboundSchema(ListSchedulesOutputType);

/** @internal */
export const ListSchedulesPublishDestination$inboundSchema: z.ZodMiniType<
  ListSchedulesPublishDestination,
  unknown
> = openEnums.inboundSchema(ListSchedulesPublishDestination);

/** @internal */
export const ListSchedulesOutputConfig$inboundSchema: z.ZodMiniType<
  ListSchedulesOutputConfig,
  unknown
> = z.object({
  publishDestination: types.optional(
    ListSchedulesPublishDestination$inboundSchema,
  ),
  brandVoiceId: types.optional(types.string()),
});

export function listSchedulesOutputConfigFromJSON(
  jsonString: string,
): SafeParseResult<ListSchedulesOutputConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSchedulesOutputConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSchedulesOutputConfig' from JSON`,
  );
}

/** @internal */
export const ListSchedulesLookbackWindow$inboundSchema: z.ZodMiniType<
  ListSchedulesLookbackWindow,
  unknown
> = openEnums.inboundSchema(ListSchedulesLookbackWindow);

/** @internal */
export const ListSchedulesSchedule$inboundSchema: z.ZodMiniType<
  ListSchedulesSchedule,
  unknown
> = z.object({
  id: types.string(),
  organizationId: types.string(),
  name: types.string(),
  sourceType: ListSchedulesSourceType$inboundSchema,
  sourceConfig: z.lazy(() => ListSchedulesSourceConfig$inboundSchema),
  targets: z.lazy(() => ListSchedulesTargets$inboundSchema),
  outputType: ListSchedulesOutputType$inboundSchema,
  outputConfig: z.optional(
    z.nullable(z.lazy(() => ListSchedulesOutputConfig$inboundSchema)),
  ),
  enabled: types.boolean(),
  autoPublish: types.boolean(),
  createdAt: types.string(),
  updatedAt: types.string(),
  lookbackWindow: ListSchedulesLookbackWindow$inboundSchema,
});

export function listSchedulesScheduleFromJSON(
  jsonString: string,
): SafeParseResult<ListSchedulesSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSchedulesSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSchedulesSchedule' from JSON`,
  );
}

/** @internal */
export const ListSchedulesOrganization$inboundSchema: z.ZodMiniType<
  ListSchedulesOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function listSchedulesOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<ListSchedulesOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSchedulesOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSchedulesOrganization' from JSON`,
  );
}

/** @internal */
export const ListSchedulesResponse$inboundSchema: z.ZodMiniType<
  ListSchedulesResponse,
  unknown
> = z.object({
  schedules: z.array(z.lazy(() => ListSchedulesSchedule$inboundSchema)),
  repositoryMap: z.record(z.string(), types.string()),
  organization: z.lazy(() => ListSchedulesOrganization$inboundSchema),
});

export function listSchedulesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSchedulesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSchedulesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSchedulesResponse' from JSON`,
  );
}
