/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0a3b616dcea7
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PlanGeoContentBriefRequest = {
  projectId: string;
  body: models.PlanGeoContentBriefRequest;
};

export type PlanGeoContentBriefResponse = {
  headers: { [k: string]: Array<string> };
  result: models.PlanGeoContentBriefResponse;
};

/** @internal */
export type PlanGeoContentBriefRequest$Outbound = {
  projectId: string;
  body: models.PlanGeoContentBriefRequest$Outbound;
};

/** @internal */
export const PlanGeoContentBriefRequest$outboundSchema: z.ZodMiniType<
  PlanGeoContentBriefRequest$Outbound,
  PlanGeoContentBriefRequest
> = z.object({
  projectId: z.string(),
  body: models.PlanGeoContentBriefRequest$outboundSchema,
});

export function planGeoContentBriefRequestToJSON(
  planGeoContentBriefRequest: PlanGeoContentBriefRequest,
): string {
  return JSON.stringify(
    PlanGeoContentBriefRequest$outboundSchema.parse(planGeoContentBriefRequest),
  );
}

/** @internal */
export const PlanGeoContentBriefResponse$inboundSchema: z.ZodMiniType<
  PlanGeoContentBriefResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.PlanGeoContentBriefResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function planGeoContentBriefResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlanGeoContentBriefResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlanGeoContentBriefResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlanGeoContentBriefResponse' from JSON`,
  );
}
