/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6ecdd54ea9e6
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PostChatMessageRequest = {
  chatId: string;
  body: models.SendChatMessageRequest;
};

/** @internal */
export type PostChatMessageRequest$Outbound = {
  chatId: string;
  body: models.SendChatMessageRequest$Outbound;
};

/** @internal */
export const PostChatMessageRequest$outboundSchema: z.ZodMiniType<
  PostChatMessageRequest$Outbound,
  PostChatMessageRequest
> = z.object({
  chatId: z.string(),
  body: models.SendChatMessageRequest$outboundSchema,
});

export function postChatMessageRequestToJSON(
  postChatMessageRequest: PostChatMessageRequest,
): string {
  return JSON.stringify(
    PostChatMessageRequest$outboundSchema.parse(postChatMessageRequest),
  );
}
