/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fe8863ec8cb3
 */

import * as z from "zod/v4-mini";

export type RotateGeoIngestTokenRequest = {
  /**
   * Bind the token to one project. Omit to track the whole organization.
   */
  projectId?: string | undefined;
};

/** @internal */
export type RotateGeoIngestTokenRequest$Outbound = {
  projectId?: string | undefined;
};

/** @internal */
export const RotateGeoIngestTokenRequest$outboundSchema: z.ZodMiniType<
  RotateGeoIngestTokenRequest$Outbound,
  RotateGeoIngestTokenRequest
> = z.object({
  projectId: z.optional(z.string()),
});

export function rotateGeoIngestTokenRequestToJSON(
  rotateGeoIngestTokenRequest: RotateGeoIngestTokenRequest,
): string {
  return JSON.stringify(
    RotateGeoIngestTokenRequest$outboundSchema.parse(
      rotateGeoIngestTokenRequest,
    ),
  );
}
