/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a4ad324cd2b0
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SendAgentSessionMessageRequest = {
  sessionId: string;
  body: models.SendAgentMessageRequest;
};

/**
 * Upstream eve response with the next continuation token for this session.
 */
export type SendAgentSessionMessageResponseBody = {};

export type SendAgentSessionMessageResponse = {
  headers: { [k: string]: Array<string> };
  result: SendAgentSessionMessageResponseBody;
};

/** @internal */
export type SendAgentSessionMessageRequest$Outbound = {
  sessionId: string;
  body: models.SendAgentMessageRequest$Outbound;
};

/** @internal */
export const SendAgentSessionMessageRequest$outboundSchema: z.ZodMiniType<
  SendAgentSessionMessageRequest$Outbound,
  SendAgentSessionMessageRequest
> = z.object({
  sessionId: z.string(),
  body: models.SendAgentMessageRequest$outboundSchema,
});

export function sendAgentSessionMessageRequestToJSON(
  sendAgentSessionMessageRequest: SendAgentSessionMessageRequest,
): string {
  return JSON.stringify(
    SendAgentSessionMessageRequest$outboundSchema.parse(
      sendAgentSessionMessageRequest,
    ),
  );
}

/** @internal */
export const SendAgentSessionMessageResponseBody$inboundSchema: z.ZodMiniType<
  SendAgentSessionMessageResponseBody,
  unknown
> = z.object({});

export function sendAgentSessionMessageResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SendAgentSessionMessageResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SendAgentSessionMessageResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendAgentSessionMessageResponseBody' from JSON`,
  );
}

/** @internal */
export const SendAgentSessionMessageResponse$inboundSchema: z.ZodMiniType<
  SendAgentSessionMessageResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => SendAgentSessionMessageResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function sendAgentSessionMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendAgentSessionMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendAgentSessionMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendAgentSessionMessageResponse' from JSON`,
  );
}
