/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c8e264503702
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type StartGeoAgentReadinessScanRequest = {
  projectId: string;
};

export type StartGeoAgentReadinessScanResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GeoAgentReadinessScanResponse;
};

/** @internal */
export type StartGeoAgentReadinessScanRequest$Outbound = {
  projectId: string;
};

/** @internal */
export const StartGeoAgentReadinessScanRequest$outboundSchema: z.ZodMiniType<
  StartGeoAgentReadinessScanRequest$Outbound,
  StartGeoAgentReadinessScanRequest
> = z.object({
  projectId: z.string(),
});

export function startGeoAgentReadinessScanRequestToJSON(
  startGeoAgentReadinessScanRequest: StartGeoAgentReadinessScanRequest,
): string {
  return JSON.stringify(
    StartGeoAgentReadinessScanRequest$outboundSchema.parse(
      startGeoAgentReadinessScanRequest,
    ),
  );
}

/** @internal */
export const StartGeoAgentReadinessScanResponse$inboundSchema: z.ZodMiniType<
  StartGeoAgentReadinessScanResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.GeoAgentReadinessScanResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function startGeoAgentReadinessScanResponseFromJSON(
  jsonString: string,
): SafeParseResult<StartGeoAgentReadinessScanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      StartGeoAgentReadinessScanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StartGeoAgentReadinessScanResponse' from JSON`,
  );
}
