/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: da267508cdf2
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type StreamAgentSessionEventsRequest = {
  sessionId: string;
};

export type StreamAgentSessionEventsResponse = {
  headers: { [k: string]: Array<string> };
  result: string;
};

/** @internal */
export type StreamAgentSessionEventsRequest$Outbound = {
  sessionId: string;
};

/** @internal */
export const StreamAgentSessionEventsRequest$outboundSchema: z.ZodMiniType<
  StreamAgentSessionEventsRequest$Outbound,
  StreamAgentSessionEventsRequest
> = z.object({
  sessionId: z.string(),
});

export function streamAgentSessionEventsRequestToJSON(
  streamAgentSessionEventsRequest: StreamAgentSessionEventsRequest,
): string {
  return JSON.stringify(
    StreamAgentSessionEventsRequest$outboundSchema.parse(
      streamAgentSessionEventsRequest,
    ),
  );
}

/** @internal */
export const StreamAgentSessionEventsResponse$inboundSchema: z.ZodMiniType<
  StreamAgentSessionEventsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function streamAgentSessionEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<StreamAgentSessionEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamAgentSessionEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamAgentSessionEventsResponse' from JSON`,
  );
}
