/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ac2de4cb5550
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SubmitFeedbackResponse = {
  headers: { [k: string]: Array<string> };
  result: models.SubmitFeedbackResponse;
};

/** @internal */
export const SubmitFeedbackResponse$inboundSchema: z.ZodMiniType<
  SubmitFeedbackResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.SubmitFeedbackResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function submitFeedbackResponseFromJSON(
  jsonString: string,
): SafeParseResult<SubmitFeedbackResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubmitFeedbackResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubmitFeedbackResponse' from JSON`,
  );
}
