/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aa0f6dea8bab
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SubmitOrganizationFeedbackRequest = {
  /**
   * Your organization slug, as shown in your feedback URL on the Feedback page.
   */
  organizationSlug: string;
  body: models.SubmitFeedbackRequest;
};

export type SubmitOrganizationFeedbackResponse = {
  headers: { [k: string]: Array<string> };
  result: models.SubmitFeedbackResponse;
};

/** @internal */
export type SubmitOrganizationFeedbackRequest$Outbound = {
  organizationSlug: string;
  body: models.SubmitFeedbackRequest$Outbound;
};

/** @internal */
export const SubmitOrganizationFeedbackRequest$outboundSchema: z.ZodMiniType<
  SubmitOrganizationFeedbackRequest$Outbound,
  SubmitOrganizationFeedbackRequest
> = z.object({
  organizationSlug: z.string(),
  body: models.SubmitFeedbackRequest$outboundSchema,
});

export function submitOrganizationFeedbackRequestToJSON(
  submitOrganizationFeedbackRequest: SubmitOrganizationFeedbackRequest,
): string {
  return JSON.stringify(
    SubmitOrganizationFeedbackRequest$outboundSchema.parse(
      submitOrganizationFeedbackRequest,
    ),
  );
}

/** @internal */
export const SubmitOrganizationFeedbackResponse$inboundSchema: z.ZodMiniType<
  SubmitOrganizationFeedbackResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.SubmitFeedbackResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function submitOrganizationFeedbackResponseFromJSON(
  jsonString: string,
): SafeParseResult<SubmitOrganizationFeedbackResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SubmitOrganizationFeedbackResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubmitOrganizationFeedbackResponse' from JSON`,
  );
}
