/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 941b1723b982
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SuggestGeoCompetitorsRequest = {
  projectId: string;
  /**
   * Website domain, for example `example.com`.
   */
  domain: string;
};

export type SuggestGeoCompetitorsResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GeoCompetitorSuggestionsResponse;
};

/** @internal */
export type SuggestGeoCompetitorsRequest$Outbound = {
  projectId: string;
  domain: string;
};

/** @internal */
export const SuggestGeoCompetitorsRequest$outboundSchema: z.ZodMiniType<
  SuggestGeoCompetitorsRequest$Outbound,
  SuggestGeoCompetitorsRequest
> = z.object({
  projectId: z.string(),
  domain: z.string(),
});

export function suggestGeoCompetitorsRequestToJSON(
  suggestGeoCompetitorsRequest: SuggestGeoCompetitorsRequest,
): string {
  return JSON.stringify(
    SuggestGeoCompetitorsRequest$outboundSchema.parse(
      suggestGeoCompetitorsRequest,
    ),
  );
}

/** @internal */
export const SuggestGeoCompetitorsResponse$inboundSchema: z.ZodMiniType<
  SuggestGeoCompetitorsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.GeoCompetitorSuggestionsResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function suggestGeoCompetitorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<SuggestGeoCompetitorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SuggestGeoCompetitorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SuggestGeoCompetitorsResponse' from JSON`,
  );
}
