/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 301ac4f9113f
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateProjectRequest = {
  projectId: string;
  body: models.PatchGeoProjectRequest;
};

/** @internal */
export type UpdateProjectRequest$Outbound = {
  projectId: string;
  body: models.PatchGeoProjectRequest$Outbound;
};

/** @internal */
export const UpdateProjectRequest$outboundSchema: z.ZodMiniType<
  UpdateProjectRequest$Outbound,
  UpdateProjectRequest
> = z.object({
  projectId: z.string(),
  body: models.PatchGeoProjectRequest$outboundSchema,
});

export function updateProjectRequestToJSON(
  updateProjectRequest: UpdateProjectRequest,
): string {
  return JSON.stringify(
    UpdateProjectRequest$outboundSchema.parse(updateProjectRequest),
  );
}
