/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5f100b8365d4
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateEventTriggerRequest = {
  triggerId: string;
  body: models.PatchEventTriggerRequest;
};

export const UpdateEventTriggerSourceType = {
  GithubWebhook: "github_webhook",
} as const;
export type UpdateEventTriggerSourceType = ClosedEnum<
  typeof UpdateEventTriggerSourceType
>;

export const UpdateEventTriggerEventType = {
  Release: "release",
  Push: "push",
} as const;
export type UpdateEventTriggerEventType = OpenEnum<
  typeof UpdateEventTriggerEventType
>;

export type UpdateEventTriggerSourceConfig = {
  eventTypes: Array<UpdateEventTriggerEventType>;
  includePreReleases: boolean;
};

export type UpdateEventTriggerTargets = {
  repositoryIds: Array<string>;
};

export const UpdateEventTriggerOutputType = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
  Image: "image",
} as const;
export type UpdateEventTriggerOutputType = OpenEnum<
  typeof UpdateEventTriggerOutputType
>;

export const UpdateEventTriggerPublishDestination = {
  Webflow: "webflow",
  Framer: "framer",
  Custom: "custom",
} as const;
export type UpdateEventTriggerPublishDestination = OpenEnum<
  typeof UpdateEventTriggerPublishDestination
>;

export type UpdateEventTriggerOutputConfig = {
  publishDestination?: UpdateEventTriggerPublishDestination | undefined;
  brandVoiceId?: string | undefined;
};

export type UpdateEventTriggerEventTrigger = {
  id: string;
  organizationId: string;
  name: string;
  sourceType: UpdateEventTriggerSourceType;
  sourceConfig: UpdateEventTriggerSourceConfig;
  targets: UpdateEventTriggerTargets;
  outputType: UpdateEventTriggerOutputType;
  outputConfig?: UpdateEventTriggerOutputConfig | null | undefined;
  enabled: boolean;
  autoPublish: boolean;
  createdAt: string;
  updatedAt: string;
};

export type UpdateEventTriggerOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

/**
 * Event trigger updated successfully
 */
export type UpdateEventTriggerResponse = {
  eventTrigger: UpdateEventTriggerEventTrigger;
  organization: UpdateEventTriggerOrganization;
};

/** @internal */
export type UpdateEventTriggerRequest$Outbound = {
  triggerId: string;
  body: models.PatchEventTriggerRequest$Outbound;
};

/** @internal */
export const UpdateEventTriggerRequest$outboundSchema: z.ZodMiniType<
  UpdateEventTriggerRequest$Outbound,
  UpdateEventTriggerRequest
> = z.object({
  triggerId: z.string(),
  body: models.PatchEventTriggerRequest$outboundSchema,
});

export function updateEventTriggerRequestToJSON(
  updateEventTriggerRequest: UpdateEventTriggerRequest,
): string {
  return JSON.stringify(
    UpdateEventTriggerRequest$outboundSchema.parse(updateEventTriggerRequest),
  );
}

/** @internal */
export const UpdateEventTriggerSourceType$inboundSchema: z.ZodMiniEnum<
  typeof UpdateEventTriggerSourceType
> = z.enum(UpdateEventTriggerSourceType);

/** @internal */
export const UpdateEventTriggerEventType$inboundSchema: z.ZodMiniType<
  UpdateEventTriggerEventType,
  unknown
> = openEnums.inboundSchema(UpdateEventTriggerEventType);

/** @internal */
export const UpdateEventTriggerSourceConfig$inboundSchema: z.ZodMiniType<
  UpdateEventTriggerSourceConfig,
  unknown
> = z.object({
  eventTypes: z.array(UpdateEventTriggerEventType$inboundSchema),
  includePreReleases: z._default(types.boolean(), true),
});

export function updateEventTriggerSourceConfigFromJSON(
  jsonString: string,
): SafeParseResult<UpdateEventTriggerSourceConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateEventTriggerSourceConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateEventTriggerSourceConfig' from JSON`,
  );
}

/** @internal */
export const UpdateEventTriggerTargets$inboundSchema: z.ZodMiniType<
  UpdateEventTriggerTargets,
  unknown
> = z.object({
  repositoryIds: z.array(types.string()),
});

export function updateEventTriggerTargetsFromJSON(
  jsonString: string,
): SafeParseResult<UpdateEventTriggerTargets, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateEventTriggerTargets$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateEventTriggerTargets' from JSON`,
  );
}

/** @internal */
export const UpdateEventTriggerOutputType$inboundSchema: z.ZodMiniType<
  UpdateEventTriggerOutputType,
  unknown
> = openEnums.inboundSchema(UpdateEventTriggerOutputType);

/** @internal */
export const UpdateEventTriggerPublishDestination$inboundSchema: z.ZodMiniType<
  UpdateEventTriggerPublishDestination,
  unknown
> = openEnums.inboundSchema(UpdateEventTriggerPublishDestination);

/** @internal */
export const UpdateEventTriggerOutputConfig$inboundSchema: z.ZodMiniType<
  UpdateEventTriggerOutputConfig,
  unknown
> = z.object({
  publishDestination: types.optional(
    UpdateEventTriggerPublishDestination$inboundSchema,
  ),
  brandVoiceId: types.optional(types.string()),
});

export function updateEventTriggerOutputConfigFromJSON(
  jsonString: string,
): SafeParseResult<UpdateEventTriggerOutputConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateEventTriggerOutputConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateEventTriggerOutputConfig' from JSON`,
  );
}

/** @internal */
export const UpdateEventTriggerEventTrigger$inboundSchema: z.ZodMiniType<
  UpdateEventTriggerEventTrigger,
  unknown
> = z.object({
  id: types.string(),
  organizationId: types.string(),
  name: types.string(),
  sourceType: UpdateEventTriggerSourceType$inboundSchema,
  sourceConfig: z.lazy(() => UpdateEventTriggerSourceConfig$inboundSchema),
  targets: z.lazy(() => UpdateEventTriggerTargets$inboundSchema),
  outputType: UpdateEventTriggerOutputType$inboundSchema,
  outputConfig: z.optional(
    z.nullable(z.lazy(() => UpdateEventTriggerOutputConfig$inboundSchema)),
  ),
  enabled: types.boolean(),
  autoPublish: types.boolean(),
  createdAt: types.string(),
  updatedAt: types.string(),
});

export function updateEventTriggerEventTriggerFromJSON(
  jsonString: string,
): SafeParseResult<UpdateEventTriggerEventTrigger, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateEventTriggerEventTrigger$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateEventTriggerEventTrigger' from JSON`,
  );
}

/** @internal */
export const UpdateEventTriggerOrganization$inboundSchema: z.ZodMiniType<
  UpdateEventTriggerOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function updateEventTriggerOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<UpdateEventTriggerOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateEventTriggerOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateEventTriggerOrganization' from JSON`,
  );
}

/** @internal */
export const UpdateEventTriggerResponse$inboundSchema: z.ZodMiniType<
  UpdateEventTriggerResponse,
  unknown
> = z.object({
  eventTrigger: z.lazy(() => UpdateEventTriggerEventTrigger$inboundSchema),
  organization: z.lazy(() => UpdateEventTriggerOrganization$inboundSchema),
});

export function updateEventTriggerResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateEventTriggerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateEventTriggerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateEventTriggerResponse' from JSON`,
  );
}
