/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ca5a5edf4af7
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const StatusRequest = {
  Draft: "draft",
  Published: "published",
} as const;
export type StatusRequest = ClosedEnum<typeof StatusRequest>;

export type UpdatePostRequestBody = {
  title?: string | undefined;
  slug?: string | null | undefined;
  markdown?: string | undefined;
  status?: StatusRequest | undefined;
};

export type UpdatePostRequest = {
  postId: string;
  body: UpdatePostRequestBody;
};

export type UpdatePostOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export const UpdatePostPostStatus = {
  Draft: "draft",
  Published: "published",
} as const;
export type UpdatePostPostStatus = OpenEnum<typeof UpdatePostPostStatus>;

export type UpdatePostPost = {
  id: string;
  title: string;
  slug: string | null;
  content: string;
  markdown: string;
  recommendations: string | null;
  contentType: string;
  sourceMetadata?: any | undefined;
  status: UpdatePostPostStatus;
  createdAt: string;
  updatedAt: string;
};

/**
 * Post updated successfully
 */
export type UpdatePostResponse = {
  organization: UpdatePostOrganization;
  post: UpdatePostPost;
};

/** @internal */
export const StatusRequest$outboundSchema: z.ZodMiniEnum<typeof StatusRequest> =
  z.enum(StatusRequest);

/** @internal */
export type UpdatePostRequestBody$Outbound = {
  title?: string | undefined;
  slug?: string | null | undefined;
  markdown?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const UpdatePostRequestBody$outboundSchema: z.ZodMiniType<
  UpdatePostRequestBody$Outbound,
  UpdatePostRequestBody
> = z.object({
  title: z.optional(z.string()),
  slug: z.optional(z.nullable(z.string())),
  markdown: z.optional(z.string()),
  status: z.optional(StatusRequest$outboundSchema),
});

export function updatePostRequestBodyToJSON(
  updatePostRequestBody: UpdatePostRequestBody,
): string {
  return JSON.stringify(
    UpdatePostRequestBody$outboundSchema.parse(updatePostRequestBody),
  );
}

/** @internal */
export type UpdatePostRequest$Outbound = {
  postId: string;
  body: UpdatePostRequestBody$Outbound;
};

/** @internal */
export const UpdatePostRequest$outboundSchema: z.ZodMiniType<
  UpdatePostRequest$Outbound,
  UpdatePostRequest
> = z.object({
  postId: z.string(),
  body: z.lazy(() => UpdatePostRequestBody$outboundSchema),
});

export function updatePostRequestToJSON(
  updatePostRequest: UpdatePostRequest,
): string {
  return JSON.stringify(
    UpdatePostRequest$outboundSchema.parse(updatePostRequest),
  );
}

/** @internal */
export const UpdatePostOrganization$inboundSchema: z.ZodMiniType<
  UpdatePostOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function updatePostOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePostOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePostOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePostOrganization' from JSON`,
  );
}

/** @internal */
export const UpdatePostPostStatus$inboundSchema: z.ZodMiniType<
  UpdatePostPostStatus,
  unknown
> = openEnums.inboundSchema(UpdatePostPostStatus);

/** @internal */
export const UpdatePostPost$inboundSchema: z.ZodMiniType<
  UpdatePostPost,
  unknown
> = z.object({
  id: types.string(),
  title: types.string(),
  slug: types.nullable(types.string()),
  content: types.string(),
  markdown: types.string(),
  recommendations: types.nullable(types.string()),
  contentType: types.string(),
  sourceMetadata: types.optional(z.any()),
  status: UpdatePostPostStatus$inboundSchema,
  createdAt: types.string(),
  updatedAt: types.string(),
});

export function updatePostPostFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePostPost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePostPost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePostPost' from JSON`,
  );
}

/** @internal */
export const UpdatePostResponse$inboundSchema: z.ZodMiniType<
  UpdatePostResponse,
  unknown
> = z.object({
  organization: z.lazy(() => UpdatePostOrganization$inboundSchema),
  post: z.lazy(() => UpdatePostPost$inboundSchema),
});

export function updatePostResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePostResponse' from JSON`,
  );
}
