/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 86622f6a610f
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const UpdateScheduleSourceTypeRequest = {
  Cron: "cron",
} as const;
export type UpdateScheduleSourceTypeRequest = ClosedEnum<
  typeof UpdateScheduleSourceTypeRequest
>;

export const UpdateScheduleFrequencyRequest = {
  Daily: "daily",
  Weekly: "weekly",
  Monthly: "monthly",
} as const;
export type UpdateScheduleFrequencyRequest = ClosedEnum<
  typeof UpdateScheduleFrequencyRequest
>;

export type UpdateScheduleCronRequest = {
  frequency: UpdateScheduleFrequencyRequest;
  hour: number;
  minute: number;
  dayOfWeek?: number | undefined;
  dayOfMonth?: number | undefined;
};

export type UpdateScheduleSourceConfigRequest = {
  cron: UpdateScheduleCronRequest;
};

export type UpdateScheduleTargetsRequest = {
  repositoryIds: Array<string>;
};

export const UpdateScheduleOutputTypeRequest = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
} as const;
export type UpdateScheduleOutputTypeRequest = ClosedEnum<
  typeof UpdateScheduleOutputTypeRequest
>;

export const UpdateSchedulePublishDestinationRequest = {
  Webflow: "webflow",
  Framer: "framer",
  Custom: "custom",
} as const;
export type UpdateSchedulePublishDestinationRequest = ClosedEnum<
  typeof UpdateSchedulePublishDestinationRequest
>;

export type UpdateScheduleOutputConfigRequest = {
  publishDestination?: UpdateSchedulePublishDestinationRequest | undefined;
  brandVoiceId?: string | undefined;
};

export const UpdateScheduleLookbackWindowRequest = {
  CurrentDay: "current_day",
  Yesterday: "yesterday",
  Last7Days: "last_7_days",
  Last14Days: "last_14_days",
  Last30Days: "last_30_days",
} as const;
export type UpdateScheduleLookbackWindowRequest = ClosedEnum<
  typeof UpdateScheduleLookbackWindowRequest
>;

export type UpdateScheduleRequestBody = {
  name: string;
  sourceType: UpdateScheduleSourceTypeRequest;
  sourceConfig: UpdateScheduleSourceConfigRequest;
  targets: UpdateScheduleTargetsRequest;
  outputType: UpdateScheduleOutputTypeRequest;
  outputConfig?: UpdateScheduleOutputConfigRequest | undefined;
  enabled: boolean;
  autoPublish?: boolean | undefined;
  lookbackWindow?: UpdateScheduleLookbackWindowRequest | undefined;
};

export type UpdateScheduleRequest = {
  scheduleId: string;
  body: UpdateScheduleRequestBody;
};

export const UpdateScheduleSourceTypeResponse = {
  Cron: "cron",
} as const;
export type UpdateScheduleSourceTypeResponse = ClosedEnum<
  typeof UpdateScheduleSourceTypeResponse
>;

export const UpdateScheduleFrequencyResponse = {
  Daily: "daily",
  Weekly: "weekly",
  Monthly: "monthly",
} as const;
export type UpdateScheduleFrequencyResponse = OpenEnum<
  typeof UpdateScheduleFrequencyResponse
>;

export type UpdateScheduleCronResponse = {
  frequency: UpdateScheduleFrequencyResponse;
  hour: number;
  minute: number;
  dayOfWeek?: number | undefined;
  dayOfMonth?: number | undefined;
};

export type UpdateScheduleSourceConfigResponse = {
  cron: UpdateScheduleCronResponse;
};

export type UpdateScheduleTargetsResponse = {
  repositoryIds: Array<string>;
};

export const UpdateScheduleOutputTypeResponse = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
} as const;
export type UpdateScheduleOutputTypeResponse = OpenEnum<
  typeof UpdateScheduleOutputTypeResponse
>;

export const UpdateSchedulePublishDestinationResponse = {
  Webflow: "webflow",
  Framer: "framer",
  Custom: "custom",
} as const;
export type UpdateSchedulePublishDestinationResponse = OpenEnum<
  typeof UpdateSchedulePublishDestinationResponse
>;

export type UpdateScheduleOutputConfigResponse = {
  publishDestination?: UpdateSchedulePublishDestinationResponse | undefined;
  brandVoiceId?: string | undefined;
};

export const UpdateScheduleLookbackWindowResponse = {
  CurrentDay: "current_day",
  Yesterday: "yesterday",
  Last7Days: "last_7_days",
  Last14Days: "last_14_days",
  Last30Days: "last_30_days",
} as const;
export type UpdateScheduleLookbackWindowResponse = OpenEnum<
  typeof UpdateScheduleLookbackWindowResponse
>;

export type UpdateScheduleSchedule = {
  id: string;
  organizationId: string;
  name: string;
  sourceType: UpdateScheduleSourceTypeResponse;
  sourceConfig: UpdateScheduleSourceConfigResponse;
  targets: UpdateScheduleTargetsResponse;
  outputType: UpdateScheduleOutputTypeResponse;
  outputConfig?: UpdateScheduleOutputConfigResponse | null | undefined;
  enabled: boolean;
  autoPublish: boolean;
  createdAt: string;
  updatedAt: string;
  lookbackWindow: UpdateScheduleLookbackWindowResponse;
};

export type UpdateScheduleOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

/**
 * Schedule updated successfully
 */
export type UpdateScheduleResponse = {
  schedule: UpdateScheduleSchedule;
  organization: UpdateScheduleOrganization;
};

/** @internal */
export const UpdateScheduleSourceTypeRequest$outboundSchema: z.ZodMiniEnum<
  typeof UpdateScheduleSourceTypeRequest
> = z.enum(UpdateScheduleSourceTypeRequest);

/** @internal */
export const UpdateScheduleFrequencyRequest$outboundSchema: z.ZodMiniEnum<
  typeof UpdateScheduleFrequencyRequest
> = z.enum(UpdateScheduleFrequencyRequest);

/** @internal */
export type UpdateScheduleCronRequest$Outbound = {
  frequency: string;
  hour: number;
  minute: number;
  dayOfWeek?: number | undefined;
  dayOfMonth?: number | undefined;
};

/** @internal */
export const UpdateScheduleCronRequest$outboundSchema: z.ZodMiniType<
  UpdateScheduleCronRequest$Outbound,
  UpdateScheduleCronRequest
> = z.object({
  frequency: UpdateScheduleFrequencyRequest$outboundSchema,
  hour: z.int(),
  minute: z.int(),
  dayOfWeek: z.optional(z.int()),
  dayOfMonth: z.optional(z.int()),
});

export function updateScheduleCronRequestToJSON(
  updateScheduleCronRequest: UpdateScheduleCronRequest,
): string {
  return JSON.stringify(
    UpdateScheduleCronRequest$outboundSchema.parse(updateScheduleCronRequest),
  );
}

/** @internal */
export type UpdateScheduleSourceConfigRequest$Outbound = {
  cron: UpdateScheduleCronRequest$Outbound;
};

/** @internal */
export const UpdateScheduleSourceConfigRequest$outboundSchema: z.ZodMiniType<
  UpdateScheduleSourceConfigRequest$Outbound,
  UpdateScheduleSourceConfigRequest
> = z.object({
  cron: z.lazy(() => UpdateScheduleCronRequest$outboundSchema),
});

export function updateScheduleSourceConfigRequestToJSON(
  updateScheduleSourceConfigRequest: UpdateScheduleSourceConfigRequest,
): string {
  return JSON.stringify(
    UpdateScheduleSourceConfigRequest$outboundSchema.parse(
      updateScheduleSourceConfigRequest,
    ),
  );
}

/** @internal */
export type UpdateScheduleTargetsRequest$Outbound = {
  repositoryIds: Array<string>;
};

/** @internal */
export const UpdateScheduleTargetsRequest$outboundSchema: z.ZodMiniType<
  UpdateScheduleTargetsRequest$Outbound,
  UpdateScheduleTargetsRequest
> = z.object({
  repositoryIds: z.array(z.string()),
});

export function updateScheduleTargetsRequestToJSON(
  updateScheduleTargetsRequest: UpdateScheduleTargetsRequest,
): string {
  return JSON.stringify(
    UpdateScheduleTargetsRequest$outboundSchema.parse(
      updateScheduleTargetsRequest,
    ),
  );
}

/** @internal */
export const UpdateScheduleOutputTypeRequest$outboundSchema: z.ZodMiniEnum<
  typeof UpdateScheduleOutputTypeRequest
> = z.enum(UpdateScheduleOutputTypeRequest);

/** @internal */
export const UpdateSchedulePublishDestinationRequest$outboundSchema:
  z.ZodMiniEnum<typeof UpdateSchedulePublishDestinationRequest> = z.enum(
    UpdateSchedulePublishDestinationRequest,
  );

/** @internal */
export type UpdateScheduleOutputConfigRequest$Outbound = {
  publishDestination?: string | undefined;
  brandVoiceId?: string | undefined;
};

/** @internal */
export const UpdateScheduleOutputConfigRequest$outboundSchema: z.ZodMiniType<
  UpdateScheduleOutputConfigRequest$Outbound,
  UpdateScheduleOutputConfigRequest
> = z.object({
  publishDestination: z.optional(
    UpdateSchedulePublishDestinationRequest$outboundSchema,
  ),
  brandVoiceId: z.optional(z.string()),
});

export function updateScheduleOutputConfigRequestToJSON(
  updateScheduleOutputConfigRequest: UpdateScheduleOutputConfigRequest,
): string {
  return JSON.stringify(
    UpdateScheduleOutputConfigRequest$outboundSchema.parse(
      updateScheduleOutputConfigRequest,
    ),
  );
}

/** @internal */
export const UpdateScheduleLookbackWindowRequest$outboundSchema: z.ZodMiniEnum<
  typeof UpdateScheduleLookbackWindowRequest
> = z.enum(UpdateScheduleLookbackWindowRequest);

/** @internal */
export type UpdateScheduleRequestBody$Outbound = {
  name: string;
  sourceType: string;
  sourceConfig: UpdateScheduleSourceConfigRequest$Outbound;
  targets: UpdateScheduleTargetsRequest$Outbound;
  outputType: string;
  outputConfig?: UpdateScheduleOutputConfigRequest$Outbound | undefined;
  enabled: boolean;
  autoPublish: boolean;
  lookbackWindow: string;
};

/** @internal */
export const UpdateScheduleRequestBody$outboundSchema: z.ZodMiniType<
  UpdateScheduleRequestBody$Outbound,
  UpdateScheduleRequestBody
> = z.object({
  name: z.string(),
  sourceType: UpdateScheduleSourceTypeRequest$outboundSchema,
  sourceConfig: z.lazy(() => UpdateScheduleSourceConfigRequest$outboundSchema),
  targets: z.lazy(() => UpdateScheduleTargetsRequest$outboundSchema),
  outputType: UpdateScheduleOutputTypeRequest$outboundSchema,
  outputConfig: z.optional(
    z.lazy(() => UpdateScheduleOutputConfigRequest$outboundSchema),
  ),
  enabled: z.boolean(),
  autoPublish: z._default(z.boolean(), false),
  lookbackWindow: z._default(
    UpdateScheduleLookbackWindowRequest$outboundSchema,
    "last_7_days",
  ),
});

export function updateScheduleRequestBodyToJSON(
  updateScheduleRequestBody: UpdateScheduleRequestBody,
): string {
  return JSON.stringify(
    UpdateScheduleRequestBody$outboundSchema.parse(updateScheduleRequestBody),
  );
}

/** @internal */
export type UpdateScheduleRequest$Outbound = {
  scheduleId: string;
  body: UpdateScheduleRequestBody$Outbound;
};

/** @internal */
export const UpdateScheduleRequest$outboundSchema: z.ZodMiniType<
  UpdateScheduleRequest$Outbound,
  UpdateScheduleRequest
> = z.object({
  scheduleId: z.string(),
  body: z.lazy(() => UpdateScheduleRequestBody$outboundSchema),
});

export function updateScheduleRequestToJSON(
  updateScheduleRequest: UpdateScheduleRequest,
): string {
  return JSON.stringify(
    UpdateScheduleRequest$outboundSchema.parse(updateScheduleRequest),
  );
}

/** @internal */
export const UpdateScheduleSourceTypeResponse$inboundSchema: z.ZodMiniEnum<
  typeof UpdateScheduleSourceTypeResponse
> = z.enum(UpdateScheduleSourceTypeResponse);

/** @internal */
export const UpdateScheduleFrequencyResponse$inboundSchema: z.ZodMiniType<
  UpdateScheduleFrequencyResponse,
  unknown
> = openEnums.inboundSchema(UpdateScheduleFrequencyResponse);

/** @internal */
export const UpdateScheduleCronResponse$inboundSchema: z.ZodMiniType<
  UpdateScheduleCronResponse,
  unknown
> = z.object({
  frequency: UpdateScheduleFrequencyResponse$inboundSchema,
  hour: types.number(),
  minute: types.number(),
  dayOfWeek: types.optional(types.number()),
  dayOfMonth: types.optional(types.number()),
});

export function updateScheduleCronResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateScheduleCronResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateScheduleCronResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateScheduleCronResponse' from JSON`,
  );
}

/** @internal */
export const UpdateScheduleSourceConfigResponse$inboundSchema: z.ZodMiniType<
  UpdateScheduleSourceConfigResponse,
  unknown
> = z.object({
  cron: z.lazy(() => UpdateScheduleCronResponse$inboundSchema),
});

export function updateScheduleSourceConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateScheduleSourceConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateScheduleSourceConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateScheduleSourceConfigResponse' from JSON`,
  );
}

/** @internal */
export const UpdateScheduleTargetsResponse$inboundSchema: z.ZodMiniType<
  UpdateScheduleTargetsResponse,
  unknown
> = z.object({
  repositoryIds: z.array(types.string()),
});

export function updateScheduleTargetsResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateScheduleTargetsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateScheduleTargetsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateScheduleTargetsResponse' from JSON`,
  );
}

/** @internal */
export const UpdateScheduleOutputTypeResponse$inboundSchema: z.ZodMiniType<
  UpdateScheduleOutputTypeResponse,
  unknown
> = openEnums.inboundSchema(UpdateScheduleOutputTypeResponse);

/** @internal */
export const UpdateSchedulePublishDestinationResponse$inboundSchema:
  z.ZodMiniType<UpdateSchedulePublishDestinationResponse, unknown> = openEnums
    .inboundSchema(UpdateSchedulePublishDestinationResponse);

/** @internal */
export const UpdateScheduleOutputConfigResponse$inboundSchema: z.ZodMiniType<
  UpdateScheduleOutputConfigResponse,
  unknown
> = z.object({
  publishDestination: types.optional(
    UpdateSchedulePublishDestinationResponse$inboundSchema,
  ),
  brandVoiceId: types.optional(types.string()),
});

export function updateScheduleOutputConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateScheduleOutputConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateScheduleOutputConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateScheduleOutputConfigResponse' from JSON`,
  );
}

/** @internal */
export const UpdateScheduleLookbackWindowResponse$inboundSchema: z.ZodMiniType<
  UpdateScheduleLookbackWindowResponse,
  unknown
> = openEnums.inboundSchema(UpdateScheduleLookbackWindowResponse);

/** @internal */
export const UpdateScheduleSchedule$inboundSchema: z.ZodMiniType<
  UpdateScheduleSchedule,
  unknown
> = z.object({
  id: types.string(),
  organizationId: types.string(),
  name: types.string(),
  sourceType: UpdateScheduleSourceTypeResponse$inboundSchema,
  sourceConfig: z.lazy(() => UpdateScheduleSourceConfigResponse$inboundSchema),
  targets: z.lazy(() => UpdateScheduleTargetsResponse$inboundSchema),
  outputType: UpdateScheduleOutputTypeResponse$inboundSchema,
  outputConfig: z.optional(
    z.nullable(z.lazy(() => UpdateScheduleOutputConfigResponse$inboundSchema)),
  ),
  enabled: types.boolean(),
  autoPublish: types.boolean(),
  createdAt: types.string(),
  updatedAt: types.string(),
  lookbackWindow: UpdateScheduleLookbackWindowResponse$inboundSchema,
});

export function updateScheduleScheduleFromJSON(
  jsonString: string,
): SafeParseResult<UpdateScheduleSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateScheduleSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateScheduleSchedule' from JSON`,
  );
}

/** @internal */
export const UpdateScheduleOrganization$inboundSchema: z.ZodMiniType<
  UpdateScheduleOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function updateScheduleOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<UpdateScheduleOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateScheduleOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateScheduleOrganization' from JSON`,
  );
}

/** @internal */
export const UpdateScheduleResponse$inboundSchema: z.ZodMiniType<
  UpdateScheduleResponse,
  unknown
> = z.object({
  schedule: z.lazy(() => UpdateScheduleSchedule$inboundSchema),
  organization: z.lazy(() => UpdateScheduleOrganization$inboundSchema),
});

export function updateScheduleResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateScheduleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateScheduleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateScheduleResponse' from JSON`,
  );
}
