/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7b961ce4eb28
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateGeoSequenceRequest = {
  projectId: string;
  sequenceId: string;
  body: models.PatchGeoSequenceRequest;
};

/** @internal */
export type UpdateGeoSequenceRequest$Outbound = {
  projectId: string;
  sequenceId: string;
  body: models.PatchGeoSequenceRequest$Outbound;
};

/** @internal */
export const UpdateGeoSequenceRequest$outboundSchema: z.ZodMiniType<
  UpdateGeoSequenceRequest$Outbound,
  UpdateGeoSequenceRequest
> = z.object({
  projectId: z.string(),
  sequenceId: z.string(),
  body: models.PatchGeoSequenceRequest$outboundSchema,
});

export function updateGeoSequenceRequestToJSON(
  updateGeoSequenceRequest: UpdateGeoSequenceRequest,
): string {
  return JSON.stringify(
    UpdateGeoSequenceRequest$outboundSchema.parse(updateGeoSequenceRequest),
  );
}
