/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 84cadfab3947
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpsertGeoCompetitorRequest = {
  projectId: string;
  body: models.PutGeoCompetitorRequest;
};

/** @internal */
export type UpsertGeoCompetitorRequest$Outbound = {
  projectId: string;
  body: models.PutGeoCompetitorRequest$Outbound;
};

/** @internal */
export const UpsertGeoCompetitorRequest$outboundSchema: z.ZodMiniType<
  UpsertGeoCompetitorRequest$Outbound,
  UpsertGeoCompetitorRequest
> = z.object({
  projectId: z.string(),
  body: models.PutGeoCompetitorRequest$outboundSchema,
});

export function upsertGeoCompetitorRequestToJSON(
  upsertGeoCompetitorRequest: UpsertGeoCompetitorRequest,
): string {
  return JSON.stringify(
    UpsertGeoCompetitorRequest$outboundSchema.parse(upsertGeoCompetitorRequest),
  );
}
