/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7ab94ea07a5b
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AgentSessionSummary = {
  sessionId: string;
  chatId: string | null;
  surface: string;
  status: string;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const AgentSessionSummary$inboundSchema: z.ZodMiniType<
  AgentSessionSummary,
  unknown
> = z.object({
  sessionId: types.string(),
  chatId: types.nullable(types.string()),
  surface: types.string(),
  status: types.string(),
  createdAt: types.string(),
  updatedAt: types.string(),
});

export function agentSessionSummaryFromJSON(
  jsonString: string,
): SafeParseResult<AgentSessionSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentSessionSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentSessionSummary' from JSON`,
  );
}
