/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 18ae023f798e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApproveGeoContentBriefResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type ApproveGeoContentBriefResponse = {
  runId: string;
  organization: ApproveGeoContentBriefResponseOrganization;
};

/** @internal */
export const ApproveGeoContentBriefResponseOrganization$inboundSchema:
  z.ZodMiniType<ApproveGeoContentBriefResponseOrganization, unknown> = z.object(
    {
      id: types.string(),
      slug: types.string(),
      name: types.string(),
      logo: types.nullable(types.string()),
    },
  );

export function approveGeoContentBriefResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApproveGeoContentBriefResponseOrganization,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApproveGeoContentBriefResponseOrganization$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApproveGeoContentBriefResponseOrganization' from JSON`,
  );
}

/** @internal */
export const ApproveGeoContentBriefResponse$inboundSchema: z.ZodMiniType<
  ApproveGeoContentBriefResponse,
  unknown
> = z.object({
  runId: types.string(),
  organization: z.lazy(() =>
    ApproveGeoContentBriefResponseOrganization$inboundSchema
  ),
});

export function approveGeoContentBriefResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApproveGeoContentBriefResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApproveGeoContentBriefResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApproveGeoContentBriefResponse' from JSON`,
  );
}
