/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 17665be83197
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ExternalChannelId,
  ExternalChannelId$inboundSchema,
} from "./external-channel-id.js";

export type ChatSessionSummary = {
  chatId: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  pinnedAt: string | null;
  externalChannelId?: ExternalChannelId | null | undefined;
};

/** @internal */
export const ChatSessionSummary$inboundSchema: z.ZodMiniType<
  ChatSessionSummary,
  unknown
> = z.object({
  chatId: types.string(),
  title: types.string(),
  createdAt: types.string(),
  updatedAt: types.string(),
  pinnedAt: types.nullable(types.string()),
  externalChannelId: z.optional(z.nullable(ExternalChannelId$inboundSchema)),
});

export function chatSessionSummaryFromJSON(
  jsonString: string,
): SafeParseResult<ChatSessionSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatSessionSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatSessionSummary' from JSON`,
  );
}
