/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9e50dcaaefd8
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Skill, Skill$inboundSchema } from "./skill.js";

export type CreateSkillResponse = {
  skill: Skill;
};

/** @internal */
export const CreateSkillResponse$inboundSchema: z.ZodMiniType<
  CreateSkillResponse,
  unknown
> = z.object({
  skill: Skill$inboundSchema,
});

export function createSkillResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSkillResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSkillResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSkillResponse' from JSON`,
  );
}
