/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fbca6261ca44
 */

import * as z from "zod/v4-mini";

export type CreateGeoProjectRequest = {
  name: string;
  /**
   * Brand identity to link. Defaults to the organization's default identity.
   */
  brandSettingsId?: string | undefined;
};

/** @internal */
export type CreateGeoProjectRequest$Outbound = {
  name: string;
  brandSettingsId?: string | undefined;
};

/** @internal */
export const CreateGeoProjectRequest$outboundSchema: z.ZodMiniType<
  CreateGeoProjectRequest$Outbound,
  CreateGeoProjectRequest
> = z.object({
  name: z.string(),
  brandSettingsId: z.optional(z.string()),
});

export function createGeoProjectRequestToJSON(
  createGeoProjectRequest: CreateGeoProjectRequest,
): string {
  return JSON.stringify(
    CreateGeoProjectRequest$outboundSchema.parse(createGeoProjectRequest),
  );
}
