/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d5797d4bdb20
 */

import * as z from "zod/v4-mini";

export type CreateGeoPromptRequest = {
  prompt: string;
};

/** @internal */
export type CreateGeoPromptRequest$Outbound = {
  prompt: string;
};

/** @internal */
export const CreateGeoPromptRequest$outboundSchema: z.ZodMiniType<
  CreateGeoPromptRequest$Outbound,
  CreateGeoPromptRequest
> = z.object({
  prompt: z.string(),
});

export function createGeoPromptRequestToJSON(
  createGeoPromptRequest: CreateGeoPromptRequest,
): string {
  return JSON.stringify(
    CreateGeoPromptRequest$outboundSchema.parse(createGeoPromptRequest),
  );
}
