/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f53c10db0d9d
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type CreateGeoScanResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type CreateGeoScanResponse = {
  scanId: string;
  statusUrl: string;
  organization: CreateGeoScanResponseOrganization;
};

/** @internal */
export const CreateGeoScanResponseOrganization$inboundSchema: z.ZodMiniType<
  CreateGeoScanResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function createGeoScanResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<CreateGeoScanResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGeoScanResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGeoScanResponseOrganization' from JSON`,
  );
}

/** @internal */
export const CreateGeoScanResponse$inboundSchema: z.ZodMiniType<
  CreateGeoScanResponse,
  unknown
> = z.object({
  scanId: types.string(),
  statusUrl: types.string(),
  organization: z.lazy(() => CreateGeoScanResponseOrganization$inboundSchema),
});

export function createGeoScanResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateGeoScanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGeoScanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGeoScanResponse' from JSON`,
  );
}
