/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a1855d659407
 */

import * as z from "zod/v4-mini";

export type CreateSkillRequest = {
  /**
   * Skill name. Lowercase letters, digits, and hyphens only.
   */
  name: string;
  /**
   * Short description of when the skill should be used.
   */
  description: string;
  /**
   * Full skill instructions, typically Markdown.
   */
  content: string;
};

/** @internal */
export type CreateSkillRequest$Outbound = {
  name: string;
  description: string;
  content: string;
};

/** @internal */
export const CreateSkillRequest$outboundSchema: z.ZodMiniType<
  CreateSkillRequest$Outbound,
  CreateSkillRequest
> = z.object({
  name: z.string(),
  description: z.string(),
  content: z.string(),
});

export function createSkillRequestToJSON(
  createSkillRequest: CreateSkillRequest,
): string {
  return JSON.stringify(
    CreateSkillRequest$outboundSchema.parse(createSkillRequest),
  );
}
