/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6d3522971c6e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DeleteGeoPromptResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type DeleteGeoPromptResponse = {
  id: string;
  organization: DeleteGeoPromptResponseOrganization;
};

/** @internal */
export const DeleteGeoPromptResponseOrganization$inboundSchema: z.ZodMiniType<
  DeleteGeoPromptResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function deleteGeoPromptResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<DeleteGeoPromptResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteGeoPromptResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteGeoPromptResponseOrganization' from JSON`,
  );
}

/** @internal */
export const DeleteGeoPromptResponse$inboundSchema: z.ZodMiniType<
  DeleteGeoPromptResponse,
  unknown
> = z.object({
  id: types.string(),
  organization: z.lazy(() => DeleteGeoPromptResponseOrganization$inboundSchema),
});

export function deleteGeoPromptResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteGeoPromptResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteGeoPromptResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteGeoPromptResponse' from JSON`,
  );
}
