/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ccdbac684933
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type GeoSettings = {
  id: string;
  organizationId: string;
  projectId: string;
  companyName: string;
  aliases: Array<string>;
  conversionPaths: Array<string>;
  competitors: Array<string>;
  languages: Array<string>;
  engines: Array<string>;
  enforceZdr: boolean;
  nonZdrApprovedEngines: Array<string>;
  pausedAutoPromptIds: Array<string>;
  removedAutoPromptIds: Array<string>;
  enabled: boolean;
  scanIntervalHours: number;
  scanStartedAt: string | null;
  lastScanAt: string | null;
  isScanning: boolean;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const GeoSettings$inboundSchema: z.ZodMiniType<GeoSettings, unknown> = z
  .object({
    id: types.string(),
    organizationId: types.string(),
    projectId: types.string(),
    companyName: types.string(),
    aliases: z.array(types.string()),
    conversionPaths: z.array(types.string()),
    competitors: z.array(types.string()),
    languages: z.array(types.string()),
    engines: z.array(types.string()),
    enforceZdr: types.boolean(),
    nonZdrApprovedEngines: z.array(types.string()),
    pausedAutoPromptIds: z.array(types.string()),
    removedAutoPromptIds: z.array(types.string()),
    enabled: types.boolean(),
    scanIntervalHours: types.number(),
    scanStartedAt: types.nullable(types.string()),
    lastScanAt: types.nullable(types.string()),
    isScanning: types.boolean(),
    createdAt: types.string(),
    updatedAt: types.string(),
  });

export function geoSettingsFromJSON(
  jsonString: string,
): SafeParseResult<GeoSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoSettings' from JSON`,
  );
}
