/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b1d6a43202af
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GeoSentimentAnalysisResponseStatus = {
  Ready: "ready",
  Pending: "pending",
  Stale: "stale",
  Failed: "failed",
  Unavailable: "unavailable",
} as const;
export type GeoSentimentAnalysisResponseStatus = OpenEnum<
  typeof GeoSentimentAnalysisResponseStatus
>;

export const Polarity = {
  Positive: "positive",
  Negative: "negative",
} as const;
export type Polarity = OpenEnum<typeof Polarity>;

export type ClaimEvidence = {
  checkId: string;
  quote: string;
  prompt: string;
  engine: string;
  capturedAt: string;
};

export type Claim = {
  statement: string;
  evidence: Array<ClaimEvidence>;
};

export type GeoSentimentAnalysisResponseEvidence = {
  checkId: string;
  quote: string;
  prompt: string;
  engine: string;
  capturedAt: string;
};

export type Theme = {
  title: string;
  polarity: Polarity;
  claims: Array<Claim>;
  evidence: Array<GeoSentimentAnalysisResponseEvidence>;
};

export type GeoSentimentAnalysisResponseResult = {
  fingerprint: string;
  generatedAt: string;
  sampled: number;
  eligible: number;
  themes: Array<Theme>;
};

export type GeoSentimentAnalysisResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoSentimentAnalysisResponse = {
  status: GeoSentimentAnalysisResponseStatus;
  result: GeoSentimentAnalysisResponseResult | null;
  message: string | null;
  organization: GeoSentimentAnalysisResponseOrganization;
};

/** @internal */
export const GeoSentimentAnalysisResponseStatus$inboundSchema: z.ZodMiniType<
  GeoSentimentAnalysisResponseStatus,
  unknown
> = openEnums.inboundSchema(GeoSentimentAnalysisResponseStatus);

/** @internal */
export const Polarity$inboundSchema: z.ZodMiniType<Polarity, unknown> =
  openEnums.inboundSchema(Polarity);

/** @internal */
export const ClaimEvidence$inboundSchema: z.ZodMiniType<
  ClaimEvidence,
  unknown
> = z.object({
  checkId: types.string(),
  quote: types.string(),
  prompt: types.string(),
  engine: types.string(),
  capturedAt: types.string(),
});

export function claimEvidenceFromJSON(
  jsonString: string,
): SafeParseResult<ClaimEvidence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClaimEvidence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClaimEvidence' from JSON`,
  );
}

/** @internal */
export const Claim$inboundSchema: z.ZodMiniType<Claim, unknown> = z.object({
  statement: types.string(),
  evidence: z.array(z.lazy(() => ClaimEvidence$inboundSchema)),
});

export function claimFromJSON(
  jsonString: string,
): SafeParseResult<Claim, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Claim$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Claim' from JSON`,
  );
}

/** @internal */
export const GeoSentimentAnalysisResponseEvidence$inboundSchema: z.ZodMiniType<
  GeoSentimentAnalysisResponseEvidence,
  unknown
> = z.object({
  checkId: types.string(),
  quote: types.string(),
  prompt: types.string(),
  engine: types.string(),
  capturedAt: types.string(),
});

export function geoSentimentAnalysisResponseEvidenceFromJSON(
  jsonString: string,
): SafeParseResult<GeoSentimentAnalysisResponseEvidence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeoSentimentAnalysisResponseEvidence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoSentimentAnalysisResponseEvidence' from JSON`,
  );
}

/** @internal */
export const Theme$inboundSchema: z.ZodMiniType<Theme, unknown> = z.object({
  title: types.string(),
  polarity: Polarity$inboundSchema,
  claims: z.array(z.lazy(() => Claim$inboundSchema)),
  evidence: z.array(
    z.lazy(() => GeoSentimentAnalysisResponseEvidence$inboundSchema),
  ),
});

export function themeFromJSON(
  jsonString: string,
): SafeParseResult<Theme, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Theme$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Theme' from JSON`,
  );
}

/** @internal */
export const GeoSentimentAnalysisResponseResult$inboundSchema: z.ZodMiniType<
  GeoSentimentAnalysisResponseResult,
  unknown
> = z.object({
  fingerprint: types.string(),
  generatedAt: types.string(),
  sampled: types.number(),
  eligible: types.number(),
  themes: z.array(z.lazy(() => Theme$inboundSchema)),
});

export function geoSentimentAnalysisResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<GeoSentimentAnalysisResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeoSentimentAnalysisResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoSentimentAnalysisResponseResult' from JSON`,
  );
}

/** @internal */
export const GeoSentimentAnalysisResponseOrganization$inboundSchema:
  z.ZodMiniType<GeoSentimentAnalysisResponseOrganization, unknown> = z.object({
    id: types.string(),
    slug: types.string(),
    name: types.string(),
    logo: types.nullable(types.string()),
  });

export function geoSentimentAnalysisResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<
  GeoSentimentAnalysisResponseOrganization,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GeoSentimentAnalysisResponseOrganization$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GeoSentimentAnalysisResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoSentimentAnalysisResponse$inboundSchema: z.ZodMiniType<
  GeoSentimentAnalysisResponse,
  unknown
> = z.object({
  status: GeoSentimentAnalysisResponseStatus$inboundSchema,
  result: types.nullable(
    z.lazy(() => GeoSentimentAnalysisResponseResult$inboundSchema),
  ),
  message: types.nullable(types.string()),
  organization: z.lazy(() =>
    GeoSentimentAnalysisResponseOrganization$inboundSchema
  ),
});

export function geoSentimentAnalysisResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoSentimentAnalysisResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoSentimentAnalysisResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoSentimentAnalysisResponse' from JSON`,
  );
}
