/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 337874f588a1
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GeoTrafficPagesResponseVisitorType = {
  Crawler: "crawler",
  AiReferral: "ai_referral",
  Human: "human",
  Unknown: "unknown",
} as const;
export type GeoTrafficPagesResponseVisitorType = OpenEnum<
  typeof GeoTrafficPagesResponseVisitorType
>;

export type Page = {
  path: string;
  source: string;
  visitorType: GeoTrafficPagesResponseVisitorType;
  visits: number;
  previousVisits?: number | undefined;
  lastSeenAt: string;
};

export type GeoTrafficPagesResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoTrafficPagesResponse = {
  /**
   * False when the traffic backend is not configured for this deployment; the payload is then empty rather than an error.
   */
  configured: boolean;
  pages: Array<Page>;
  organization: GeoTrafficPagesResponseOrganization;
};

/** @internal */
export const GeoTrafficPagesResponseVisitorType$inboundSchema: z.ZodMiniType<
  GeoTrafficPagesResponseVisitorType,
  unknown
> = openEnums.inboundSchema(GeoTrafficPagesResponseVisitorType);

/** @internal */
export const Page$inboundSchema: z.ZodMiniType<Page, unknown> = z.object({
  path: types.string(),
  source: types.string(),
  visitorType: GeoTrafficPagesResponseVisitorType$inboundSchema,
  visits: types.number(),
  previousVisits: types.optional(types.number()),
  lastSeenAt: types.string(),
});

export function pageFromJSON(
  jsonString: string,
): SafeParseResult<Page, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Page$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Page' from JSON`,
  );
}

/** @internal */
export const GeoTrafficPagesResponseOrganization$inboundSchema: z.ZodMiniType<
  GeoTrafficPagesResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function geoTrafficPagesResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoTrafficPagesResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeoTrafficPagesResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoTrafficPagesResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoTrafficPagesResponse$inboundSchema: z.ZodMiniType<
  GeoTrafficPagesResponse,
  unknown
> = z.object({
  configured: types.boolean(),
  pages: z.array(z.lazy(() => Page$inboundSchema)),
  organization: z.lazy(() => GeoTrafficPagesResponseOrganization$inboundSchema),
});

export function geoTrafficPagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoTrafficPagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoTrafficPagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoTrafficPagesResponse' from JSON`,
  );
}
