/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 39eac6c70519
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Event = {
  capturedAt: string;
  path: string;
  host: string;
  method: string;
  referer: string;
  country: string;
  agent: string;
  category: string;
};

export type GeoJourneyDetailResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoJourneyDetailResponse = {
  /**
   * False when the traffic backend is not configured for this deployment; the payload is then empty rather than an error.
   */
  configured: boolean;
  events: Array<Event>;
  organization: GeoJourneyDetailResponseOrganization;
};

/** @internal */
export const Event$inboundSchema: z.ZodMiniType<Event, unknown> = z.object({
  capturedAt: types.string(),
  path: types.string(),
  host: types.string(),
  method: types.string(),
  referer: types.string(),
  country: types.string(),
  agent: types.string(),
  category: types.string(),
});

export function eventFromJSON(
  jsonString: string,
): SafeParseResult<Event, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Event$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Event' from JSON`,
  );
}

/** @internal */
export const GeoJourneyDetailResponseOrganization$inboundSchema: z.ZodMiniType<
  GeoJourneyDetailResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function geoJourneyDetailResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoJourneyDetailResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeoJourneyDetailResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoJourneyDetailResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoJourneyDetailResponse$inboundSchema: z.ZodMiniType<
  GeoJourneyDetailResponse,
  unknown
> = z.object({
  configured: types.boolean(),
  events: z.array(z.lazy(() => Event$inboundSchema)),
  organization: z.lazy(() =>
    GeoJourneyDetailResponseOrganization$inboundSchema
  ),
});

export function geoJourneyDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoJourneyDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoJourneyDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoJourneyDetailResponse' from JSON`,
  );
}
