/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3214a3364b6e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const PromptGapStatus = {
  Draft: "draft",
  Approved: "approved",
  Writing: "writing",
  Completed: "completed",
  Failed: "failed",
} as const;
export type PromptGapStatus = OpenEnum<typeof PromptGapStatus>;

export type PromptGapBrief = {
  briefId: string;
  status: PromptGapStatus;
  postId: string | null;
  workingTitle: string | null;
};

export type PromptGap = {
  id: string;
  prompt: string;
  title: string | null;
  engines: Array<string>;
  competitors: Array<string>;
  ownMentionRate: number;
  engineCoverage: number;
  opportunity: number;
  brief: PromptGapBrief | null;
};

export const SearchGapStatus = {
  Draft: "draft",
  Approved: "approved",
  Writing: "writing",
  Completed: "completed",
  Failed: "failed",
} as const;
export type SearchGapStatus = OpenEnum<typeof SearchGapStatus>;

export type SearchGapBrief = {
  briefId: string;
  status: SearchGapStatus;
  postId: string | null;
  workingTitle: string | null;
};

export type SearchGap = {
  id: string;
  prompt: string;
  title: string | null;
  impressions: number | null;
  brief: SearchGapBrief | null;
};

export type GeoContentGapsResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoContentGapsResponse = {
  promptGaps: Array<PromptGap>;
  searchGaps: Array<SearchGap>;
  /**
   * False until the project has at least one scan result.
   */
  hasScanData: boolean;
  organization: GeoContentGapsResponseOrganization;
};

/** @internal */
export const PromptGapStatus$inboundSchema: z.ZodMiniType<
  PromptGapStatus,
  unknown
> = openEnums.inboundSchema(PromptGapStatus);

/** @internal */
export const PromptGapBrief$inboundSchema: z.ZodMiniType<
  PromptGapBrief,
  unknown
> = z.object({
  briefId: types.string(),
  status: PromptGapStatus$inboundSchema,
  postId: types.nullable(types.string()),
  workingTitle: types.nullable(types.string()),
});

export function promptGapBriefFromJSON(
  jsonString: string,
): SafeParseResult<PromptGapBrief, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PromptGapBrief$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PromptGapBrief' from JSON`,
  );
}

/** @internal */
export const PromptGap$inboundSchema: z.ZodMiniType<PromptGap, unknown> = z
  .object({
    id: types.string(),
    prompt: types.string(),
    title: types.nullable(types.string()),
    engines: z.array(types.string()),
    competitors: z.array(types.string()),
    ownMentionRate: types.number(),
    engineCoverage: types.number(),
    opportunity: types.number(),
    brief: types.nullable(z.lazy(() => PromptGapBrief$inboundSchema)),
  });

export function promptGapFromJSON(
  jsonString: string,
): SafeParseResult<PromptGap, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PromptGap$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PromptGap' from JSON`,
  );
}

/** @internal */
export const SearchGapStatus$inboundSchema: z.ZodMiniType<
  SearchGapStatus,
  unknown
> = openEnums.inboundSchema(SearchGapStatus);

/** @internal */
export const SearchGapBrief$inboundSchema: z.ZodMiniType<
  SearchGapBrief,
  unknown
> = z.object({
  briefId: types.string(),
  status: SearchGapStatus$inboundSchema,
  postId: types.nullable(types.string()),
  workingTitle: types.nullable(types.string()),
});

export function searchGapBriefFromJSON(
  jsonString: string,
): SafeParseResult<SearchGapBrief, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchGapBrief$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchGapBrief' from JSON`,
  );
}

/** @internal */
export const SearchGap$inboundSchema: z.ZodMiniType<SearchGap, unknown> = z
  .object({
    id: types.string(),
    prompt: types.string(),
    title: types.nullable(types.string()),
    impressions: types.nullable(types.number()),
    brief: types.nullable(z.lazy(() => SearchGapBrief$inboundSchema)),
  });

export function searchGapFromJSON(
  jsonString: string,
): SafeParseResult<SearchGap, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchGap$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchGap' from JSON`,
  );
}

/** @internal */
export const GeoContentGapsResponseOrganization$inboundSchema: z.ZodMiniType<
  GeoContentGapsResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function geoContentGapsResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoContentGapsResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeoContentGapsResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoContentGapsResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoContentGapsResponse$inboundSchema: z.ZodMiniType<
  GeoContentGapsResponse,
  unknown
> = z.object({
  promptGaps: z.array(z.lazy(() => PromptGap$inboundSchema)),
  searchGaps: z.array(z.lazy(() => SearchGap$inboundSchema)),
  hasScanData: types.boolean(),
  organization: z.lazy(() => GeoContentGapsResponseOrganization$inboundSchema),
});

export function geoContentGapsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoContentGapsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoContentGapsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoContentGapsResponse' from JSON`,
  );
}
