/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6d993f1e5e3e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  GeoContentBriefDetail,
  GeoContentBriefDetail$inboundSchema,
} from "./geo-content-brief-detail.js";

export type GeoContentBriefResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoContentBriefResponse = {
  brief: GeoContentBriefDetail;
  organization: GeoContentBriefResponseOrganization;
};

/** @internal */
export const GeoContentBriefResponseOrganization$inboundSchema: z.ZodMiniType<
  GeoContentBriefResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function geoContentBriefResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoContentBriefResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeoContentBriefResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoContentBriefResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoContentBriefResponse$inboundSchema: z.ZodMiniType<
  GeoContentBriefResponse,
  unknown
> = z.object({
  brief: GeoContentBriefDetail$inboundSchema,
  organization: z.lazy(() => GeoContentBriefResponseOrganization$inboundSchema),
});

export function geoContentBriefResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoContentBriefResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoContentBriefResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoContentBriefResponse' from JSON`,
  );
}
