/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1e1d78ade75e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { GeoProject, GeoProject$inboundSchema } from "./geo-project.js";

export type GeoProjectResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoProjectResponse = {
  project: GeoProject;
  organization: GeoProjectResponseOrganization;
};

/** @internal */
export const GeoProjectResponseOrganization$inboundSchema: z.ZodMiniType<
  GeoProjectResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function geoProjectResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoProjectResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoProjectResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoProjectResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoProjectResponse$inboundSchema: z.ZodMiniType<
  GeoProjectResponse,
  unknown
> = z.object({
  project: GeoProject$inboundSchema,
  organization: z.lazy(() => GeoProjectResponseOrganization$inboundSchema),
});

export function geoProjectResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoProjectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoProjectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoProjectResponse' from JSON`,
  );
}
