/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 144dce007df8
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type GeoProject = {
  id: string;
  name: string;
  brandSettingsId: string;
  createdAt: string;
};

/** @internal */
export const GeoProject$inboundSchema: z.ZodMiniType<GeoProject, unknown> = z
  .object({
    id: types.string(),
    name: types.string(),
    brandSettingsId: types.string(),
    createdAt: types.string(),
  });

export function geoProjectFromJSON(
  jsonString: string,
): SafeParseResult<GeoProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoProject' from JSON`,
  );
}
