/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a3727cb3cc2c
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GeoCompetitorKind = {
  Direct: "direct",
  Indirect: "indirect",
} as const;
export type GeoCompetitorKind = OpenEnum<typeof GeoCompetitorKind>;

export type GeoCompetitor = {
  id: string;
  name: string;
  domain: string | null;
  synonyms: Array<string>;
  kind: GeoCompetitorKind;
  color: string | null;
};

/** @internal */
export const GeoCompetitorKind$inboundSchema: z.ZodMiniType<
  GeoCompetitorKind,
  unknown
> = openEnums.inboundSchema(GeoCompetitorKind);

/** @internal */
export const GeoCompetitor$inboundSchema: z.ZodMiniType<
  GeoCompetitor,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  domain: types.nullable(types.string()),
  synonyms: z.array(types.string()),
  kind: GeoCompetitorKind$inboundSchema,
  color: types.nullable(types.string()),
});

export function geoCompetitorFromJSON(
  jsonString: string,
): SafeParseResult<GeoCompetitor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoCompetitor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoCompetitor' from JSON`,
  );
}
