/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f1eeaac29e2a
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GeoShelfListResponseKind = {
  Listicle: "listicle",
  ReviewSite: "review_site",
  Community: "community",
  News: "news",
  Docs: "docs",
  Video: "video",
  Other: "other",
} as const;
export type GeoShelfListResponseKind = OpenEnum<
  typeof GeoShelfListResponseKind
>;

export const Ownership = {
  ThirdParty: "third_party",
  Own: "own",
  Competitor: "competitor",
} as const;
export type Ownership = OpenEnum<typeof Ownership>;

export const Origin = {
  Scan: "scan",
  Manual: "manual",
} as const;
export type Origin = OpenEnum<typeof Origin>;

export const FetchStatus = {
  Pending: "pending",
  Ok: "ok",
  Blocked: "blocked",
  Failed: "failed",
} as const;
export type FetchStatus = OpenEnum<typeof FetchStatus>;

export type Citations = {
  windowCount: number;
  totalCount: number;
  promptCount: number;
  engines: Array<string>;
  firstCitedAt: Date | null;
  lastCitedAt: Date | null;
};

export const PlacementStatus = {
  Present: "present",
  Absent: "absent",
  Unknown: "unknown",
} as const;
export type PlacementStatus = OpenEnum<typeof PlacementStatus>;

export const EvidenceEnum = {
  Fetch: "fetch",
  Manual: "manual",
} as const;
export type EvidenceEnum = OpenEnum<typeof EvidenceEnum>;

export type Placement = {
  competitorId: string | null;
  brandName: string;
  brandDomain: string | null;
  status: PlacementStatus;
  position: number | null;
  hasLink: boolean;
  evidence: EvidenceEnum;
  excerpt: string | null;
  checkedAt: Date;
};

export const OpportunityStatus = {
  Open: "open",
  InProgress: "in_progress",
  Won: "won",
  Lost: "lost",
  Dismissed: "dismissed",
} as const;
export type OpportunityStatus = OpenEnum<typeof OpportunityStatus>;

export const Priority = {
  Low: "low",
  Medium: "medium",
  High: "high",
} as const;
export type Priority = OpenEnum<typeof Priority>;

export type Opportunity = {
  status: OpportunityStatus;
  priority: Priority | null;
  assigneeMemberId: string | null;
  pocMemberId: string | null;
  notes: string | null;
  dueAt: Date | null;
  id: string;
  createdByUserId: string | null;
  resolvedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

export type GeoShelfListResponseSource = {
  id: string;
  url: string;
  domain: string;
  title: string | null;
  kind: GeoShelfListResponseKind;
  ownership: Ownership;
  origin: Origin;
  fetchStatus: FetchStatus;
  lastFetchedAt: Date | null;
  citations: Citations;
  placements: Array<Placement>;
  opportunity: Opportunity | null;
  createdByUserId: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type GeoShelfListResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoShelfListResponse = {
  sources: Array<GeoShelfListResponseSource>;
  nextOffset: number | null;
  organization: GeoShelfListResponseOrganization;
};

/** @internal */
export const GeoShelfListResponseKind$inboundSchema: z.ZodMiniType<
  GeoShelfListResponseKind,
  unknown
> = openEnums.inboundSchema(GeoShelfListResponseKind);

/** @internal */
export const Ownership$inboundSchema: z.ZodMiniType<Ownership, unknown> =
  openEnums.inboundSchema(Ownership);

/** @internal */
export const Origin$inboundSchema: z.ZodMiniType<Origin, unknown> = openEnums
  .inboundSchema(Origin);

/** @internal */
export const FetchStatus$inboundSchema: z.ZodMiniType<FetchStatus, unknown> =
  openEnums.inboundSchema(FetchStatus);

/** @internal */
export const Citations$inboundSchema: z.ZodMiniType<Citations, unknown> = z
  .object({
    windowCount: types.number(),
    totalCount: types.number(),
    promptCount: types.number(),
    engines: z.array(types.string()),
    firstCitedAt: types.nullable(types.date()),
    lastCitedAt: types.nullable(types.date()),
  });

export function citationsFromJSON(
  jsonString: string,
): SafeParseResult<Citations, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Citations$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Citations' from JSON`,
  );
}

/** @internal */
export const PlacementStatus$inboundSchema: z.ZodMiniType<
  PlacementStatus,
  unknown
> = openEnums.inboundSchema(PlacementStatus);

/** @internal */
export const EvidenceEnum$inboundSchema: z.ZodMiniType<EvidenceEnum, unknown> =
  openEnums.inboundSchema(EvidenceEnum);

/** @internal */
export const Placement$inboundSchema: z.ZodMiniType<Placement, unknown> = z
  .object({
    competitorId: types.nullable(types.string()),
    brandName: types.string(),
    brandDomain: types.nullable(types.string()),
    status: PlacementStatus$inboundSchema,
    position: types.nullable(types.number()),
    hasLink: types.boolean(),
    evidence: EvidenceEnum$inboundSchema,
    excerpt: types.nullable(types.string()),
    checkedAt: types.date(),
  });

export function placementFromJSON(
  jsonString: string,
): SafeParseResult<Placement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Placement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Placement' from JSON`,
  );
}

/** @internal */
export const OpportunityStatus$inboundSchema: z.ZodMiniType<
  OpportunityStatus,
  unknown
> = openEnums.inboundSchema(OpportunityStatus);

/** @internal */
export const Priority$inboundSchema: z.ZodMiniType<Priority, unknown> =
  openEnums.inboundSchema(Priority);

/** @internal */
export const Opportunity$inboundSchema: z.ZodMiniType<Opportunity, unknown> = z
  .object({
    status: OpportunityStatus$inboundSchema,
    priority: types.nullable(Priority$inboundSchema),
    assigneeMemberId: types.nullable(types.string()),
    pocMemberId: types.nullable(types.string()),
    notes: types.nullable(types.string()),
    dueAt: types.nullable(types.date()),
    id: types.string(),
    createdByUserId: types.nullable(types.string()),
    resolvedAt: types.nullable(types.date()),
    createdAt: types.date(),
    updatedAt: types.date(),
  });

export function opportunityFromJSON(
  jsonString: string,
): SafeParseResult<Opportunity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Opportunity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Opportunity' from JSON`,
  );
}

/** @internal */
export const GeoShelfListResponseSource$inboundSchema: z.ZodMiniType<
  GeoShelfListResponseSource,
  unknown
> = z.object({
  id: types.string(),
  url: types.string(),
  domain: types.string(),
  title: types.nullable(types.string()),
  kind: GeoShelfListResponseKind$inboundSchema,
  ownership: Ownership$inboundSchema,
  origin: Origin$inboundSchema,
  fetchStatus: FetchStatus$inboundSchema,
  lastFetchedAt: types.nullable(types.date()),
  citations: z.lazy(() => Citations$inboundSchema),
  placements: z.array(z.lazy(() => Placement$inboundSchema)),
  opportunity: types.nullable(z.lazy(() => Opportunity$inboundSchema)),
  createdByUserId: types.nullable(types.string()),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function geoShelfListResponseSourceFromJSON(
  jsonString: string,
): SafeParseResult<GeoShelfListResponseSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoShelfListResponseSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoShelfListResponseSource' from JSON`,
  );
}

/** @internal */
export const GeoShelfListResponseOrganization$inboundSchema: z.ZodMiniType<
  GeoShelfListResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function geoShelfListResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoShelfListResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoShelfListResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoShelfListResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoShelfListResponse$inboundSchema: z.ZodMiniType<
  GeoShelfListResponse,
  unknown
> = z.object({
  sources: z.array(z.lazy(() => GeoShelfListResponseSource$inboundSchema)),
  nextOffset: types.nullable(types.number()),
  organization: z.lazy(() => GeoShelfListResponseOrganization$inboundSchema),
});

export function geoShelfListResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoShelfListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoShelfListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoShelfListResponse' from JSON`,
  );
}
