/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3726decc4e46
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Totals = {
  crawler: number;
  cited: number;
  aiReferral: number;
  /**
   * AI referral visits that reached a configured conversion path. Null when no conversion paths are set.
   */
  conversions: number | null;
};

export const SourceVisitorType = {
  Crawler: "crawler",
  AiReferral: "ai_referral",
  Human: "human",
  Unknown: "unknown",
} as const;
export type SourceVisitorType = OpenEnum<typeof SourceVisitorType>;

export type GeoTrafficOverviewResponseSource = {
  source: string;
  visitorType: SourceVisitorType;
  agent: string;
  category: string;
  confidence: string;
  visits: number;
  previousVisits?: number | undefined;
  markdownVisits: number;
  paths: number;
  lastSeenAt: string;
};

export const PointVisitorType = {
  Crawler: "crawler",
  AiReferral: "ai_referral",
  Human: "human",
  Unknown: "unknown",
} as const;
export type PointVisitorType = OpenEnum<typeof PointVisitorType>;

export type GeoTrafficOverviewResponsePoint = {
  day: string;
  visitorType: PointVisitorType;
  source: string;
  visits: number;
};

export type GeoTrafficOverviewResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoTrafficOverviewResponse = {
  /**
   * False when the traffic backend is not configured for this deployment; the payload is then empty rather than an error.
   */
  configured: boolean;
  totals: Totals;
  /**
   * Conversions in the previous window of the same length. Null when no conversion paths are set or no comparison data exists.
   */
  previousConversions: number | null;
  sources: Array<GeoTrafficOverviewResponseSource>;
  points: Array<GeoTrafficOverviewResponsePoint>;
  organization: GeoTrafficOverviewResponseOrganization;
};

/** @internal */
export const Totals$inboundSchema: z.ZodMiniType<Totals, unknown> = z.object({
  crawler: types.number(),
  cited: types.number(),
  aiReferral: types.number(),
  conversions: types.nullable(types.number()),
});

export function totalsFromJSON(
  jsonString: string,
): SafeParseResult<Totals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Totals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Totals' from JSON`,
  );
}

/** @internal */
export const SourceVisitorType$inboundSchema: z.ZodMiniType<
  SourceVisitorType,
  unknown
> = openEnums.inboundSchema(SourceVisitorType);

/** @internal */
export const GeoTrafficOverviewResponseSource$inboundSchema: z.ZodMiniType<
  GeoTrafficOverviewResponseSource,
  unknown
> = z.object({
  source: types.string(),
  visitorType: SourceVisitorType$inboundSchema,
  agent: types.string(),
  category: types.string(),
  confidence: types.string(),
  visits: types.number(),
  previousVisits: types.optional(types.number()),
  markdownVisits: types.number(),
  paths: types.number(),
  lastSeenAt: types.string(),
});

export function geoTrafficOverviewResponseSourceFromJSON(
  jsonString: string,
): SafeParseResult<GeoTrafficOverviewResponseSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoTrafficOverviewResponseSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoTrafficOverviewResponseSource' from JSON`,
  );
}

/** @internal */
export const PointVisitorType$inboundSchema: z.ZodMiniType<
  PointVisitorType,
  unknown
> = openEnums.inboundSchema(PointVisitorType);

/** @internal */
export const GeoTrafficOverviewResponsePoint$inboundSchema: z.ZodMiniType<
  GeoTrafficOverviewResponsePoint,
  unknown
> = z.object({
  day: types.string(),
  visitorType: PointVisitorType$inboundSchema,
  source: types.string(),
  visits: types.number(),
});

export function geoTrafficOverviewResponsePointFromJSON(
  jsonString: string,
): SafeParseResult<GeoTrafficOverviewResponsePoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoTrafficOverviewResponsePoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoTrafficOverviewResponsePoint' from JSON`,
  );
}

/** @internal */
export const GeoTrafficOverviewResponseOrganization$inboundSchema:
  z.ZodMiniType<GeoTrafficOverviewResponseOrganization, unknown> = z.object({
    id: types.string(),
    slug: types.string(),
    name: types.string(),
    logo: types.nullable(types.string()),
  });

export function geoTrafficOverviewResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoTrafficOverviewResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeoTrafficOverviewResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoTrafficOverviewResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoTrafficOverviewResponse$inboundSchema: z.ZodMiniType<
  GeoTrafficOverviewResponse,
  unknown
> = z.object({
  configured: types.boolean(),
  totals: z.lazy(() => Totals$inboundSchema),
  previousConversions: types.nullable(types.number()),
  sources: z.array(
    z.lazy(() => GeoTrafficOverviewResponseSource$inboundSchema),
  ),
  points: z.array(z.lazy(() => GeoTrafficOverviewResponsePoint$inboundSchema)),
  organization: z.lazy(() =>
    GeoTrafficOverviewResponseOrganization$inboundSchema
  ),
});

export function geoTrafficOverviewResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoTrafficOverviewResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoTrafficOverviewResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoTrafficOverviewResponse' from JSON`,
  );
}
