/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9f825ca4c9e6
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  GeoContentBriefDocument,
  GeoContentBriefDocument$inboundSchema,
} from "./geo-content-brief-document.js";

export const GeoContentBriefDetailStatus = {
  Draft: "draft",
  Approved: "approved",
  Writing: "writing",
  Completed: "completed",
  Failed: "failed",
} as const;
export type GeoContentBriefDetailStatus = OpenEnum<
  typeof GeoContentBriefDetailStatus
>;

export type GeoContentBriefDetail = {
  id: string;
  topic: string;
  brief: GeoContentBriefDocument;
  status: GeoContentBriefDetailStatus;
  autoApproved: boolean;
  runId: string | null;
  postId: string | null;
  humanized: boolean;
  error: string | null;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};

/** @internal */
export const GeoContentBriefDetailStatus$inboundSchema: z.ZodMiniType<
  GeoContentBriefDetailStatus,
  unknown
> = openEnums.inboundSchema(GeoContentBriefDetailStatus);

/** @internal */
export const GeoContentBriefDetail$inboundSchema: z.ZodMiniType<
  GeoContentBriefDetail,
  unknown
> = z.object({
  id: types.string(),
  topic: types.string(),
  brief: GeoContentBriefDocument$inboundSchema,
  status: GeoContentBriefDetailStatus$inboundSchema,
  autoApproved: types.boolean(),
  runId: types.nullable(types.string()),
  postId: types.nullable(types.string()),
  humanized: types.boolean(),
  error: types.nullable(types.string()),
  createdAt: types.string(),
  updatedAt: types.string(),
  completedAt: types.nullable(types.string()),
});

export function geoContentBriefDetailFromJSON(
  jsonString: string,
): SafeParseResult<GeoContentBriefDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoContentBriefDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoContentBriefDetail' from JSON`,
  );
}
