/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0ed4fb3be4cd
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type GeoSequence = {
  id: string;
  name: string;
  steps: Array<string>;
  enabled: boolean;
  createdAt: string;
};

/** @internal */
export const GeoSequence$inboundSchema: z.ZodMiniType<GeoSequence, unknown> = z
  .object({
    id: types.string(),
    name: types.string(),
    steps: z.array(types.string()),
    enabled: types.boolean(),
    createdAt: types.string(),
  });

export function geoSequenceFromJSON(
  jsonString: string,
): SafeParseResult<GeoSequence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoSequence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoSequence' from JSON`,
  );
}
