/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a72498f69654
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { GeoScan, GeoScan$inboundSchema } from "./geo-scan.js";

export type GeoScanResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoScanResponse = {
  scan: GeoScan;
  organization: GeoScanResponseOrganization;
};

/** @internal */
export const GeoScanResponseOrganization$inboundSchema: z.ZodMiniType<
  GeoScanResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function geoScanResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoScanResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoScanResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoScanResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoScanResponse$inboundSchema: z.ZodMiniType<
  GeoScanResponse,
  unknown
> = z.object({
  scan: GeoScan$inboundSchema,
  organization: z.lazy(() => GeoScanResponseOrganization$inboundSchema),
});

export function geoScanResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoScanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoScanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoScanResponse' from JSON`,
  );
}
