/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8a254c6d3bf3
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GeoContentBriefDocumentContentSubtype = {
  Guide: "guide",
  Comparison: "comparison",
  Listicle: "listicle",
  HowTo: "how-to",
  Faq: "faq",
  Alternatives: "alternatives",
} as const;
export type GeoContentBriefDocumentContentSubtype = OpenEnum<
  typeof GeoContentBriefDocumentContentSubtype
>;

export type Section = {
  heading: string;
  goal: string;
  claims: Array<string>;
};

export type InternalLink = {
  url: string;
  anchor: string;
  why: string;
};

export type GeoContentBriefDocument = {
  targetPrompt: string;
  intent: string;
  contentSubtype: GeoContentBriefDocumentContentSubtype;
  workingTitle: string;
  audience: string;
  jobToBeDone: string;
  sections: Array<Section>;
  questionsToAnswer: Array<string>;
  internalLinks: Array<InternalLink>;
  acceptanceChecklist: Array<string>;
};

/** @internal */
export const GeoContentBriefDocumentContentSubtype$inboundSchema: z.ZodMiniType<
  GeoContentBriefDocumentContentSubtype,
  unknown
> = openEnums.inboundSchema(GeoContentBriefDocumentContentSubtype);

/** @internal */
export const Section$inboundSchema: z.ZodMiniType<Section, unknown> = z.object({
  heading: types.string(),
  goal: types.string(),
  claims: z.array(types.string()),
});

export function sectionFromJSON(
  jsonString: string,
): SafeParseResult<Section, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Section$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Section' from JSON`,
  );
}

/** @internal */
export const InternalLink$inboundSchema: z.ZodMiniType<InternalLink, unknown> =
  z.object({
    url: types.string(),
    anchor: types.string(),
    why: types.string(),
  });

export function internalLinkFromJSON(
  jsonString: string,
): SafeParseResult<InternalLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InternalLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InternalLink' from JSON`,
  );
}

/** @internal */
export const GeoContentBriefDocument$inboundSchema: z.ZodMiniType<
  GeoContentBriefDocument,
  unknown
> = z.object({
  targetPrompt: types.string(),
  intent: types.string(),
  contentSubtype: GeoContentBriefDocumentContentSubtype$inboundSchema,
  workingTitle: types.string(),
  audience: types.string(),
  jobToBeDone: types.string(),
  sections: z.array(z.lazy(() => Section$inboundSchema)),
  questionsToAnswer: z.array(types.string()),
  internalLinks: z.array(z.lazy(() => InternalLink$inboundSchema)),
  acceptanceChecklist: z.array(types.string()),
});

export function geoContentBriefDocumentFromJSON(
  jsonString: string,
): SafeParseResult<GeoContentBriefDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoContentBriefDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoContentBriefDocument' from JSON`,
  );
}
