/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c2321cb3811f
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GeoScanStatus = {
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
export type GeoScanStatus = OpenEnum<typeof GeoScanStatus>;

export type GeoScan = {
  id: string;
  projectId: string;
  status: GeoScanStatus;
  startedAt: string;
  finishedAt: string | null;
  createdAt: string;
};

/** @internal */
export const GeoScanStatus$inboundSchema: z.ZodMiniType<
  GeoScanStatus,
  unknown
> = openEnums.inboundSchema(GeoScanStatus);

/** @internal */
export const GeoScan$inboundSchema: z.ZodMiniType<GeoScan, unknown> = z.object({
  id: types.string(),
  projectId: types.string(),
  status: GeoScanStatus$inboundSchema,
  startedAt: types.string(),
  finishedAt: types.nullable(types.string()),
  createdAt: types.string(),
});

export function geoScanFromJSON(
  jsonString: string,
): SafeParseResult<GeoScan, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoScan$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoScan' from JSON`,
  );
}
