/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8a254c6d3bf3
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GeoContentBriefDocumentContentSubtype = {
  Guide: "guide",
  Comparison: "comparison",
  Listicle: "listicle",
  HowTo: "how-to",
  Faq: "faq",
  Alternatives: "alternatives",
} as const;
export type GeoContentBriefDocumentContentSubtype = OpenEnum<
  typeof GeoContentBriefDocumentContentSubtype
>;

export type Section = {
  heading: string;
  goal: string;
  claims: Array<string>;
};

export type InternalLink = {
  url: string;
  anchor: string;
  why: string;
};

export type GeoContentBriefDocumentEngine = {
  engine: string;
  mentioned: boolean;
  position: number | null;
};

export type CompetitorMention = {
  name: string;
  engines: number;
};

export type CitedDomain = {
  domain: string;
  engines: number;
};

export type GeoContentBriefDocumentBaseline = {
  sourcePromptId: string;
  mentionedEngines: number;
  totalEngines: number;
  engines: Array<GeoContentBriefDocumentEngine>;
  competitorMentions: Array<CompetitorMention>;
  citedDomains: Array<CitedDomain>;
  capturedAt: string | null;
};

export type GeoContentBriefDocument = {
  targetPrompt: string;
  intent: string;
  contentSubtype: GeoContentBriefDocumentContentSubtype;
  workingTitle: string;
  audience: string;
  jobToBeDone: string;
  sections: Array<Section>;
  questionsToAnswer: Array<string>;
  internalLinks: Array<InternalLink>;
  acceptanceChecklist: Array<string>;
  recommendedAngle?: string | undefined;
  competitorsToCounter?: Array<string> | undefined;
  sourcesToReference?: Array<string> | undefined;
  missingCoverage?: Array<string> | undefined;
  baseline?: GeoContentBriefDocumentBaseline | null | undefined;
};

/** @internal */
export const GeoContentBriefDocumentContentSubtype$inboundSchema: z.ZodMiniType<
  GeoContentBriefDocumentContentSubtype,
  unknown
> = openEnums.inboundSchema(GeoContentBriefDocumentContentSubtype);

/** @internal */
export const Section$inboundSchema: z.ZodMiniType<Section, unknown> = z.object({
  heading: types.string(),
  goal: types.string(),
  claims: z.array(types.string()),
});

export function sectionFromJSON(
  jsonString: string,
): SafeParseResult<Section, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Section$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Section' from JSON`,
  );
}

/** @internal */
export const InternalLink$inboundSchema: z.ZodMiniType<InternalLink, unknown> =
  z.object({
    url: types.string(),
    anchor: types.string(),
    why: types.string(),
  });

export function internalLinkFromJSON(
  jsonString: string,
): SafeParseResult<InternalLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InternalLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InternalLink' from JSON`,
  );
}

/** @internal */
export const GeoContentBriefDocumentEngine$inboundSchema: z.ZodMiniType<
  GeoContentBriefDocumentEngine,
  unknown
> = z.object({
  engine: types.string(),
  mentioned: types.boolean(),
  position: types.nullable(types.number()),
});

export function geoContentBriefDocumentEngineFromJSON(
  jsonString: string,
): SafeParseResult<GeoContentBriefDocumentEngine, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoContentBriefDocumentEngine$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoContentBriefDocumentEngine' from JSON`,
  );
}

/** @internal */
export const CompetitorMention$inboundSchema: z.ZodMiniType<
  CompetitorMention,
  unknown
> = z.object({
  name: types.string(),
  engines: types.number(),
});

export function competitorMentionFromJSON(
  jsonString: string,
): SafeParseResult<CompetitorMention, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompetitorMention$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompetitorMention' from JSON`,
  );
}

/** @internal */
export const CitedDomain$inboundSchema: z.ZodMiniType<CitedDomain, unknown> = z
  .object({
    domain: types.string(),
    engines: types.number(),
  });

export function citedDomainFromJSON(
  jsonString: string,
): SafeParseResult<CitedDomain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CitedDomain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CitedDomain' from JSON`,
  );
}

/** @internal */
export const GeoContentBriefDocumentBaseline$inboundSchema: z.ZodMiniType<
  GeoContentBriefDocumentBaseline,
  unknown
> = z.object({
  sourcePromptId: types.string(),
  mentionedEngines: types.number(),
  totalEngines: types.number(),
  engines: z.array(z.lazy(() => GeoContentBriefDocumentEngine$inboundSchema)),
  competitorMentions: z.array(z.lazy(() => CompetitorMention$inboundSchema)),
  citedDomains: z.array(z.lazy(() => CitedDomain$inboundSchema)),
  capturedAt: types.nullable(types.string()),
});

export function geoContentBriefDocumentBaselineFromJSON(
  jsonString: string,
): SafeParseResult<GeoContentBriefDocumentBaseline, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoContentBriefDocumentBaseline$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoContentBriefDocumentBaseline' from JSON`,
  );
}

/** @internal */
export const GeoContentBriefDocument$inboundSchema: z.ZodMiniType<
  GeoContentBriefDocument,
  unknown
> = z.object({
  targetPrompt: types.string(),
  intent: types.string(),
  contentSubtype: GeoContentBriefDocumentContentSubtype$inboundSchema,
  workingTitle: types.string(),
  audience: types.string(),
  jobToBeDone: types.string(),
  sections: z.array(z.lazy(() => Section$inboundSchema)),
  questionsToAnswer: z.array(types.string()),
  internalLinks: z.array(z.lazy(() => InternalLink$inboundSchema)),
  acceptanceChecklist: z.array(types.string()),
  recommendedAngle: types.optional(types.string()),
  competitorsToCounter: types.optional(z.array(types.string())),
  sourcesToReference: types.optional(z.array(types.string())),
  missingCoverage: types.optional(z.array(types.string())),
  baseline: z.optional(
    z.nullable(z.lazy(() => GeoContentBriefDocumentBaseline$inboundSchema)),
  ),
});

export function geoContentBriefDocumentFromJSON(
  jsonString: string,
): SafeParseResult<GeoContentBriefDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoContentBriefDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoContentBriefDocument' from JSON`,
  );
}
