/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 105a98afc53e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type GeoVisibilityTimeseriesResponsePoint = {
  day: string;
  engine: string;
  checks: number;
  mentions: number;
  avgPosition?: number | null | undefined;
};

export type GeoVisibilityTimeseriesResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoVisibilityTimeseriesResponse = {
  configured: boolean;
  points: Array<GeoVisibilityTimeseriesResponsePoint>;
  organization: GeoVisibilityTimeseriesResponseOrganization;
};

/** @internal */
export const GeoVisibilityTimeseriesResponsePoint$inboundSchema: z.ZodMiniType<
  GeoVisibilityTimeseriesResponsePoint,
  unknown
> = z.object({
  day: types.string(),
  engine: types.string(),
  checks: types.number(),
  mentions: types.number(),
  avgPosition: z.optional(z.nullable(types.number())),
});

export function geoVisibilityTimeseriesResponsePointFromJSON(
  jsonString: string,
): SafeParseResult<GeoVisibilityTimeseriesResponsePoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeoVisibilityTimeseriesResponsePoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoVisibilityTimeseriesResponsePoint' from JSON`,
  );
}

/** @internal */
export const GeoVisibilityTimeseriesResponseOrganization$inboundSchema:
  z.ZodMiniType<GeoVisibilityTimeseriesResponseOrganization, unknown> = z
    .object({
      id: types.string(),
      slug: types.string(),
      name: types.string(),
      logo: types.nullable(types.string()),
    });

export function geoVisibilityTimeseriesResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<
  GeoVisibilityTimeseriesResponseOrganization,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GeoVisibilityTimeseriesResponseOrganization$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GeoVisibilityTimeseriesResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoVisibilityTimeseriesResponse$inboundSchema: z.ZodMiniType<
  GeoVisibilityTimeseriesResponse,
  unknown
> = z.object({
  configured: types.boolean(),
  points: z.array(
    z.lazy(() => GeoVisibilityTimeseriesResponsePoint$inboundSchema),
  ),
  organization: z.lazy(() =>
    GeoVisibilityTimeseriesResponseOrganization$inboundSchema
  ),
});

export function geoVisibilityTimeseriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoVisibilityTimeseriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoVisibilityTimeseriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoVisibilityTimeseriesResponse' from JSON`,
  );
}
