/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 46edcbd44166
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { GeoPrompt, GeoPrompt$inboundSchema } from "./geo-prompt.js";

export type GeoPromptResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoPromptResponse = {
  prompt: GeoPrompt;
  organization: GeoPromptResponseOrganization;
};

/** @internal */
export const GeoPromptResponseOrganization$inboundSchema: z.ZodMiniType<
  GeoPromptResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function geoPromptResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoPromptResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoPromptResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoPromptResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoPromptResponse$inboundSchema: z.ZodMiniType<
  GeoPromptResponse,
  unknown
> = z.object({
  prompt: GeoPrompt$inboundSchema,
  organization: z.lazy(() => GeoPromptResponseOrganization$inboundSchema),
});

export function geoPromptResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoPromptResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoPromptResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoPromptResponse' from JSON`,
  );
}
