/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dc0fcf3fa400
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type GeoAgentReadinessScanResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoAgentReadinessScanResponse = {
  reportId: string;
  /**
   * True when an in-flight scan for the same URL was reused instead of starting a new one.
   */
  alreadyRunning: boolean;
  organization: GeoAgentReadinessScanResponseOrganization;
};

/** @internal */
export const GeoAgentReadinessScanResponseOrganization$inboundSchema:
  z.ZodMiniType<GeoAgentReadinessScanResponseOrganization, unknown> = z.object({
    id: types.string(),
    slug: types.string(),
    name: types.string(),
    logo: types.nullable(types.string()),
  });

export function geoAgentReadinessScanResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<
  GeoAgentReadinessScanResponseOrganization,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GeoAgentReadinessScanResponseOrganization$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GeoAgentReadinessScanResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoAgentReadinessScanResponse$inboundSchema: z.ZodMiniType<
  GeoAgentReadinessScanResponse,
  unknown
> = z.object({
  reportId: types.string(),
  alreadyRunning: types.boolean(),
  organization: z.lazy(() =>
    GeoAgentReadinessScanResponseOrganization$inboundSchema
  ),
});

export function geoAgentReadinessScanResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoAgentReadinessScanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoAgentReadinessScanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoAgentReadinessScanResponse' from JSON`,
  );
}
