/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 09679a0ed727
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Engine = {
  engine: string;
  checks: number;
  mentions: number;
  mentionRate: number;
  avgPosition: number | null;
  lastCheckedAt: string;
};

export type GeoVisibilityOverviewResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoVisibilityOverviewResponse = {
  /**
   * Whether the analytics backend is configured.
   */
  configured: boolean;
  engines: Array<Engine>;
  organization: GeoVisibilityOverviewResponseOrganization;
};

/** @internal */
export const Engine$inboundSchema: z.ZodMiniType<Engine, unknown> = z.object({
  engine: types.string(),
  checks: types.number(),
  mentions: types.number(),
  mentionRate: types.number(),
  avgPosition: types.nullable(types.number()),
  lastCheckedAt: types.string(),
});

export function engineFromJSON(
  jsonString: string,
): SafeParseResult<Engine, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Engine$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Engine' from JSON`,
  );
}

/** @internal */
export const GeoVisibilityOverviewResponseOrganization$inboundSchema:
  z.ZodMiniType<GeoVisibilityOverviewResponseOrganization, unknown> = z.object({
    id: types.string(),
    slug: types.string(),
    name: types.string(),
    logo: types.nullable(types.string()),
  });

export function geoVisibilityOverviewResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<
  GeoVisibilityOverviewResponseOrganization,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GeoVisibilityOverviewResponseOrganization$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GeoVisibilityOverviewResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoVisibilityOverviewResponse$inboundSchema: z.ZodMiniType<
  GeoVisibilityOverviewResponse,
  unknown
> = z.object({
  configured: types.boolean(),
  engines: z.array(z.lazy(() => Engine$inboundSchema)),
  organization: z.lazy(() =>
    GeoVisibilityOverviewResponseOrganization$inboundSchema
  ),
});

export function geoVisibilityOverviewResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoVisibilityOverviewResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoVisibilityOverviewResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoVisibilityOverviewResponse' from JSON`,
  );
}
