/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9da3fcbdca54
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Check = {
  id: string;
  scanId: string;
  engine: string;
  mentioned: boolean;
  ownedSourceCited?: boolean | undefined;
  position: number | null;
  sentiment: string | null;
  competitors: Array<string>;
  language: string;
  capturedAt: string;
};

export type GeoPromptHistoryResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoPromptHistoryResponse = {
  configured: boolean;
  promptId: string;
  checks: Array<Check>;
  organization: GeoPromptHistoryResponseOrganization;
};

/** @internal */
export const Check$inboundSchema: z.ZodMiniType<Check, unknown> = z.object({
  id: types.string(),
  scanId: types.string(),
  engine: types.string(),
  mentioned: types.boolean(),
  ownedSourceCited: types.optional(types.boolean()),
  position: types.nullable(types.number()),
  sentiment: types.nullable(types.string()),
  competitors: z.array(types.string()),
  language: types.string(),
  capturedAt: types.string(),
});

export function checkFromJSON(
  jsonString: string,
): SafeParseResult<Check, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Check$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Check' from JSON`,
  );
}

/** @internal */
export const GeoPromptHistoryResponseOrganization$inboundSchema: z.ZodMiniType<
  GeoPromptHistoryResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function geoPromptHistoryResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoPromptHistoryResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeoPromptHistoryResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoPromptHistoryResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoPromptHistoryResponse$inboundSchema: z.ZodMiniType<
  GeoPromptHistoryResponse,
  unknown
> = z.object({
  configured: types.boolean(),
  promptId: types.string(),
  checks: z.array(z.lazy(() => Check$inboundSchema)),
  organization: z.lazy(() =>
    GeoPromptHistoryResponseOrganization$inboundSchema
  ),
});

export function geoPromptHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoPromptHistoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoPromptHistoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoPromptHistoryResponse' from JSON`,
  );
}
