/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 897a4445c7c1
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Confidence = {
  High: "high",
  Medium: "medium",
} as const;
export type Confidence = OpenEnum<typeof Confidence>;

export type Competitor = {
  name: string;
  domain: string | null;
  description: string | null;
  confidence: Confidence | null;
};

export type GeoCompetitorSuggestionsResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoCompetitorSuggestionsResponse = {
  domain: string;
  field: string | null;
  competitors: Array<Competitor>;
  organization: GeoCompetitorSuggestionsResponseOrganization;
};

/** @internal */
export const Confidence$inboundSchema: z.ZodMiniType<Confidence, unknown> =
  openEnums.inboundSchema(Confidence);

/** @internal */
export const Competitor$inboundSchema: z.ZodMiniType<Competitor, unknown> = z
  .object({
    name: types.string(),
    domain: types.nullable(types.string()),
    description: types.nullable(types.string()),
    confidence: types.nullable(Confidence$inboundSchema),
  });

export function competitorFromJSON(
  jsonString: string,
): SafeParseResult<Competitor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Competitor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Competitor' from JSON`,
  );
}

/** @internal */
export const GeoCompetitorSuggestionsResponseOrganization$inboundSchema:
  z.ZodMiniType<GeoCompetitorSuggestionsResponseOrganization, unknown> = z
    .object({
      id: types.string(),
      slug: types.string(),
      name: types.string(),
      logo: types.nullable(types.string()),
    });

export function geoCompetitorSuggestionsResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<
  GeoCompetitorSuggestionsResponseOrganization,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GeoCompetitorSuggestionsResponseOrganization$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GeoCompetitorSuggestionsResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoCompetitorSuggestionsResponse$inboundSchema: z.ZodMiniType<
  GeoCompetitorSuggestionsResponse,
  unknown
> = z.object({
  domain: types.string(),
  field: types.nullable(types.string()),
  competitors: z.array(z.lazy(() => Competitor$inboundSchema)),
  organization: z.lazy(() =>
    GeoCompetitorSuggestionsResponseOrganization$inboundSchema
  ),
});

export function geoCompetitorSuggestionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoCompetitorSuggestionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoCompetitorSuggestionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoCompetitorSuggestionsResponse' from JSON`,
  );
}
