/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3214a3364b6e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const PromptGapStatus = {
  Draft: "draft",
  Approved: "approved",
  Writing: "writing",
  Completed: "completed",
  Failed: "failed",
} as const;
export type PromptGapStatus = OpenEnum<typeof PromptGapStatus>;

export type PromptGapBaseline = {
  mentionedEngines: number;
  totalEngines: number;
};

export type PromptGapBrief = {
  briefId: string;
  status: PromptGapStatus;
  postId: string | null;
  workingTitle: string | null;
  publishedAt: string | null;
  baseline: PromptGapBaseline | null;
  rescanned: boolean;
};

export type PromptGap = {
  id: string;
  prompt: string;
  title: string | null;
  engines: Array<string>;
  mentionedEngines: Array<string>;
  competitors: Array<string>;
  discoveredCompetitors: Array<string>;
  /**
   * Web searches AI engines ran while answering this prompt.
   */
  searchQueries: Array<string>;
  ownMentionRate: number;
  engineCoverage: number;
  opportunity: number;
  won: boolean;
  brief: PromptGapBrief | null;
};

export type Query = {
  query: string;
  clicks: number;
  impressions: number;
  position: number;
};

export const SearchGapStatus = {
  Draft: "draft",
  Approved: "approved",
  Writing: "writing",
  Completed: "completed",
  Failed: "failed",
} as const;
export type SearchGapStatus = OpenEnum<typeof SearchGapStatus>;

export type SearchGapBaseline = {
  mentionedEngines: number;
  totalEngines: number;
};

export type SearchGapBrief = {
  briefId: string;
  status: SearchGapStatus;
  postId: string | null;
  workingTitle: string | null;
  publishedAt: string | null;
  baseline: SearchGapBaseline | null;
  rescanned: boolean;
};

/**
 * What to do with this query cluster: create a new page, update the strongest existing page, merge overlapping pages, or ignore thin demand.
 */
export const Action = {
  Create: "create",
  Update: "update",
  Merge: "merge",
  Ignore: "ignore",
} as const;
/**
 * What to do with this query cluster: create a new page, update the strongest existing page, merge overlapping pages, or ignore thin demand.
 */
export type Action = OpenEnum<typeof Action>;

export const GeoContentGapsResponseKind = {
  Page: "page",
  Post: "post",
} as const;
export type GeoContentGapsResponseKind = OpenEnum<
  typeof GeoContentGapsResponseKind
>;

export type Target = {
  kind: GeoContentGapsResponseKind;
  id: string;
  url: string | null;
  title: string;
  score: number;
};

export type Recommendation = {
  /**
   * What to do with this query cluster: create a new page, update the strongest existing page, merge overlapping pages, or ignore thin demand.
   */
  action: Action;
  reason: string;
  targets: Array<Target>;
};

export type SearchGap = {
  id: string;
  prompt: string;
  title: string | null;
  impressions: number | null;
  clicks: number | null;
  position: number | null;
  queries: Array<Query>;
  brief: SearchGapBrief | null;
  recommendation: Recommendation;
};

export const AiSearchGapStatus = {
  Draft: "draft",
  Approved: "approved",
  Writing: "writing",
  Completed: "completed",
  Failed: "failed",
} as const;
export type AiSearchGapStatus = OpenEnum<typeof AiSearchGapStatus>;

export type AiSearchGapBaseline = {
  mentionedEngines: number;
  totalEngines: number;
};

export type AiSearchGapBrief = {
  briefId: string;
  status: AiSearchGapStatus;
  postId: string | null;
  workingTitle: string | null;
  publishedAt: string | null;
  baseline: AiSearchGapBaseline | null;
  rescanned: boolean;
};

export type AiSearchGap = {
  id: string;
  query: string;
  variants: Array<string>;
  prompts: Array<string>;
  engines: Array<string>;
  /**
   * Scan answers in which an engine ran this web search.
   */
  searches: number;
  ownMentionRate: number;
  competitors: Array<string>;
  discoveredCompetitors: Array<string>;
  opportunity: number;
  brief: AiSearchGapBrief | null;
};

export type GeoContentGapsResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoContentGapsResponse = {
  promptGaps: Array<PromptGap>;
  searchGaps: Array<SearchGap>;
  /**
   * Web searches AI engines run across your scans where you are neither cited nor mentioned in most answers.
   */
  aiSearchGaps: Array<AiSearchGap>;
  /**
   * False until the project has at least one scan result.
   */
  hasScanData: boolean;
  organization: GeoContentGapsResponseOrganization;
};

/** @internal */
export const PromptGapStatus$inboundSchema: z.ZodMiniType<
  PromptGapStatus,
  unknown
> = openEnums.inboundSchema(PromptGapStatus);

/** @internal */
export const PromptGapBaseline$inboundSchema: z.ZodMiniType<
  PromptGapBaseline,
  unknown
> = z.object({
  mentionedEngines: types.number(),
  totalEngines: types.number(),
});

export function promptGapBaselineFromJSON(
  jsonString: string,
): SafeParseResult<PromptGapBaseline, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PromptGapBaseline$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PromptGapBaseline' from JSON`,
  );
}

/** @internal */
export const PromptGapBrief$inboundSchema: z.ZodMiniType<
  PromptGapBrief,
  unknown
> = z.object({
  briefId: types.string(),
  status: PromptGapStatus$inboundSchema,
  postId: types.nullable(types.string()),
  workingTitle: types.nullable(types.string()),
  publishedAt: types.nullable(types.string()),
  baseline: types.nullable(z.lazy(() => PromptGapBaseline$inboundSchema)),
  rescanned: types.boolean(),
});

export function promptGapBriefFromJSON(
  jsonString: string,
): SafeParseResult<PromptGapBrief, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PromptGapBrief$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PromptGapBrief' from JSON`,
  );
}

/** @internal */
export const PromptGap$inboundSchema: z.ZodMiniType<PromptGap, unknown> = z
  .object({
    id: types.string(),
    prompt: types.string(),
    title: types.nullable(types.string()),
    engines: z.array(types.string()),
    mentionedEngines: z.array(types.string()),
    competitors: z.array(types.string()),
    discoveredCompetitors: z.array(types.string()),
    searchQueries: z.array(types.string()),
    ownMentionRate: types.number(),
    engineCoverage: types.number(),
    opportunity: types.number(),
    won: types.boolean(),
    brief: types.nullable(z.lazy(() => PromptGapBrief$inboundSchema)),
  });

export function promptGapFromJSON(
  jsonString: string,
): SafeParseResult<PromptGap, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PromptGap$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PromptGap' from JSON`,
  );
}

/** @internal */
export const Query$inboundSchema: z.ZodMiniType<Query, unknown> = z.object({
  query: types.string(),
  clicks: types.number(),
  impressions: types.number(),
  position: types.number(),
});

export function queryFromJSON(
  jsonString: string,
): SafeParseResult<Query, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Query$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Query' from JSON`,
  );
}

/** @internal */
export const SearchGapStatus$inboundSchema: z.ZodMiniType<
  SearchGapStatus,
  unknown
> = openEnums.inboundSchema(SearchGapStatus);

/** @internal */
export const SearchGapBaseline$inboundSchema: z.ZodMiniType<
  SearchGapBaseline,
  unknown
> = z.object({
  mentionedEngines: types.number(),
  totalEngines: types.number(),
});

export function searchGapBaselineFromJSON(
  jsonString: string,
): SafeParseResult<SearchGapBaseline, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchGapBaseline$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchGapBaseline' from JSON`,
  );
}

/** @internal */
export const SearchGapBrief$inboundSchema: z.ZodMiniType<
  SearchGapBrief,
  unknown
> = z.object({
  briefId: types.string(),
  status: SearchGapStatus$inboundSchema,
  postId: types.nullable(types.string()),
  workingTitle: types.nullable(types.string()),
  publishedAt: types.nullable(types.string()),
  baseline: types.nullable(z.lazy(() => SearchGapBaseline$inboundSchema)),
  rescanned: types.boolean(),
});

export function searchGapBriefFromJSON(
  jsonString: string,
): SafeParseResult<SearchGapBrief, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchGapBrief$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchGapBrief' from JSON`,
  );
}

/** @internal */
export const Action$inboundSchema: z.ZodMiniType<Action, unknown> = openEnums
  .inboundSchema(Action);

/** @internal */
export const GeoContentGapsResponseKind$inboundSchema: z.ZodMiniType<
  GeoContentGapsResponseKind,
  unknown
> = openEnums.inboundSchema(GeoContentGapsResponseKind);

/** @internal */
export const Target$inboundSchema: z.ZodMiniType<Target, unknown> = z.object({
  kind: GeoContentGapsResponseKind$inboundSchema,
  id: types.string(),
  url: types.nullable(types.string()),
  title: types.string(),
  score: types.number(),
});

export function targetFromJSON(
  jsonString: string,
): SafeParseResult<Target, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Target$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Target' from JSON`,
  );
}

/** @internal */
export const Recommendation$inboundSchema: z.ZodMiniType<
  Recommendation,
  unknown
> = z.object({
  action: Action$inboundSchema,
  reason: types.string(),
  targets: z.array(z.lazy(() => Target$inboundSchema)),
});

export function recommendationFromJSON(
  jsonString: string,
): SafeParseResult<Recommendation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Recommendation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Recommendation' from JSON`,
  );
}

/** @internal */
export const SearchGap$inboundSchema: z.ZodMiniType<SearchGap, unknown> = z
  .object({
    id: types.string(),
    prompt: types.string(),
    title: types.nullable(types.string()),
    impressions: types.nullable(types.number()),
    clicks: types.nullable(types.number()),
    position: types.nullable(types.number()),
    queries: z.array(z.lazy(() => Query$inboundSchema)),
    brief: types.nullable(z.lazy(() => SearchGapBrief$inboundSchema)),
    recommendation: z.lazy(() => Recommendation$inboundSchema),
  });

export function searchGapFromJSON(
  jsonString: string,
): SafeParseResult<SearchGap, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchGap$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchGap' from JSON`,
  );
}

/** @internal */
export const AiSearchGapStatus$inboundSchema: z.ZodMiniType<
  AiSearchGapStatus,
  unknown
> = openEnums.inboundSchema(AiSearchGapStatus);

/** @internal */
export const AiSearchGapBaseline$inboundSchema: z.ZodMiniType<
  AiSearchGapBaseline,
  unknown
> = z.object({
  mentionedEngines: types.number(),
  totalEngines: types.number(),
});

export function aiSearchGapBaselineFromJSON(
  jsonString: string,
): SafeParseResult<AiSearchGapBaseline, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AiSearchGapBaseline$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AiSearchGapBaseline' from JSON`,
  );
}

/** @internal */
export const AiSearchGapBrief$inboundSchema: z.ZodMiniType<
  AiSearchGapBrief,
  unknown
> = z.object({
  briefId: types.string(),
  status: AiSearchGapStatus$inboundSchema,
  postId: types.nullable(types.string()),
  workingTitle: types.nullable(types.string()),
  publishedAt: types.nullable(types.string()),
  baseline: types.nullable(z.lazy(() => AiSearchGapBaseline$inboundSchema)),
  rescanned: types.boolean(),
});

export function aiSearchGapBriefFromJSON(
  jsonString: string,
): SafeParseResult<AiSearchGapBrief, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AiSearchGapBrief$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AiSearchGapBrief' from JSON`,
  );
}

/** @internal */
export const AiSearchGap$inboundSchema: z.ZodMiniType<AiSearchGap, unknown> = z
  .object({
    id: types.string(),
    query: types.string(),
    variants: z.array(types.string()),
    prompts: z.array(types.string()),
    engines: z.array(types.string()),
    searches: types.number(),
    ownMentionRate: types.number(),
    competitors: z.array(types.string()),
    discoveredCompetitors: z.array(types.string()),
    opportunity: types.number(),
    brief: types.nullable(z.lazy(() => AiSearchGapBrief$inboundSchema)),
  });

export function aiSearchGapFromJSON(
  jsonString: string,
): SafeParseResult<AiSearchGap, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AiSearchGap$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AiSearchGap' from JSON`,
  );
}

/** @internal */
export const GeoContentGapsResponseOrganization$inboundSchema: z.ZodMiniType<
  GeoContentGapsResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function geoContentGapsResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoContentGapsResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeoContentGapsResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoContentGapsResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoContentGapsResponse$inboundSchema: z.ZodMiniType<
  GeoContentGapsResponse,
  unknown
> = z.object({
  promptGaps: z.array(z.lazy(() => PromptGap$inboundSchema)),
  searchGaps: z.array(z.lazy(() => SearchGap$inboundSchema)),
  aiSearchGaps: z.array(z.lazy(() => AiSearchGap$inboundSchema)),
  hasScanData: types.boolean(),
  organization: z.lazy(() => GeoContentGapsResponseOrganization$inboundSchema),
});

export function geoContentGapsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoContentGapsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoContentGapsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoContentGapsResponse' from JSON`,
  );
}
