/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b315425d5d68
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { GeoSettings, GeoSettings$inboundSchema } from "./geo-settings.js";

export type GeoSettingsResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoSettingsResponse = {
  /**
   * Whether the analytics backend is configured.
   */
  configured: boolean;
  settings: GeoSettings | null;
  organization: GeoSettingsResponseOrganization;
};

/** @internal */
export const GeoSettingsResponseOrganization$inboundSchema: z.ZodMiniType<
  GeoSettingsResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function geoSettingsResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoSettingsResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoSettingsResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoSettingsResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoSettingsResponse$inboundSchema: z.ZodMiniType<
  GeoSettingsResponse,
  unknown
> = z.object({
  configured: types.boolean(),
  settings: types.nullable(GeoSettings$inboundSchema),
  organization: z.lazy(() => GeoSettingsResponseOrganization$inboundSchema),
});

export function geoSettingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoSettingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoSettingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoSettingsResponse' from JSON`,
  );
}
