/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0c18d9fd9383
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GeoAgentReadinessReportStatus = {
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
export type GeoAgentReadinessReportStatus = OpenEnum<
  typeof GeoAgentReadinessReportStatus
>;

export type Essential = {
  earned: number;
  available: number;
  passing: number;
  total: number;
};

export type Recommended = {
  earned: number;
  available: number;
  passing: number;
  total: number;
};

export type Bonus = {
  points: number;
  positiveSignals: number;
};

export type ScoreBreakdown = {
  essential: Essential;
  recommended: Recommended;
  bonus: Bonus;
};

export const Tier = {
  Essential: "essential",
  Recommended: "recommended",
  Bonus: "bonus",
} as const;
export type Tier = OpenEnum<typeof Tier>;

export const ResultEnum = {
  Failed: "failed",
  Partial: "partial",
} as const;
export type ResultEnum = OpenEnum<typeof ResultEnum>;

export type GeoAgentReadinessReportIssue = {
  id: string;
  name: string;
  tier: Tier;
  result: ResultEnum;
  details: string | null;
  recommendation: string | null;
};

/**
 * Latest completed report, if any.
 */
export type GeoAgentReadinessReport = {
  id: string;
  status: GeoAgentReadinessReportStatus;
  targetUrl: string;
  score: number | null;
  scoreLabel: string | null;
  scoreBreakdown: ScoreBreakdown | null;
  issues: Array<GeoAgentReadinessReportIssue>;
  eligibleChecks: number | null;
  reportUrl: string | null;
  errorMessage: string | null;
  scannedAt: string | null;
  createdAt: string;
};

/** @internal */
export const GeoAgentReadinessReportStatus$inboundSchema: z.ZodMiniType<
  GeoAgentReadinessReportStatus,
  unknown
> = openEnums.inboundSchema(GeoAgentReadinessReportStatus);

/** @internal */
export const Essential$inboundSchema: z.ZodMiniType<Essential, unknown> = z
  .object({
    earned: types.number(),
    available: types.number(),
    passing: types.number(),
    total: types.number(),
  });

export function essentialFromJSON(
  jsonString: string,
): SafeParseResult<Essential, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Essential$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Essential' from JSON`,
  );
}

/** @internal */
export const Recommended$inboundSchema: z.ZodMiniType<Recommended, unknown> = z
  .object({
    earned: types.number(),
    available: types.number(),
    passing: types.number(),
    total: types.number(),
  });

export function recommendedFromJSON(
  jsonString: string,
): SafeParseResult<Recommended, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Recommended$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Recommended' from JSON`,
  );
}

/** @internal */
export const Bonus$inboundSchema: z.ZodMiniType<Bonus, unknown> = z.object({
  points: types.number(),
  positiveSignals: types.number(),
});

export function bonusFromJSON(
  jsonString: string,
): SafeParseResult<Bonus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Bonus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Bonus' from JSON`,
  );
}

/** @internal */
export const ScoreBreakdown$inboundSchema: z.ZodMiniType<
  ScoreBreakdown,
  unknown
> = z.object({
  essential: z.lazy(() => Essential$inboundSchema),
  recommended: z.lazy(() => Recommended$inboundSchema),
  bonus: z.lazy(() => Bonus$inboundSchema),
});

export function scoreBreakdownFromJSON(
  jsonString: string,
): SafeParseResult<ScoreBreakdown, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScoreBreakdown$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScoreBreakdown' from JSON`,
  );
}

/** @internal */
export const Tier$inboundSchema: z.ZodMiniType<Tier, unknown> = openEnums
  .inboundSchema(Tier);

/** @internal */
export const ResultEnum$inboundSchema: z.ZodMiniType<ResultEnum, unknown> =
  openEnums.inboundSchema(ResultEnum);

/** @internal */
export const GeoAgentReadinessReportIssue$inboundSchema: z.ZodMiniType<
  GeoAgentReadinessReportIssue,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  tier: Tier$inboundSchema,
  result: ResultEnum$inboundSchema,
  details: types.nullable(types.string()),
  recommendation: types.nullable(types.string()),
});

export function geoAgentReadinessReportIssueFromJSON(
  jsonString: string,
): SafeParseResult<GeoAgentReadinessReportIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoAgentReadinessReportIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoAgentReadinessReportIssue' from JSON`,
  );
}

/** @internal */
export const GeoAgentReadinessReport$inboundSchema: z.ZodMiniType<
  GeoAgentReadinessReport,
  unknown
> = z.object({
  id: types.string(),
  status: GeoAgentReadinessReportStatus$inboundSchema,
  targetUrl: types.string(),
  score: types.nullable(types.number()),
  scoreLabel: types.nullable(types.string()),
  scoreBreakdown: types.nullable(z.lazy(() => ScoreBreakdown$inboundSchema)),
  issues: z.array(z.lazy(() => GeoAgentReadinessReportIssue$inboundSchema)),
  eligibleChecks: types.nullable(types.number()),
  reportUrl: types.nullable(types.string()),
  errorMessage: types.nullable(types.string()),
  scannedAt: types.nullable(types.string()),
  createdAt: types.string(),
});

export function geoAgentReadinessReportFromJSON(
  jsonString: string,
): SafeParseResult<GeoAgentReadinessReport, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoAgentReadinessReport$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoAgentReadinessReport' from JSON`,
  );
}
