/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6a9f5cce1e95
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GeoPromptSource = {
  Custom: "custom",
  Auto: "auto",
} as const;
export type GeoPromptSource = OpenEnum<typeof GeoPromptSource>;

export type GeoPrompt = {
  id: string;
  prompt: string;
  enabled: boolean;
  source: GeoPromptSource;
  createdAt: string | null;
};

/** @internal */
export const GeoPromptSource$inboundSchema: z.ZodMiniType<
  GeoPromptSource,
  unknown
> = openEnums.inboundSchema(GeoPromptSource);

/** @internal */
export const GeoPrompt$inboundSchema: z.ZodMiniType<GeoPrompt, unknown> = z
  .object({
    id: types.string(),
    prompt: types.string(),
    enabled: types.boolean(),
    source: GeoPromptSource$inboundSchema,
    createdAt: types.nullable(types.string()),
  });

export function geoPromptFromJSON(
  jsonString: string,
): SafeParseResult<GeoPrompt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoPrompt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoPrompt' from JSON`,
  );
}
