/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9d38fca29039
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GeoTrafficJourneysResponseVisitorType = {
  Crawler: "crawler",
  AiReferral: "ai_referral",
  Human: "human",
  Unknown: "unknown",
} as const;
export type GeoTrafficJourneysResponseVisitorType = OpenEnum<
  typeof GeoTrafficJourneysResponseVisitorType
>;

export type Journey = {
  journeyId: string;
  source: string;
  visitorType: GeoTrafficJourneysResponseVisitorType;
  pages: number;
  distinctPaths: number;
  firstSeenAt: string;
  lastSeenAt: string;
  samplePaths: Array<string>;
};

export type GeoTrafficJourneysResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type GeoTrafficJourneysResponse = {
  /**
   * False when the traffic backend is not configured for this deployment; the payload is then empty rather than an error.
   */
  configured: boolean;
  journeys: Array<Journey>;
  organization: GeoTrafficJourneysResponseOrganization;
};

/** @internal */
export const GeoTrafficJourneysResponseVisitorType$inboundSchema: z.ZodMiniType<
  GeoTrafficJourneysResponseVisitorType,
  unknown
> = openEnums.inboundSchema(GeoTrafficJourneysResponseVisitorType);

/** @internal */
export const Journey$inboundSchema: z.ZodMiniType<Journey, unknown> = z.object({
  journeyId: types.string(),
  source: types.string(),
  visitorType: GeoTrafficJourneysResponseVisitorType$inboundSchema,
  pages: types.number(),
  distinctPaths: types.number(),
  firstSeenAt: types.string(),
  lastSeenAt: types.string(),
  samplePaths: z.array(types.string()),
});

export function journeyFromJSON(
  jsonString: string,
): SafeParseResult<Journey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Journey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Journey' from JSON`,
  );
}

/** @internal */
export const GeoTrafficJourneysResponseOrganization$inboundSchema:
  z.ZodMiniType<GeoTrafficJourneysResponseOrganization, unknown> = z.object({
    id: types.string(),
    slug: types.string(),
    name: types.string(),
    logo: types.nullable(types.string()),
  });

export function geoTrafficJourneysResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GeoTrafficJourneysResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeoTrafficJourneysResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoTrafficJourneysResponseOrganization' from JSON`,
  );
}

/** @internal */
export const GeoTrafficJourneysResponse$inboundSchema: z.ZodMiniType<
  GeoTrafficJourneysResponse,
  unknown
> = z.object({
  configured: types.boolean(),
  journeys: z.array(z.lazy(() => Journey$inboundSchema)),
  organization: z.lazy(() =>
    GeoTrafficJourneysResponseOrganization$inboundSchema
  ),
});

export function geoTrafficJourneysResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeoTrafficJourneysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeoTrafficJourneysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeoTrafficJourneysResponse' from JSON`,
  );
}
