/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7d9b4742844b
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type CurrentWorkspace = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export const GetWorkspacesResponseStatus = {
  Active: "active",
  Pending: "pending",
} as const;
export type GetWorkspacesResponseStatus = OpenEnum<
  typeof GetWorkspacesResponseStatus
>;

export type Workspace = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
  role: string | null;
  status: GetWorkspacesResponseStatus;
  isCurrent: boolean;
};

export type AuthenticationOauth = {
  type: "oauth";
  accountId: string;
  scopes: Array<string>;
};

export type AuthenticationAPIKey = {
  type: "apiKey";
};

export type Authentication =
  | AuthenticationAPIKey
  | AuthenticationOauth
  | discriminatedUnionTypes.Unknown<"type">;

export type GetWorkspacesResponse = {
  currentWorkspace: CurrentWorkspace;
  workspaces: Array<Workspace>;
  authentication:
    | AuthenticationAPIKey
    | AuthenticationOauth
    | discriminatedUnionTypes.Unknown<"type">;
};

/** @internal */
export const CurrentWorkspace$inboundSchema: z.ZodMiniType<
  CurrentWorkspace,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function currentWorkspaceFromJSON(
  jsonString: string,
): SafeParseResult<CurrentWorkspace, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CurrentWorkspace$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CurrentWorkspace' from JSON`,
  );
}

/** @internal */
export const GetWorkspacesResponseStatus$inboundSchema: z.ZodMiniType<
  GetWorkspacesResponseStatus,
  unknown
> = openEnums.inboundSchema(GetWorkspacesResponseStatus);

/** @internal */
export const Workspace$inboundSchema: z.ZodMiniType<Workspace, unknown> = z
  .object({
    id: types.string(),
    slug: types.string(),
    name: types.string(),
    logo: types.nullable(types.string()),
    role: types.nullable(types.string()),
    status: GetWorkspacesResponseStatus$inboundSchema,
    isCurrent: types.boolean(),
  });

export function workspaceFromJSON(
  jsonString: string,
): SafeParseResult<Workspace, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Workspace$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Workspace' from JSON`,
  );
}

/** @internal */
export const AuthenticationOauth$inboundSchema: z.ZodMiniType<
  AuthenticationOauth,
  unknown
> = z.object({
  type: types.literal("oauth"),
  accountId: types.string(),
  scopes: z.array(types.string()),
});

export function authenticationOauthFromJSON(
  jsonString: string,
): SafeParseResult<AuthenticationOauth, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthenticationOauth$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthenticationOauth' from JSON`,
  );
}

/** @internal */
export const AuthenticationAPIKey$inboundSchema: z.ZodMiniType<
  AuthenticationAPIKey,
  unknown
> = z.object({
  type: types.literal("apiKey"),
});

export function authenticationAPIKeyFromJSON(
  jsonString: string,
): SafeParseResult<AuthenticationAPIKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthenticationAPIKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthenticationAPIKey' from JSON`,
  );
}

/** @internal */
export const Authentication$inboundSchema: z.ZodMiniType<
  Authentication,
  unknown
> = discriminatedUnion("type", {
  apiKey: z.lazy(() => AuthenticationAPIKey$inboundSchema),
  oauth: z.lazy(() => AuthenticationOauth$inboundSchema),
});

export function authenticationFromJSON(
  jsonString: string,
): SafeParseResult<Authentication, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Authentication$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Authentication' from JSON`,
  );
}

/** @internal */
export const GetWorkspacesResponse$inboundSchema: z.ZodMiniType<
  GetWorkspacesResponse,
  unknown
> = z.object({
  currentWorkspace: z.lazy(() => CurrentWorkspace$inboundSchema),
  workspaces: z.array(z.lazy(() => Workspace$inboundSchema)),
  authentication: discriminatedUnion("type", {
    apiKey: z.lazy(() => AuthenticationAPIKey$inboundSchema),
    oauth: z.lazy(() => AuthenticationOauth$inboundSchema),
  }),
});

export function getWorkspacesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWorkspacesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWorkspacesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWorkspacesResponse' from JSON`,
  );
}
