/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: edbb8bb3b1f4
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  GeoCompetitor,
  GeoCompetitor$inboundSchema,
} from "./geo-competitor.js";

export type ImportGeoCompetitorsResponseIssue = {
  line: number;
  message: string;
};

export type ImportGeoCompetitorsResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type ImportGeoCompetitorsResponse = {
  imported: number;
  updated: number;
  skipped: number;
  issues: Array<ImportGeoCompetitorsResponseIssue>;
  competitors: Array<GeoCompetitor>;
  organization: ImportGeoCompetitorsResponseOrganization;
};

/** @internal */
export const ImportGeoCompetitorsResponseIssue$inboundSchema: z.ZodMiniType<
  ImportGeoCompetitorsResponseIssue,
  unknown
> = z.object({
  line: types.number(),
  message: types.string(),
});

export function importGeoCompetitorsResponseIssueFromJSON(
  jsonString: string,
): SafeParseResult<ImportGeoCompetitorsResponseIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImportGeoCompetitorsResponseIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImportGeoCompetitorsResponseIssue' from JSON`,
  );
}

/** @internal */
export const ImportGeoCompetitorsResponseOrganization$inboundSchema:
  z.ZodMiniType<ImportGeoCompetitorsResponseOrganization, unknown> = z.object({
    id: types.string(),
    slug: types.string(),
    name: types.string(),
    logo: types.nullable(types.string()),
  });

export function importGeoCompetitorsResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<
  ImportGeoCompetitorsResponseOrganization,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ImportGeoCompetitorsResponseOrganization$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ImportGeoCompetitorsResponseOrganization' from JSON`,
  );
}

/** @internal */
export const ImportGeoCompetitorsResponse$inboundSchema: z.ZodMiniType<
  ImportGeoCompetitorsResponse,
  unknown
> = z.object({
  imported: types.number(),
  updated: types.number(),
  skipped: types.number(),
  issues: z.array(
    z.lazy(() => ImportGeoCompetitorsResponseIssue$inboundSchema),
  ),
  competitors: z.array(GeoCompetitor$inboundSchema),
  organization: z.lazy(() =>
    ImportGeoCompetitorsResponseOrganization$inboundSchema
  ),
});

export function importGeoCompetitorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ImportGeoCompetitorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImportGeoCompetitorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImportGeoCompetitorsResponse' from JSON`,
  );
}
