/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: df41fc2849a8
 */

import * as z from "zod/v4-mini";

export type ImportGeoPromptsRequestRow = {
  prompt: string;
  enabled?: boolean | undefined;
};

export type ImportGeoPromptsRequest = {
  rows?: Array<ImportGeoPromptsRequestRow> | undefined;
  /**
   * Raw CSV text with a `prompt` column (optionally `enabled`). Used when `rows` is omitted.
   */
  csv?: string | undefined;
};

/** @internal */
export type ImportGeoPromptsRequestRow$Outbound = {
  prompt: string;
  enabled?: boolean | undefined;
};

/** @internal */
export const ImportGeoPromptsRequestRow$outboundSchema: z.ZodMiniType<
  ImportGeoPromptsRequestRow$Outbound,
  ImportGeoPromptsRequestRow
> = z.object({
  prompt: z.string(),
  enabled: z.optional(z.boolean()),
});

export function importGeoPromptsRequestRowToJSON(
  importGeoPromptsRequestRow: ImportGeoPromptsRequestRow,
): string {
  return JSON.stringify(
    ImportGeoPromptsRequestRow$outboundSchema.parse(importGeoPromptsRequestRow),
  );
}

/** @internal */
export type ImportGeoPromptsRequest$Outbound = {
  rows?: Array<ImportGeoPromptsRequestRow$Outbound> | undefined;
  csv?: string | undefined;
};

/** @internal */
export const ImportGeoPromptsRequest$outboundSchema: z.ZodMiniType<
  ImportGeoPromptsRequest$Outbound,
  ImportGeoPromptsRequest
> = z.object({
  rows: z.optional(
    z.array(z.lazy(() => ImportGeoPromptsRequestRow$outboundSchema)),
  ),
  csv: z.optional(z.string()),
});

export function importGeoPromptsRequestToJSON(
  importGeoPromptsRequest: ImportGeoPromptsRequest,
): string {
  return JSON.stringify(
    ImportGeoPromptsRequest$outboundSchema.parse(importGeoPromptsRequest),
  );
}
