/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 88f3919edef0
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const ImportGeoCompetitorsRequestKind = {
  Direct: "direct",
  Indirect: "indirect",
} as const;
export type ImportGeoCompetitorsRequestKind = ClosedEnum<
  typeof ImportGeoCompetitorsRequestKind
>;

export type ImportGeoCompetitorsRequestRow = {
  name: string;
  domain?: string | null | undefined;
  kind?: ImportGeoCompetitorsRequestKind | undefined;
  synonyms?: Array<string> | undefined;
};

export type ImportGeoCompetitorsRequest = {
  rows?: Array<ImportGeoCompetitorsRequestRow> | undefined;
  /**
   * Raw CSV text with a `name` column (optionally `domain`, `kind`, `synonyms`). Used when `rows` is omitted.
   */
  csv?: string | undefined;
};

/** @internal */
export const ImportGeoCompetitorsRequestKind$outboundSchema: z.ZodMiniEnum<
  typeof ImportGeoCompetitorsRequestKind
> = z.enum(ImportGeoCompetitorsRequestKind);

/** @internal */
export type ImportGeoCompetitorsRequestRow$Outbound = {
  name: string;
  domain?: string | null | undefined;
  kind?: string | undefined;
  synonyms?: Array<string> | undefined;
};

/** @internal */
export const ImportGeoCompetitorsRequestRow$outboundSchema: z.ZodMiniType<
  ImportGeoCompetitorsRequestRow$Outbound,
  ImportGeoCompetitorsRequestRow
> = z.object({
  name: z.string(),
  domain: z.optional(z.nullable(z.string())),
  kind: z.optional(ImportGeoCompetitorsRequestKind$outboundSchema),
  synonyms: z.optional(z.array(z.string())),
});

export function importGeoCompetitorsRequestRowToJSON(
  importGeoCompetitorsRequestRow: ImportGeoCompetitorsRequestRow,
): string {
  return JSON.stringify(
    ImportGeoCompetitorsRequestRow$outboundSchema.parse(
      importGeoCompetitorsRequestRow,
    ),
  );
}

/** @internal */
export type ImportGeoCompetitorsRequest$Outbound = {
  rows?: Array<ImportGeoCompetitorsRequestRow$Outbound> | undefined;
  csv?: string | undefined;
};

/** @internal */
export const ImportGeoCompetitorsRequest$outboundSchema: z.ZodMiniType<
  ImportGeoCompetitorsRequest$Outbound,
  ImportGeoCompetitorsRequest
> = z.object({
  rows: z.optional(
    z.array(z.lazy(() => ImportGeoCompetitorsRequestRow$outboundSchema)),
  ),
  csv: z.optional(z.string()),
});

export function importGeoCompetitorsRequestToJSON(
  importGeoCompetitorsRequest: ImportGeoCompetitorsRequest,
): string {
  return JSON.stringify(
    ImportGeoCompetitorsRequest$outboundSchema.parse(
      importGeoCompetitorsRequest,
    ),
  );
}
