/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c7343a75701f
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { GeoPrompt, GeoPrompt$inboundSchema } from "./geo-prompt.js";

export type ListGeoPromptsResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type ListGeoPromptsResponse = {
  configured: boolean;
  prompts: Array<GeoPrompt>;
  organization: ListGeoPromptsResponseOrganization;
};

/** @internal */
export const ListGeoPromptsResponseOrganization$inboundSchema: z.ZodMiniType<
  ListGeoPromptsResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function listGeoPromptsResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<ListGeoPromptsResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListGeoPromptsResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGeoPromptsResponseOrganization' from JSON`,
  );
}

/** @internal */
export const ListGeoPromptsResponse$inboundSchema: z.ZodMiniType<
  ListGeoPromptsResponse,
  unknown
> = z.object({
  configured: types.boolean(),
  prompts: z.array(GeoPrompt$inboundSchema),
  organization: z.lazy(() => ListGeoPromptsResponseOrganization$inboundSchema),
});

export function listGeoPromptsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListGeoPromptsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListGeoPromptsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGeoPromptsResponse' from JSON`,
  );
}
