/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f4adb449c062
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  GeoCompetitor,
  GeoCompetitor$inboundSchema,
} from "./geo-competitor.js";

export type ListGeoCompetitorsResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type ListGeoCompetitorsResponse = {
  competitors: Array<GeoCompetitor>;
  organization: ListGeoCompetitorsResponseOrganization;
};

/** @internal */
export const ListGeoCompetitorsResponseOrganization$inboundSchema:
  z.ZodMiniType<ListGeoCompetitorsResponseOrganization, unknown> = z.object({
    id: types.string(),
    slug: types.string(),
    name: types.string(),
    logo: types.nullable(types.string()),
  });

export function listGeoCompetitorsResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<ListGeoCompetitorsResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListGeoCompetitorsResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGeoCompetitorsResponseOrganization' from JSON`,
  );
}

/** @internal */
export const ListGeoCompetitorsResponse$inboundSchema: z.ZodMiniType<
  ListGeoCompetitorsResponse,
  unknown
> = z.object({
  competitors: z.array(GeoCompetitor$inboundSchema),
  organization: z.lazy(() =>
    ListGeoCompetitorsResponseOrganization$inboundSchema
  ),
});

export function listGeoCompetitorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListGeoCompetitorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListGeoCompetitorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGeoCompetitorsResponse' from JSON`,
  );
}
