/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0449dc7b7823
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AgentSessionSummary,
  AgentSessionSummary$inboundSchema,
} from "./agent-session-summary.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ListAgentChatsResponse = {
  sessions: Array<AgentSessionSummary>;
};

/** @internal */
export const ListAgentChatsResponse$inboundSchema: z.ZodMiniType<
  ListAgentChatsResponse,
  unknown
> = z.object({
  sessions: z.array(AgentSessionSummary$inboundSchema),
});

export function listAgentChatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAgentChatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAgentChatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAgentChatsResponse' from JSON`,
  );
}
