/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a0b87bd84559
 */

import * as z from "zod/v4-mini";

export type PatchSkillRequest = {
  /**
   * Skill name. Lowercase letters, digits, and hyphens only.
   */
  name?: string | undefined;
  /**
   * Short description of when the skill should be used.
   */
  description?: string | undefined;
  /**
   * Full skill instructions, typically Markdown.
   */
  content?: string | undefined;
};

/** @internal */
export type PatchSkillRequest$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
  content?: string | undefined;
};

/** @internal */
export const PatchSkillRequest$outboundSchema: z.ZodMiniType<
  PatchSkillRequest$Outbound,
  PatchSkillRequest
> = z.object({
  name: z.optional(z.string()),
  description: z.optional(z.string()),
  content: z.optional(z.string()),
});

export function patchSkillRequestToJSON(
  patchSkillRequest: PatchSkillRequest,
): string {
  return JSON.stringify(
    PatchSkillRequest$outboundSchema.parse(patchSkillRequest),
  );
}
