/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: be9fbc050af1
 */

import * as z from "zod/v4-mini";

export type PatchGeoPromptRequest = {
  enabled: boolean;
};

/** @internal */
export type PatchGeoPromptRequest$Outbound = {
  enabled: boolean;
};

/** @internal */
export const PatchGeoPromptRequest$outboundSchema: z.ZodMiniType<
  PatchGeoPromptRequest$Outbound,
  PatchGeoPromptRequest
> = z.object({
  enabled: z.boolean(),
});

export function patchGeoPromptRequestToJSON(
  patchGeoPromptRequest: PatchGeoPromptRequest,
): string {
  return JSON.stringify(
    PatchGeoPromptRequest$outboundSchema.parse(patchGeoPromptRequest),
  );
}
