/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 531ca59f85e3
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const PatchScheduleRequestSourceType = {
  Cron: "cron",
} as const;
export type PatchScheduleRequestSourceType = ClosedEnum<
  typeof PatchScheduleRequestSourceType
>;

export const Frequency = {
  Daily: "daily",
  Weekly: "weekly",
  Monthly: "monthly",
} as const;
export type Frequency = ClosedEnum<typeof Frequency>;

export type Cron = {
  frequency: Frequency;
  hour: number;
  minute: number;
  dayOfWeek?: number | undefined;
  dayOfMonth?: number | undefined;
};

export type PatchScheduleRequestSourceConfig = {
  cron: Cron;
};

export type PatchScheduleRequestTargets = {
  repositoryIds: Array<string>;
};

export const PatchScheduleRequestOutputType = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
  Image: "image",
} as const;
export type PatchScheduleRequestOutputType = ClosedEnum<
  typeof PatchScheduleRequestOutputType
>;

export const PatchScheduleRequestPublishDestination = {
  Webflow: "webflow",
  Framer: "framer",
  Custom: "custom",
} as const;
export type PatchScheduleRequestPublishDestination = ClosedEnum<
  typeof PatchScheduleRequestPublishDestination
>;

export type PatchScheduleRequestOutputConfig = {
  publishDestination?: PatchScheduleRequestPublishDestination | undefined;
  brandVoiceId?: string | undefined;
};

export const LookbackWindow = {
  CurrentDay: "current_day",
  Yesterday: "yesterday",
  Last7Days: "last_7_days",
  Last14Days: "last_14_days",
  Last30Days: "last_30_days",
} as const;
export type LookbackWindow = ClosedEnum<typeof LookbackWindow>;

export type PatchScheduleRequest = {
  name: string;
  sourceType: PatchScheduleRequestSourceType;
  sourceConfig: PatchScheduleRequestSourceConfig;
  targets: PatchScheduleRequestTargets;
  outputType: PatchScheduleRequestOutputType;
  outputConfig?: PatchScheduleRequestOutputConfig | undefined;
  enabled: boolean;
  autoPublish?: boolean | undefined;
  lookbackWindow?: LookbackWindow | undefined;
};

/** @internal */
export const PatchScheduleRequestSourceType$outboundSchema: z.ZodMiniEnum<
  typeof PatchScheduleRequestSourceType
> = z.enum(PatchScheduleRequestSourceType);

/** @internal */
export const Frequency$outboundSchema: z.ZodMiniEnum<typeof Frequency> = z.enum(
  Frequency,
);

/** @internal */
export type Cron$Outbound = {
  frequency: string;
  hour: number;
  minute: number;
  dayOfWeek?: number | undefined;
  dayOfMonth?: number | undefined;
};

/** @internal */
export const Cron$outboundSchema: z.ZodMiniType<Cron$Outbound, Cron> = z.object(
  {
    frequency: Frequency$outboundSchema,
    hour: z.int(),
    minute: z.int(),
    dayOfWeek: z.optional(z.int()),
    dayOfMonth: z.optional(z.int()),
  },
);

export function cronToJSON(cron: Cron): string {
  return JSON.stringify(Cron$outboundSchema.parse(cron));
}

/** @internal */
export type PatchScheduleRequestSourceConfig$Outbound = {
  cron: Cron$Outbound;
};

/** @internal */
export const PatchScheduleRequestSourceConfig$outboundSchema: z.ZodMiniType<
  PatchScheduleRequestSourceConfig$Outbound,
  PatchScheduleRequestSourceConfig
> = z.object({
  cron: z.lazy(() => Cron$outboundSchema),
});

export function patchScheduleRequestSourceConfigToJSON(
  patchScheduleRequestSourceConfig: PatchScheduleRequestSourceConfig,
): string {
  return JSON.stringify(
    PatchScheduleRequestSourceConfig$outboundSchema.parse(
      patchScheduleRequestSourceConfig,
    ),
  );
}

/** @internal */
export type PatchScheduleRequestTargets$Outbound = {
  repositoryIds: Array<string>;
};

/** @internal */
export const PatchScheduleRequestTargets$outboundSchema: z.ZodMiniType<
  PatchScheduleRequestTargets$Outbound,
  PatchScheduleRequestTargets
> = z.object({
  repositoryIds: z.array(z.string()),
});

export function patchScheduleRequestTargetsToJSON(
  patchScheduleRequestTargets: PatchScheduleRequestTargets,
): string {
  return JSON.stringify(
    PatchScheduleRequestTargets$outboundSchema.parse(
      patchScheduleRequestTargets,
    ),
  );
}

/** @internal */
export const PatchScheduleRequestOutputType$outboundSchema: z.ZodMiniEnum<
  typeof PatchScheduleRequestOutputType
> = z.enum(PatchScheduleRequestOutputType);

/** @internal */
export const PatchScheduleRequestPublishDestination$outboundSchema:
  z.ZodMiniEnum<typeof PatchScheduleRequestPublishDestination> = z.enum(
    PatchScheduleRequestPublishDestination,
  );

/** @internal */
export type PatchScheduleRequestOutputConfig$Outbound = {
  publishDestination?: string | undefined;
  brandVoiceId?: string | undefined;
};

/** @internal */
export const PatchScheduleRequestOutputConfig$outboundSchema: z.ZodMiniType<
  PatchScheduleRequestOutputConfig$Outbound,
  PatchScheduleRequestOutputConfig
> = z.object({
  publishDestination: z.optional(
    PatchScheduleRequestPublishDestination$outboundSchema,
  ),
  brandVoiceId: z.optional(z.string()),
});

export function patchScheduleRequestOutputConfigToJSON(
  patchScheduleRequestOutputConfig: PatchScheduleRequestOutputConfig,
): string {
  return JSON.stringify(
    PatchScheduleRequestOutputConfig$outboundSchema.parse(
      patchScheduleRequestOutputConfig,
    ),
  );
}

/** @internal */
export const LookbackWindow$outboundSchema: z.ZodMiniEnum<
  typeof LookbackWindow
> = z.enum(LookbackWindow);

/** @internal */
export type PatchScheduleRequest$Outbound = {
  name: string;
  sourceType: string;
  sourceConfig: PatchScheduleRequestSourceConfig$Outbound;
  targets: PatchScheduleRequestTargets$Outbound;
  outputType: string;
  outputConfig?: PatchScheduleRequestOutputConfig$Outbound | undefined;
  enabled: boolean;
  autoPublish: boolean;
  lookbackWindow: string;
};

/** @internal */
export const PatchScheduleRequest$outboundSchema: z.ZodMiniType<
  PatchScheduleRequest$Outbound,
  PatchScheduleRequest
> = z.object({
  name: z.string(),
  sourceType: PatchScheduleRequestSourceType$outboundSchema,
  sourceConfig: z.lazy(() => PatchScheduleRequestSourceConfig$outboundSchema),
  targets: z.lazy(() => PatchScheduleRequestTargets$outboundSchema),
  outputType: PatchScheduleRequestOutputType$outboundSchema,
  outputConfig: z.optional(
    z.lazy(() => PatchScheduleRequestOutputConfig$outboundSchema),
  ),
  enabled: z.boolean(),
  autoPublish: z._default(z.boolean(), false),
  lookbackWindow: z._default(LookbackWindow$outboundSchema, "last_7_days"),
});

export function patchScheduleRequestToJSON(
  patchScheduleRequest: PatchScheduleRequest,
): string {
  return JSON.stringify(
    PatchScheduleRequest$outboundSchema.parse(patchScheduleRequest),
  );
}
