/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 725881d18685
 */

import * as z from "zod/v4-mini";

export type PatchGeoSequenceRequest = {
  name?: string | undefined;
  steps?: Array<string> | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export type PatchGeoSequenceRequest$Outbound = {
  name?: string | undefined;
  steps?: Array<string> | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export const PatchGeoSequenceRequest$outboundSchema: z.ZodMiniType<
  PatchGeoSequenceRequest$Outbound,
  PatchGeoSequenceRequest
> = z.object({
  name: z.optional(z.string()),
  steps: z.optional(z.array(z.string())),
  enabled: z.optional(z.boolean()),
});

export function patchGeoSequenceRequestToJSON(
  patchGeoSequenceRequest: PatchGeoSequenceRequest,
): string {
  return JSON.stringify(
    PatchGeoSequenceRequest$outboundSchema.parse(patchGeoSequenceRequest),
  );
}
