/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: af0e72b4357f
 */

import * as z from "zod/v4-mini";

export type PatchGeoSettingsRequest = {
  companyName: string;
  aliases: Array<string>;
  languages: Array<string>;
  engines: Array<string>;
  enforceZdr: boolean;
  nonZdrApprovedEngines: Array<string>;
  enabled: boolean;
  /**
   * 24, 48, 72, 168, 336, 720
   */
  scanIntervalHours: number;
};

/** @internal */
export type PatchGeoSettingsRequest$Outbound = {
  companyName: string;
  aliases: Array<string>;
  languages: Array<string>;
  engines: Array<string>;
  enforceZdr: boolean;
  nonZdrApprovedEngines: Array<string>;
  enabled: boolean;
  scanIntervalHours: number;
};

/** @internal */
export const PatchGeoSettingsRequest$outboundSchema: z.ZodMiniType<
  PatchGeoSettingsRequest$Outbound,
  PatchGeoSettingsRequest
> = z.object({
  companyName: z.string(),
  aliases: z.array(z.string()),
  languages: z.array(z.string()),
  engines: z.array(z.string()),
  enforceZdr: z.boolean(),
  nonZdrApprovedEngines: z.array(z.string()),
  enabled: z.boolean(),
  scanIntervalHours: z.int(),
});

export function patchGeoSettingsRequestToJSON(
  patchGeoSettingsRequest: PatchGeoSettingsRequest,
): string {
  return JSON.stringify(
    PatchGeoSettingsRequest$outboundSchema.parse(patchGeoSettingsRequest),
  );
}
