/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 531ca59f85e3
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const SourceType = {
  Cron: "cron",
} as const;
export type SourceType = ClosedEnum<typeof SourceType>;

export const Frequency = {
  Daily: "daily",
  Weekly: "weekly",
  Monthly: "monthly",
} as const;
export type Frequency = ClosedEnum<typeof Frequency>;

export type Cron = {
  frequency: Frequency;
  hour: number;
  minute: number;
  dayOfWeek?: number | undefined;
  dayOfMonth?: number | undefined;
};

export type SourceConfig = {
  cron: Cron;
};

export type Targets = {
  repositoryIds: Array<string>;
};

export const OutputType = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
  Image: "image",
} as const;
export type OutputType = ClosedEnum<typeof OutputType>;

export const PublishDestination = {
  Webflow: "webflow",
  Framer: "framer",
  Custom: "custom",
} as const;
export type PublishDestination = ClosedEnum<typeof PublishDestination>;

export type OutputConfig = {
  publishDestination?: PublishDestination | undefined;
  brandVoiceId?: string | undefined;
};

export const LookbackWindow = {
  CurrentDay: "current_day",
  Yesterday: "yesterday",
  Last7Days: "last_7_days",
  Last14Days: "last_14_days",
  Last30Days: "last_30_days",
} as const;
export type LookbackWindow = ClosedEnum<typeof LookbackWindow>;

export type PatchScheduleRequest = {
  name: string;
  sourceType: SourceType;
  sourceConfig: SourceConfig;
  targets: Targets;
  outputType: OutputType;
  outputConfig?: OutputConfig | undefined;
  enabled: boolean;
  autoPublish?: boolean | undefined;
  lookbackWindow?: LookbackWindow | undefined;
};

/** @internal */
export const SourceType$outboundSchema: z.ZodMiniEnum<typeof SourceType> = z
  .enum(SourceType);

/** @internal */
export const Frequency$outboundSchema: z.ZodMiniEnum<typeof Frequency> = z.enum(
  Frequency,
);

/** @internal */
export type Cron$Outbound = {
  frequency: string;
  hour: number;
  minute: number;
  dayOfWeek?: number | undefined;
  dayOfMonth?: number | undefined;
};

/** @internal */
export const Cron$outboundSchema: z.ZodMiniType<Cron$Outbound, Cron> = z.object(
  {
    frequency: Frequency$outboundSchema,
    hour: z.int(),
    minute: z.int(),
    dayOfWeek: z.optional(z.int()),
    dayOfMonth: z.optional(z.int()),
  },
);

export function cronToJSON(cron: Cron): string {
  return JSON.stringify(Cron$outboundSchema.parse(cron));
}

/** @internal */
export type SourceConfig$Outbound = {
  cron: Cron$Outbound;
};

/** @internal */
export const SourceConfig$outboundSchema: z.ZodMiniType<
  SourceConfig$Outbound,
  SourceConfig
> = z.object({
  cron: z.lazy(() => Cron$outboundSchema),
});

export function sourceConfigToJSON(sourceConfig: SourceConfig): string {
  return JSON.stringify(SourceConfig$outboundSchema.parse(sourceConfig));
}

/** @internal */
export type Targets$Outbound = {
  repositoryIds: Array<string>;
};

/** @internal */
export const Targets$outboundSchema: z.ZodMiniType<Targets$Outbound, Targets> =
  z.object({
    repositoryIds: z.array(z.string()),
  });

export function targetsToJSON(targets: Targets): string {
  return JSON.stringify(Targets$outboundSchema.parse(targets));
}

/** @internal */
export const OutputType$outboundSchema: z.ZodMiniEnum<typeof OutputType> = z
  .enum(OutputType);

/** @internal */
export const PublishDestination$outboundSchema: z.ZodMiniEnum<
  typeof PublishDestination
> = z.enum(PublishDestination);

/** @internal */
export type OutputConfig$Outbound = {
  publishDestination?: string | undefined;
  brandVoiceId?: string | undefined;
};

/** @internal */
export const OutputConfig$outboundSchema: z.ZodMiniType<
  OutputConfig$Outbound,
  OutputConfig
> = z.object({
  publishDestination: z.optional(PublishDestination$outboundSchema),
  brandVoiceId: z.optional(z.string()),
});

export function outputConfigToJSON(outputConfig: OutputConfig): string {
  return JSON.stringify(OutputConfig$outboundSchema.parse(outputConfig));
}

/** @internal */
export const LookbackWindow$outboundSchema: z.ZodMiniEnum<
  typeof LookbackWindow
> = z.enum(LookbackWindow);

/** @internal */
export type PatchScheduleRequest$Outbound = {
  name: string;
  sourceType: string;
  sourceConfig: SourceConfig$Outbound;
  targets: Targets$Outbound;
  outputType: string;
  outputConfig?: OutputConfig$Outbound | undefined;
  enabled: boolean;
  autoPublish: boolean;
  lookbackWindow: string;
};

/** @internal */
export const PatchScheduleRequest$outboundSchema: z.ZodMiniType<
  PatchScheduleRequest$Outbound,
  PatchScheduleRequest
> = z.object({
  name: z.string(),
  sourceType: SourceType$outboundSchema,
  sourceConfig: z.lazy(() => SourceConfig$outboundSchema),
  targets: z.lazy(() => Targets$outboundSchema),
  outputType: OutputType$outboundSchema,
  outputConfig: z.optional(z.lazy(() => OutputConfig$outboundSchema)),
  enabled: z.boolean(),
  autoPublish: z._default(z.boolean(), false),
  lookbackWindow: z._default(LookbackWindow$outboundSchema, "last_7_days"),
});

export function patchScheduleRequestToJSON(
  patchScheduleRequest: PatchScheduleRequest,
): string {
  return JSON.stringify(
    PatchScheduleRequest$outboundSchema.parse(patchScheduleRequest),
  );
}
