/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 63d570f32edd
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const PatchEventTriggerRequestSourceType = {
  GithubWebhook: "github_webhook",
} as const;
export type PatchEventTriggerRequestSourceType = ClosedEnum<
  typeof PatchEventTriggerRequestSourceType
>;

export const EventType = {
  Release: "release",
  Push: "push",
} as const;
export type EventType = ClosedEnum<typeof EventType>;

export type PatchEventTriggerRequestSourceConfig = {
  eventTypes: Array<EventType>;
  includePreReleases?: boolean | undefined;
};

export type PatchEventTriggerRequestTargets = {
  repositoryIds: Array<string>;
};

export const PatchEventTriggerRequestOutputType = {
  Changelog: "changelog",
  BlogPost: "blog_post",
  LinkedinPost: "linkedin_post",
  TwitterPost: "twitter_post",
  Image: "image",
} as const;
export type PatchEventTriggerRequestOutputType = ClosedEnum<
  typeof PatchEventTriggerRequestOutputType
>;

export const PatchEventTriggerRequestPublishDestination = {
  Webflow: "webflow",
  Framer: "framer",
  Custom: "custom",
} as const;
export type PatchEventTriggerRequestPublishDestination = ClosedEnum<
  typeof PatchEventTriggerRequestPublishDestination
>;

export type PatchEventTriggerRequestOutputConfig = {
  publishDestination?: PatchEventTriggerRequestPublishDestination | undefined;
  brandVoiceId?: string | undefined;
};

export type PatchEventTriggerRequest = {
  sourceType: PatchEventTriggerRequestSourceType;
  sourceConfig: PatchEventTriggerRequestSourceConfig;
  targets: PatchEventTriggerRequestTargets;
  outputType: PatchEventTriggerRequestOutputType;
  outputConfig?: PatchEventTriggerRequestOutputConfig | undefined;
  enabled: boolean;
  autoPublish?: boolean | undefined;
};

/** @internal */
export const PatchEventTriggerRequestSourceType$outboundSchema: z.ZodMiniEnum<
  typeof PatchEventTriggerRequestSourceType
> = z.enum(PatchEventTriggerRequestSourceType);

/** @internal */
export const EventType$outboundSchema: z.ZodMiniEnum<typeof EventType> = z.enum(
  EventType,
);

/** @internal */
export type PatchEventTriggerRequestSourceConfig$Outbound = {
  eventTypes: Array<string>;
  includePreReleases: boolean;
};

/** @internal */
export const PatchEventTriggerRequestSourceConfig$outboundSchema: z.ZodMiniType<
  PatchEventTriggerRequestSourceConfig$Outbound,
  PatchEventTriggerRequestSourceConfig
> = z.object({
  eventTypes: z.array(EventType$outboundSchema),
  includePreReleases: z._default(z.boolean(), true),
});

export function patchEventTriggerRequestSourceConfigToJSON(
  patchEventTriggerRequestSourceConfig: PatchEventTriggerRequestSourceConfig,
): string {
  return JSON.stringify(
    PatchEventTriggerRequestSourceConfig$outboundSchema.parse(
      patchEventTriggerRequestSourceConfig,
    ),
  );
}

/** @internal */
export type PatchEventTriggerRequestTargets$Outbound = {
  repositoryIds: Array<string>;
};

/** @internal */
export const PatchEventTriggerRequestTargets$outboundSchema: z.ZodMiniType<
  PatchEventTriggerRequestTargets$Outbound,
  PatchEventTriggerRequestTargets
> = z.object({
  repositoryIds: z.array(z.string()),
});

export function patchEventTriggerRequestTargetsToJSON(
  patchEventTriggerRequestTargets: PatchEventTriggerRequestTargets,
): string {
  return JSON.stringify(
    PatchEventTriggerRequestTargets$outboundSchema.parse(
      patchEventTriggerRequestTargets,
    ),
  );
}

/** @internal */
export const PatchEventTriggerRequestOutputType$outboundSchema: z.ZodMiniEnum<
  typeof PatchEventTriggerRequestOutputType
> = z.enum(PatchEventTriggerRequestOutputType);

/** @internal */
export const PatchEventTriggerRequestPublishDestination$outboundSchema:
  z.ZodMiniEnum<typeof PatchEventTriggerRequestPublishDestination> = z.enum(
    PatchEventTriggerRequestPublishDestination,
  );

/** @internal */
export type PatchEventTriggerRequestOutputConfig$Outbound = {
  publishDestination?: string | undefined;
  brandVoiceId?: string | undefined;
};

/** @internal */
export const PatchEventTriggerRequestOutputConfig$outboundSchema: z.ZodMiniType<
  PatchEventTriggerRequestOutputConfig$Outbound,
  PatchEventTriggerRequestOutputConfig
> = z.object({
  publishDestination: z.optional(
    PatchEventTriggerRequestPublishDestination$outboundSchema,
  ),
  brandVoiceId: z.optional(z.string()),
});

export function patchEventTriggerRequestOutputConfigToJSON(
  patchEventTriggerRequestOutputConfig: PatchEventTriggerRequestOutputConfig,
): string {
  return JSON.stringify(
    PatchEventTriggerRequestOutputConfig$outboundSchema.parse(
      patchEventTriggerRequestOutputConfig,
    ),
  );
}

/** @internal */
export type PatchEventTriggerRequest$Outbound = {
  sourceType: string;
  sourceConfig: PatchEventTriggerRequestSourceConfig$Outbound;
  targets: PatchEventTriggerRequestTargets$Outbound;
  outputType: string;
  outputConfig?: PatchEventTriggerRequestOutputConfig$Outbound | undefined;
  enabled: boolean;
  autoPublish: boolean;
};

/** @internal */
export const PatchEventTriggerRequest$outboundSchema: z.ZodMiniType<
  PatchEventTriggerRequest$Outbound,
  PatchEventTriggerRequest
> = z.object({
  sourceType: PatchEventTriggerRequestSourceType$outboundSchema,
  sourceConfig: z.lazy(() =>
    PatchEventTriggerRequestSourceConfig$outboundSchema
  ),
  targets: z.lazy(() => PatchEventTriggerRequestTargets$outboundSchema),
  outputType: PatchEventTriggerRequestOutputType$outboundSchema,
  outputConfig: z.optional(
    z.lazy(() => PatchEventTriggerRequestOutputConfig$outboundSchema),
  ),
  enabled: z.boolean(),
  autoPublish: z._default(z.boolean(), false),
});

export function patchEventTriggerRequestToJSON(
  patchEventTriggerRequest: PatchEventTriggerRequest,
): string {
  return JSON.stringify(
    PatchEventTriggerRequest$outboundSchema.parse(patchEventTriggerRequest),
  );
}
