/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 766e19c7828e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  GeoContentBriefDocument,
  GeoContentBriefDocument$inboundSchema,
} from "./geo-content-brief-document.js";

export const PlanGeoContentBriefResponseStatus = {
  Draft: "draft",
  Approved: "approved",
  Writing: "writing",
  Completed: "completed",
  Failed: "failed",
} as const;
export type PlanGeoContentBriefResponseStatus = OpenEnum<
  typeof PlanGeoContentBriefResponseStatus
>;

export type PlanGeoContentBriefResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type PlanGeoContentBriefResponse = {
  briefId: string;
  brief: GeoContentBriefDocument;
  status: PlanGeoContentBriefResponseStatus;
  runId: string | null;
  postId: string | null;
  organization: PlanGeoContentBriefResponseOrganization;
};

/** @internal */
export const PlanGeoContentBriefResponseStatus$inboundSchema: z.ZodMiniType<
  PlanGeoContentBriefResponseStatus,
  unknown
> = openEnums.inboundSchema(PlanGeoContentBriefResponseStatus);

/** @internal */
export const PlanGeoContentBriefResponseOrganization$inboundSchema:
  z.ZodMiniType<PlanGeoContentBriefResponseOrganization, unknown> = z.object({
    id: types.string(),
    slug: types.string(),
    name: types.string(),
    logo: types.nullable(types.string()),
  });

export function planGeoContentBriefResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<
  PlanGeoContentBriefResponseOrganization,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PlanGeoContentBriefResponseOrganization$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PlanGeoContentBriefResponseOrganization' from JSON`,
  );
}

/** @internal */
export const PlanGeoContentBriefResponse$inboundSchema: z.ZodMiniType<
  PlanGeoContentBriefResponse,
  unknown
> = z.object({
  briefId: types.string(),
  brief: GeoContentBriefDocument$inboundSchema,
  status: PlanGeoContentBriefResponseStatus$inboundSchema,
  runId: types.nullable(types.string()),
  postId: types.nullable(types.string()),
  organization: z.lazy(() =>
    PlanGeoContentBriefResponseOrganization$inboundSchema
  ),
});

export function planGeoContentBriefResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlanGeoContentBriefResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlanGeoContentBriefResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlanGeoContentBriefResponse' from JSON`,
  );
}
