/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b6fc7725062e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ScheduledPublication,
  ScheduledPublication$inboundSchema,
} from "./scheduled-publication.js";

export type PostSchedule = {
  postId: string;
  scheduledAt: Date;
  timeZone: string;
  publications: Array<ScheduledPublication>;
};

/** @internal */
export const PostSchedule$inboundSchema: z.ZodMiniType<PostSchedule, unknown> =
  z.object({
    postId: types.string(),
    scheduledAt: types.date(),
    timeZone: types.string(),
    publications: z.array(ScheduledPublication$inboundSchema),
  });

export function postScheduleFromJSON(
  jsonString: string,
): SafeParseResult<PostSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostSchedule' from JSON`,
  );
}
