/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 926a634d7740
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { PostSchedule, PostSchedule$inboundSchema } from "./post-schedule.js";

export type PostScheduleResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type PostScheduleResponse = {
  organization: PostScheduleResponseOrganization;
  schedule: PostSchedule | null;
};

/** @internal */
export const PostScheduleResponseOrganization$inboundSchema: z.ZodMiniType<
  PostScheduleResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function postScheduleResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<PostScheduleResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostScheduleResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostScheduleResponseOrganization' from JSON`,
  );
}

/** @internal */
export const PostScheduleResponse$inboundSchema: z.ZodMiniType<
  PostScheduleResponse,
  unknown
> = z.object({
  organization: z.lazy(() => PostScheduleResponseOrganization$inboundSchema),
  schedule: types.nullable(PostSchedule$inboundSchema),
});

export function postScheduleResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostScheduleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostScheduleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostScheduleResponse' from JSON`,
  );
}
