/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 08043f4450fb
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const PublicStatusResponseStatus = {
  Ok: "ok",
} as const;
export type PublicStatusResponseStatus = ClosedEnum<
  typeof PublicStatusResponseStatus
>;

export const Service = {
  NotraAPI: "Notra API",
} as const;
export type Service = ClosedEnum<typeof Service>;

export const TypeEnum = {
  Bearer: "bearer",
} as const;
export type TypeEnum = ClosedEnum<typeof TypeEnum>;

export type PublicStatusResponseAuthentication = {
  type: TypeEnum;
  resourceMetadata: string;
  guide: string;
};

export type PublicStatusResponse = {
  status: PublicStatusResponseStatus;
  service: Service;
  version: string;
  public: true;
  authentication: PublicStatusResponseAuthentication;
};

/** @internal */
export const PublicStatusResponseStatus$inboundSchema: z.ZodMiniEnum<
  typeof PublicStatusResponseStatus
> = z.enum(PublicStatusResponseStatus);

/** @internal */
export const Service$inboundSchema: z.ZodMiniEnum<typeof Service> = z.enum(
  Service,
);

/** @internal */
export const TypeEnum$inboundSchema: z.ZodMiniEnum<typeof TypeEnum> = z.enum(
  TypeEnum,
);

/** @internal */
export const PublicStatusResponseAuthentication$inboundSchema: z.ZodMiniType<
  PublicStatusResponseAuthentication,
  unknown
> = z.pipe(
  z.object({
    type: TypeEnum$inboundSchema,
    resource_metadata: types.string(),
    guide: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "resource_metadata": "resourceMetadata",
    });
  }),
);

export function publicStatusResponseAuthenticationFromJSON(
  jsonString: string,
): SafeParseResult<PublicStatusResponseAuthentication, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PublicStatusResponseAuthentication$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicStatusResponseAuthentication' from JSON`,
  );
}

/** @internal */
export const PublicStatusResponse$inboundSchema: z.ZodMiniType<
  PublicStatusResponse,
  unknown
> = z.object({
  status: PublicStatusResponseStatus$inboundSchema,
  service: Service$inboundSchema,
  version: types.string(),
  public: types.literal(true),
  authentication: z.lazy(() =>
    PublicStatusResponseAuthentication$inboundSchema
  ),
});

export function publicStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<PublicStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicStatusResponse' from JSON`,
  );
}
