/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3351f6eb1107
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type RunGeoSequenceResponseOrganization = {
  id: string;
  slug: string;
  name: string;
  logo: string | null;
};

export type RunGeoSequenceResponse = {
  /**
   * Recorded answers across every engine that responded.
   */
  checks: number;
  /**
   * How many of those answers mentioned the tracked brand.
   */
  mentions: number;
  /**
   * Engines the conversation was played against.
   */
  engines: Array<string>;
  organization: RunGeoSequenceResponseOrganization;
};

/** @internal */
export const RunGeoSequenceResponseOrganization$inboundSchema: z.ZodMiniType<
  RunGeoSequenceResponseOrganization,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  name: types.string(),
  logo: types.nullable(types.string()),
});

export function runGeoSequenceResponseOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<RunGeoSequenceResponseOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RunGeoSequenceResponseOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunGeoSequenceResponseOrganization' from JSON`,
  );
}

/** @internal */
export const RunGeoSequenceResponse$inboundSchema: z.ZodMiniType<
  RunGeoSequenceResponse,
  unknown
> = z.object({
  checks: types.number(),
  mentions: types.number(),
  engines: z.array(types.string()),
  organization: z.lazy(() => RunGeoSequenceResponseOrganization$inboundSchema),
});

export function runGeoSequenceResponseFromJSON(
  jsonString: string,
): SafeParseResult<RunGeoSequenceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RunGeoSequenceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunGeoSequenceResponse' from JSON`,
  );
}
