/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6c8cb89f9b8a
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const DestinationEnum = {
  Notra: "notra",
  Github: "github",
  Social: "social",
} as const;
export type DestinationEnum = OpenEnum<typeof DestinationEnum>;

export type ConfigSocial = {
  destination: "social";
  accountId: string;
};

export type ConfigGithub = {
  destination: "github";
  repositoryId: string;
  merge: boolean;
};

export type ConfigNotra = {
  destination: "notra";
};

export type Config =
  | ConfigNotra
  | ConfigGithub
  | ConfigSocial
  | discriminatedUnionTypes.Unknown<"destination">;

/**
 * scheduled → publishing → published or failed. Failed destinations are retried automatically for transient errors before they end up failed.
 */
export const ScheduledPublicationStatus = {
  Scheduled: "scheduled",
  Publishing: "publishing",
  Published: "published",
  Failed: "failed",
  Canceled: "canceled",
} as const;
/**
 * scheduled → publishing → published or failed. Failed destinations are retried automatically for transient errors before they end up failed.
 */
export type ScheduledPublicationStatus = OpenEnum<
  typeof ScheduledPublicationStatus
>;

export type ScheduledPublication = {
  id: string;
  destination: DestinationEnum;
  config:
    | ConfigNotra
    | ConfigGithub
    | ConfigSocial
    | discriminatedUnionTypes.Unknown<"destination">;
  /**
   * scheduled → publishing → published or failed. Failed destinations are retried automatically for transient errors before they end up failed.
   */
  status: ScheduledPublicationStatus;
  scheduledAt: Date;
  timeZone: string;
  attempts: number;
  errorCode: string | null;
  lastError: string | null;
  /**
   * Pull request or social post URL once published.
   */
  resultUrl: string | null;
  publishedAt: Date | null;
};

/** @internal */
export const DestinationEnum$inboundSchema: z.ZodMiniType<
  DestinationEnum,
  unknown
> = openEnums.inboundSchema(DestinationEnum);

/** @internal */
export const ConfigSocial$inboundSchema: z.ZodMiniType<ConfigSocial, unknown> =
  z.object({
    destination: types.literal("social"),
    accountId: types.string(),
  });

export function configSocialFromJSON(
  jsonString: string,
): SafeParseResult<ConfigSocial, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConfigSocial$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConfigSocial' from JSON`,
  );
}

/** @internal */
export const ConfigGithub$inboundSchema: z.ZodMiniType<ConfigGithub, unknown> =
  z.object({
    destination: types.literal("github"),
    repositoryId: types.string(),
    merge: types.boolean(),
  });

export function configGithubFromJSON(
  jsonString: string,
): SafeParseResult<ConfigGithub, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConfigGithub$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConfigGithub' from JSON`,
  );
}

/** @internal */
export const ConfigNotra$inboundSchema: z.ZodMiniType<ConfigNotra, unknown> = z
  .object({
    destination: types.literal("notra"),
  });

export function configNotraFromJSON(
  jsonString: string,
): SafeParseResult<ConfigNotra, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConfigNotra$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConfigNotra' from JSON`,
  );
}

/** @internal */
export const Config$inboundSchema: z.ZodMiniType<Config, unknown> =
  discriminatedUnion("destination", {
    notra: z.lazy(() => ConfigNotra$inboundSchema),
    github: z.lazy(() => ConfigGithub$inboundSchema),
    social: z.lazy(() => ConfigSocial$inboundSchema),
  });

export function configFromJSON(
  jsonString: string,
): SafeParseResult<Config, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Config$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Config' from JSON`,
  );
}

/** @internal */
export const ScheduledPublicationStatus$inboundSchema: z.ZodMiniType<
  ScheduledPublicationStatus,
  unknown
> = openEnums.inboundSchema(ScheduledPublicationStatus);

/** @internal */
export const ScheduledPublication$inboundSchema: z.ZodMiniType<
  ScheduledPublication,
  unknown
> = z.object({
  id: types.string(),
  destination: DestinationEnum$inboundSchema,
  config: discriminatedUnion("destination", {
    notra: z.lazy(() => ConfigNotra$inboundSchema),
    github: z.lazy(() => ConfigGithub$inboundSchema),
    social: z.lazy(() => ConfigSocial$inboundSchema),
  }),
  status: ScheduledPublicationStatus$inboundSchema,
  scheduledAt: types.date(),
  timeZone: types.string(),
  attempts: types.number(),
  errorCode: types.nullable(types.string()),
  lastError: types.nullable(types.string()),
  resultUrl: types.nullable(types.string()),
  publishedAt: types.nullable(types.date()),
});

export function scheduledPublicationFromJSON(
  jsonString: string,
): SafeParseResult<ScheduledPublication, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduledPublication$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduledPublication' from JSON`,
  );
}
