/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1b781361675a
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const Model = {
  Auto: "auto",
  AnthropicClaudeOpus47: "anthropic/claude-opus-4.7",
  AnthropicClaudeSonnet46: "anthropic/claude-sonnet-4.6",
  AnthropicClaudeHaiku45: "anthropic/claude-haiku-4.5",
  OpenaiGpt54: "openai/gpt-5.4",
} as const;
export type Model = ClosedEnum<typeof Model>;

export const ThinkingLevel = {
  Off: "off",
  Low: "low",
  Medium: "medium",
  High: "high",
} as const;
export type ThinkingLevel = ClosedEnum<typeof ThinkingLevel>;

export type ContextLinearTeam = {
  type: "linear-team";
  integrationId: string;
  teamName?: string | undefined;
};

export type ContextGithubRepo = {
  type: "github-repo";
  integrationId: string;
  owner: string;
  repo: string;
};

export type Context = ContextGithubRepo | ContextLinearTeam;

export type SendChatMessageRequest = {
  message: string;
  model?: Model | undefined;
  enableThinking?: boolean | undefined;
  thinkingLevel?: ThinkingLevel | undefined;
  timezone?: string | undefined;
  context?: Array<ContextGithubRepo | ContextLinearTeam> | undefined;
};

/** @internal */
export const Model$outboundSchema: z.ZodMiniEnum<typeof Model> = z.enum(Model);

/** @internal */
export const ThinkingLevel$outboundSchema: z.ZodMiniEnum<typeof ThinkingLevel> =
  z.enum(ThinkingLevel);

/** @internal */
export type ContextLinearTeam$Outbound = {
  type: "linear-team";
  integrationId: string;
  teamName?: string | undefined;
};

/** @internal */
export const ContextLinearTeam$outboundSchema: z.ZodMiniType<
  ContextLinearTeam$Outbound,
  ContextLinearTeam
> = z.object({
  type: z.literal("linear-team"),
  integrationId: z.string(),
  teamName: z.optional(z.string()),
});

export function contextLinearTeamToJSON(
  contextLinearTeam: ContextLinearTeam,
): string {
  return JSON.stringify(
    ContextLinearTeam$outboundSchema.parse(contextLinearTeam),
  );
}

/** @internal */
export type ContextGithubRepo$Outbound = {
  type: "github-repo";
  integrationId: string;
  owner: string;
  repo: string;
};

/** @internal */
export const ContextGithubRepo$outboundSchema: z.ZodMiniType<
  ContextGithubRepo$Outbound,
  ContextGithubRepo
> = z.object({
  type: z.literal("github-repo"),
  integrationId: z.string(),
  owner: z.string(),
  repo: z.string(),
});

export function contextGithubRepoToJSON(
  contextGithubRepo: ContextGithubRepo,
): string {
  return JSON.stringify(
    ContextGithubRepo$outboundSchema.parse(contextGithubRepo),
  );
}

/** @internal */
export type Context$Outbound =
  | ContextGithubRepo$Outbound
  | ContextLinearTeam$Outbound;

/** @internal */
export const Context$outboundSchema: z.ZodMiniType<Context$Outbound, Context> =
  z.union([
    z.lazy(() => ContextGithubRepo$outboundSchema),
    z.lazy(() => ContextLinearTeam$outboundSchema),
  ]);

export function contextToJSON(context: Context): string {
  return JSON.stringify(Context$outboundSchema.parse(context));
}

/** @internal */
export type SendChatMessageRequest$Outbound = {
  message: string;
  model?: string | undefined;
  enableThinking?: boolean | undefined;
  thinkingLevel?: string | undefined;
  timezone?: string | undefined;
  context?:
    | Array<ContextGithubRepo$Outbound | ContextLinearTeam$Outbound>
    | undefined;
};

/** @internal */
export const SendChatMessageRequest$outboundSchema: z.ZodMiniType<
  SendChatMessageRequest$Outbound,
  SendChatMessageRequest
> = z.object({
  message: z.string(),
  model: z.optional(Model$outboundSchema),
  enableThinking: z.optional(z.boolean()),
  thinkingLevel: z.optional(ThinkingLevel$outboundSchema),
  timezone: z.optional(z.string()),
  context: z.optional(
    z.array(z.union([
      z.lazy(() => ContextGithubRepo$outboundSchema),
      z.lazy(() =>
        ContextLinearTeam$outboundSchema
      ),
    ])),
  ),
});

export function sendChatMessageRequestToJSON(
  sendChatMessageRequest: SendChatMessageRequest,
): string {
  return JSON.stringify(
    SendChatMessageRequest$outboundSchema.parse(sendChatMessageRequest),
  );
}
