/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: abeebd6535f4
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SkillSummary = {
  id: string;
  name: string;
  description: string;
  isSystem: boolean;
  updatedAt: string;
};

/** @internal */
export const SkillSummary$inboundSchema: z.ZodMiniType<SkillSummary, unknown> =
  z.object({
    id: types.string(),
    name: types.string(),
    description: types.string(),
    isSystem: types.boolean(),
    updatedAt: types.string(),
  });

export function skillSummaryFromJSON(
  jsonString: string,
): SafeParseResult<SkillSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkillSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkillSummary' from JSON`,
  );
}
