/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5f4c46b386d4
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Triage status.
 */
export const UpdateFeedbackRequestStatus = {
  New: "new",
  Triaged: "triaged",
  Resolved: "resolved",
  Archived: "archived",
} as const;
/**
 * Triage status.
 */
export type UpdateFeedbackRequestStatus = ClosedEnum<
  typeof UpdateFeedbackRequestStatus
>;

export type UpdateFeedbackRequest = {
  /**
   * Triage status.
   */
  status: UpdateFeedbackRequestStatus;
};

/** @internal */
export const UpdateFeedbackRequestStatus$outboundSchema: z.ZodMiniEnum<
  typeof UpdateFeedbackRequestStatus
> = z.enum(UpdateFeedbackRequestStatus);

/** @internal */
export type UpdateFeedbackRequest$Outbound = {
  status: string;
};

/** @internal */
export const UpdateFeedbackRequest$outboundSchema: z.ZodMiniType<
  UpdateFeedbackRequest$Outbound,
  UpdateFeedbackRequest
> = z.object({
  status: UpdateFeedbackRequestStatus$outboundSchema,
});

export function updateFeedbackRequestToJSON(
  updateFeedbackRequest: UpdateFeedbackRequest,
): string {
  return JSON.stringify(
    UpdateFeedbackRequest$outboundSchema.parse(updateFeedbackRequest),
  );
}
